<!DOCTYPE html>
                <html>
                <head>
                    <title>#Blocksport #Airdrop Campaign is LIVE now</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://blocksport.medium.com/blocksport-airdrop-campaign-is-live-now-ab678305b562"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/?source=post_page-----ab678305b562--------------------------------">Author : Blocksport</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>#Blocksport #Airdrop Campaign is LIVE now</h3></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*4LkHmfTgcnWdYvW8MI9n_g.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Reward Pool: 200000 $BSPT tokens<br></br>Get up to 25 BSPT Tokens for participation and 10 BSPT tokens for referral</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">🏾Do 6 Tasks & Get 25 #BSPT tokens<br></br>1. To follow Blocksport Twitter<br></br>2. 1. To follow Blocksport NFT Twitter<br></br>3. To join the Telegram group<br></br>4. To follow Facebook<br></br>5. To follow Medium<br></br>6. To like, tag 3 members and retweet the pinned tweet</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">🏾Refer More To Earn More</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">️Airdrop Link: <a href="https://t.me/BlockSportAirdropbot?start=r0617145492" target="_self">https://t.me/BlocksportAirdropbot?start=r0617145492</a></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Rules and Tips<br></br>1. Early Participants Get Better Rewards<br></br>2. First Come, First Served<br></br>3. It all depends on how soon you participate after we announce an airdrop. Be alert, and you’ll get a greater chance of receiving an airdrop on 100% completion of the tasks.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Other Activity Rules<br></br>- All rewards will be distributed directly to participant’s ERC20 wallet addresses and will not be confirmed in a further announcement.<br></br>- Blocksport reserves the right to cancel or amend any Activity or Activity Rules at our sole discretion.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Good Luck guys!</p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>