<!DOCTYPE html>
                <html>
                <head>
                    <title>AI-Based Drug Discovery Pipeline Generates Novel Drug Compounds against Coronavirus</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/syncedreview/ai-based-drug-discovery-pipeline-generates-novel-drug-compounds-against-coronavirus-31829015d0d"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@synced?source=post_page-----31829015d0d--------------------------------">Author : Synced</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>AI-Based Drug Discovery Pipeline Generates Novel Drug Compounds against Coronavirus</h3></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Uqw6JMO6GH28TJwxMCdcMQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Uqw6JMO6GH28TJwxMCdcMQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Uqw6JMO6GH28TJwxMCdcMQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Uqw6JMO6GH28TJwxMCdcMQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Uqw6JMO6GH28TJwxMCdcMQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Uqw6JMO6GH28TJwxMCdcMQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Uqw6JMO6GH28TJwxMCdcMQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Uqw6JMO6GH28TJwxMCdcMQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Uqw6JMO6GH28TJwxMCdcMQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Uqw6JMO6GH28TJwxMCdcMQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Uqw6JMO6GH28TJwxMCdcMQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Uqw6JMO6GH28TJwxMCdcMQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Uqw6JMO6GH28TJwxMCdcMQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*Uqw6JMO6GH28TJwxMCdcMQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*Uqw6JMO6GH28TJwxMCdcMQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A new study leverages an established AI-based drug discovery pipeline to produce molecular structures as part of the widening fight against the 2019-nCoV outbreak. Researchers say results from the study show cost-effectiveness and time efficiency of the new method for the development of novel drug compounds and treatments against coronavirus infection.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The paper <em>Potential COVID-2019 3C-like Protease Inhibitors Designed Using Generative Deep Learning Approaches</em> and the molecules themselves have been published on ResearchGate and ChemRxiv by researchers from Insilico Medicine. The biotech company began devoting part of its generative chemistry pipeline to designing novel drug-like inhibitors of 2019-nCoV on January 28. The researchers note that “None of the molecules have been synthesized or tested in vitro or in vivo. <strong>These are not drugs for 2019-nCov coronavirus. </strong>Expert medicinal chemists are encouraged to review and comment on the molecules in the article and on the website. ”</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Most current efforts against the coronavirus are investing heavy on repurposing of clinically-approved drugs and virtual screening for molecules that are available from chemical libraries. Researchers have identified one of the key 2019-nCoV protein targets as the 3C-like protease for which the crystal structure is known. <strong>If a drug can be developed that inhibits conserved proteases it may be capable of preventing replication and proliferation of the virus.</strong> It could also reduce the risk of mutation mediated drug-resistance, allowing it to remain effective. For example, in the case of the SARS-CoV, which also belongs to the family of coronaviruses, inhibitors targeting the main protease were the most effective means to alleviate the epidemic.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Since the protease target for 2019-nCoV and its sequence and structure are known, Insilico researchers only applied the generative chemistry pipeline to generate possible drug-like hits. They used the generative pipeline for three input data types: crystal structure, homology models, and co-crystalized ligand. The generative deep learning approaches can automatically extract high-dimensional abstract information from the molecular structures without manual feature design. Also, they can learn the nonlinear mapping between molecular structures corresponding to the biological and pharmacological properties accordingly.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Kvf74TEi13hL5QYYnZXZ6g.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Kvf74TEi13hL5QYYnZXZ6g.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Kvf74TEi13hL5QYYnZXZ6g.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Kvf74TEi13hL5QYYnZXZ6g.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Kvf74TEi13hL5QYYnZXZ6g.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Kvf74TEi13hL5QYYnZXZ6g.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Kvf74TEi13hL5QYYnZXZ6g.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Kvf74TEi13hL5QYYnZXZ6g.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Kvf74TEi13hL5QYYnZXZ6g.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Kvf74TEi13hL5QYYnZXZ6g.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Kvf74TEi13hL5QYYnZXZ6g.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Kvf74TEi13hL5QYYnZXZ6g.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Kvf74TEi13hL5QYYnZXZ6g.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*Kvf74TEi13hL5QYYnZXZ6g.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*Kvf74TEi13hL5QYYnZXZ6g.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*GYRb7j0H5bIQEw7ZE6dubQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*GYRb7j0H5bIQEw7ZE6dubQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*GYRb7j0H5bIQEw7ZE6dubQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*GYRb7j0H5bIQEw7ZE6dubQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*GYRb7j0H5bIQEw7ZE6dubQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*GYRb7j0H5bIQEw7ZE6dubQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*GYRb7j0H5bIQEw7ZE6dubQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*GYRb7j0H5bIQEw7ZE6dubQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*GYRb7j0H5bIQEw7ZE6dubQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*GYRb7j0H5bIQEw7ZE6dubQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*GYRb7j0H5bIQEw7ZE6dubQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*GYRb7j0H5bIQEw7ZE6dubQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*GYRb7j0H5bIQEw7ZE6dubQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*GYRb7j0H5bIQEw7ZE6dubQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*GYRb7j0H5bIQEw7ZE6dubQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*tJGwWhyTaVPfUfVmRT_4sw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*tJGwWhyTaVPfUfVmRT_4sw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*tJGwWhyTaVPfUfVmRT_4sw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*tJGwWhyTaVPfUfVmRT_4sw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*tJGwWhyTaVPfUfVmRT_4sw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*tJGwWhyTaVPfUfVmRT_4sw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*tJGwWhyTaVPfUfVmRT_4sw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*tJGwWhyTaVPfUfVmRT_4sw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*tJGwWhyTaVPfUfVmRT_4sw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*tJGwWhyTaVPfUfVmRT_4sw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*tJGwWhyTaVPfUfVmRT_4sw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*tJGwWhyTaVPfUfVmRT_4sw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*tJGwWhyTaVPfUfVmRT_4sw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*tJGwWhyTaVPfUfVmRT_4sw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*tJGwWhyTaVPfUfVmRT_4sw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The team used 28 machine learning models to generate molecular structures during the generative phase, and optimized the models with reinforcement learning leveraging the reward function. They deployed a wide variety of ML approaches to exploit various molecular representations — generative autoencoders, generative adversarial networks, genetic algorithms, etc. Every model was optimizing the reward function to exploit clusters and generate new molecules with high scores, and so after each launch of the generative pipeline researchers would select the highest-ranking structures for the next analysis. Insilico is actively <a href="https://insilico.com/ncov-sprint/" target="_self">publishing</a> the novel compounds it has generated using these approaches. The company says that although it is synthesizing, testing, and optimizing some molecules using its own resources, it is also seeking collaborators to help with the process.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The spread of the 2019-nCoV is having deep global economic and societal impact. The lack of effective antiviral strategies to treat the spread and prevent infections has increased the risk of infection in populations. Just last week, <em>MIT Technology Review</em> named Insilico’s techniques for AI-discovered molecules one of its “<a href="https://www.technologyreview.com/lists/technologies/2020/#ai-discovered-molecules" target="_self">10 Breakthrough Technologies 2020</a>”. If the new AI-designed molecular structures can help free humanity from the 2019-nCoV epidemic they will be front page news.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The paper <em>Potential COVID-2019 3C-like Protease Inhibitors Designed Using Generative Deep Learning Approaches </em>is on <a href="https://2019ncov.s3.ap-east-1.amazonaws.com/Insilico-Medicine-Generative-Sprint-2019-nCoV-Project.pdf" target="_self">arXiv</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Journalist</strong>: Fangyu Cai | <strong>Editor</strong>: Michael Sarazen</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Thinking of contributing to Synced Review? </strong>Synced’s new column<strong> </strong><a href="https://docs.google.com/forms/d/e/1FAIpQLSdaYAtvk8dtP__l1wvOjEKkQNAfZQNjX-G4OoEWcVU8jFIMug/viewform" target="_self">Share My Research</a><strong> </strong>welcomes scholars to share their own research breakthroughs with global AI enthusiasts.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*xX1uNpHzOHEIdJjE.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*xX1uNpHzOHEIdJjE.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*xX1uNpHzOHEIdJjE.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*xX1uNpHzOHEIdJjE.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*xX1uNpHzOHEIdJjE.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*xX1uNpHzOHEIdJjE.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*xX1uNpHzOHEIdJjE.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*xX1uNpHzOHEIdJjE.png 640w, https://miro.medium.com/v2/resize:fit:720/0*xX1uNpHzOHEIdJjE.png 720w, https://miro.medium.com/v2/resize:fit:750/0*xX1uNpHzOHEIdJjE.png 750w, https://miro.medium.com/v2/resize:fit:786/0*xX1uNpHzOHEIdJjE.png 786w, https://miro.medium.com/v2/resize:fit:828/0*xX1uNpHzOHEIdJjE.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*xX1uNpHzOHEIdJjE.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*xX1uNpHzOHEIdJjE.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*xX1uNpHzOHEIdJjE.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We know you don’t want to miss any story.<strong> Subscribe to our popular </strong><a href="https://mailchi.mp/2fb3aa308ad3/welcome-to-synced-global-ai-weekly-newsletter" target="_self">Synced Global AI Weekly</a> <strong>to get weekly AI updates.</strong></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:86%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 630px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*3YaqZzSS5ZlGUJdF.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*3YaqZzSS5ZlGUJdF.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*3YaqZzSS5ZlGUJdF.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*3YaqZzSS5ZlGUJdF.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*3YaqZzSS5ZlGUJdF.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*3YaqZzSS5ZlGUJdF.png 1100w, https://miro.medium.com/v2/resize:fit:1260/format:webp/0*3YaqZzSS5ZlGUJdF.png 1260w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 630px" srcset="https://miro.medium.com/v2/resize:fit:640/0*3YaqZzSS5ZlGUJdF.png 640w, https://miro.medium.com/v2/resize:fit:720/0*3YaqZzSS5ZlGUJdF.png 720w, https://miro.medium.com/v2/resize:fit:750/0*3YaqZzSS5ZlGUJdF.png 750w, https://miro.medium.com/v2/resize:fit:786/0*3YaqZzSS5ZlGUJdF.png 786w, https://miro.medium.com/v2/resize:fit:828/0*3YaqZzSS5ZlGUJdF.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*3YaqZzSS5ZlGUJdF.png 1100w, https://miro.medium.com/v2/resize:fit:1260/0*3YaqZzSS5ZlGUJdF.png 1260w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/630/0*3YaqZzSS5ZlGUJdF.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Need a comprehensive review of the past, present and future of modern AI research development? <a href="https://payhip.com/b/j8i2" target="_self">Trends of AI Technology Development Report</a><strong> </strong>is out!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://syncedreview.com/2018-500-company-ai-adaptivity-report/?source=post_page---------------------------" target="_self">2018 Fortune Global 500 Public Company AI Adaptivity Report</a><strong> </strong>is out!<br></br>Purchase a Kindle-formatted report on <a href="https://goo.gl/deesY3?source=post_page---------------------------" target="_self">Amazon</a><strong>.</strong><br></br>Apply for <a href="https://goo.gl/fLLXcX?source=post_page---------------------------" target="_self">Insight Partner Program</a> to get a complimentary full PDF report.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:86%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 630px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*CLA2ZI6wuCejhjgZ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*CLA2ZI6wuCejhjgZ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*CLA2ZI6wuCejhjgZ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*CLA2ZI6wuCejhjgZ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*CLA2ZI6wuCejhjgZ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*CLA2ZI6wuCejhjgZ.png 1100w, https://miro.medium.com/v2/resize:fit:1260/format:webp/0*CLA2ZI6wuCejhjgZ.png 1260w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 630px" srcset="https://miro.medium.com/v2/resize:fit:640/0*CLA2ZI6wuCejhjgZ.png 640w, https://miro.medium.com/v2/resize:fit:720/0*CLA2ZI6wuCejhjgZ.png 720w, https://miro.medium.com/v2/resize:fit:750/0*CLA2ZI6wuCejhjgZ.png 750w, https://miro.medium.com/v2/resize:fit:786/0*CLA2ZI6wuCejhjgZ.png 786w, https://miro.medium.com/v2/resize:fit:828/0*CLA2ZI6wuCejhjgZ.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*CLA2ZI6wuCejhjgZ.png 1100w, https://miro.medium.com/v2/resize:fit:1260/0*CLA2ZI6wuCejhjgZ.png 1260w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/630/0*CLA2ZI6wuCejhjgZ.png"></picture></div><br></div></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>