<!DOCTYPE html>
                <html>
                <head>
                    <title>AI in drug discovery is overhyped: examples from AstraZeneca, Harvard, Stanford and Insilico Medicine</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/the-ai-lab/artificial-intelligence-in-drug-discovery-is-overhyped-examples-from-astrazeneca-harvard-315d69a7f863"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@mostafab?source=post_page-----315d69a7f863--------------------------------">Author : Mostapha Benhenda</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>AI in drug discovery is overhyped: examples from AstraZeneca, Harvard, Stanford and Insilico Medicine</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Investments in AI for drug discovery are surging. Big Pharmas are throwing big bucks. <a href="https://labiotech.eu/exscientia-sanofi-ai-deal/" target="_self">Sanofi</a> signed a<strong> 300 Million dollars</strong> deal with the startup <a href="https://www.exscientia.co.uk/" target="_self">Exscientia</a>, and <a href="https://www.fiercebiotech.com/medtech/gsk-exscientia-ink-ai-based-drug-discovery-deal-worth-up-to-42m" target="_self">GSK</a> did the same for <strong>42 Million dollars</strong>. The Silicon Valley VC firm <a style="color:green" href="https://medium.com/u/df45fd4a749d?source=post_page-----315d69a7f863--------------------------------" target="_self">Andreessen Horowitz</a> launched a new <strong>450 Million dollars</strong> <a href="http://www.businessinsider.com/andreessen-horowitz-450-million-bio-fund-healthcare-2017-12" target="_self">bio investment fund</a>, with one focus area in applications of AI to drug discovery.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In this craze, lots of pharma/biotech companies and investors wonder whether they should jump on the bandwagon in 2018, or wait and see.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In this post, I argue that they must be <strong>careful</strong>, because pretty often, <strong>AI researchers overhype</strong> their achievements, to say the least. This practice is <strong>widespread</strong>, and for illustration purposes, I looked at recent research from one big Pharma, <a href="https://www.astrazeneca.com/our-science/gothenburg.html" target="_self">AstraZeneca</a>, two universities, <a href="http://aspuru.chem.harvard.edu/" target="_self">Harvard</a> and <a href="https://pande.stanford.edu/" target="_self">Stanford</a>, and one startup, <a href="http://www.insilico.com/" target="_self">Insilico Medicine</a>. These labs are quite reputable, they are producing otherwise interesting research.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Update: all of these labs answered. See the end of the post.</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I am only talking about the tip of the iceberg here, the situation is often worse elsewhere. For example, I won’t even talk about companies like <a href="https://www.ibm.com/blogs/insights-on-business/healthcare/accelerating-research-ai-watson-drug-discovery/" target="_self">IBM Watson</a>, who overhype their proprietary solutions. This <a href="https://medium.com/chasing-buzzwords/should-ibm-open-source-watson-ce5bfae460a1" target="_self">secrecy</a> helps them escape public criticism, until they are caught up by the <a href="https://medcitynews.com/2017/09/former-ibm-employee-ai-truth-needs-come/?rf=1" target="_self">reality</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">However, I am not saying that AI should be discarded completely. In an innovative environment like drug discovery, <strong>staying behind is not an option</strong>. First-movers enjoy a huge competitive advantage. A good compromise is then to <strong>move quickly but carefully</strong>, and to solicit <strong>counter-expertise</strong> along the way.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">For these counter-expertise services, pharma players can ask<strong> </strong><a href="https://melwy.com" target="_self">Startcrowd</a><strong>, by </strong><a href="mailto:mostaphabenhenda@gmail.com" target="_self">clicking here</a>. Startcrowd is an online network of AI experts and enthusiasts, well-positioned to deliver <strong>independent counter-expertise</strong>. We tap into the talent pool emerging from online education. It keeps Startcrowd away from the conflicts of interests spoiling the Pharma industry.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This counter-expertise is a way to avoid new disappointments with computer-aided methods. Pharma veterans remember the <a href="https://www.forbes.com/sites/brucebooth/2017/04/26/four-decades-of-hacking-biotech-and-yet-biology-still-consumes-everything/#1499cc0a779e" target="_self">epic failure of rational drug design</a> in the 1980’s. At that time, big Pharmas were promising the next industrial revolution. It didn’t happen.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*3BPvKR7TK-RgB6tvzUq1MA.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Fortune magazine cover, 1981</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I am <strong>optimistic</strong> that <strong>things can be different</strong> in 2018. It’s not really because of breakthroughs in artificial intelligence, but rather because R&D organization can be improved: stronger<strong> checks and balances </strong>are possible now, with the rise of <strong>online education</strong> (<a href="https://www.coursera.org/" target="_self">Coursera</a>, <a href="https://www.edx.org/" target="_self">EdX</a>…) and <strong>social medias</strong>. They present new opportunities for<strong> open peer-review</strong>, which can <strong>deflate the bubble</strong>. The mission of <a href="https://melwy.com" target="_self">Startcrowd</a> is to accelerate this trend.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now, let’s get into the technical part, with some recent examples of overhyped AI research.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:56%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 425px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*B_V-eO0zTMMSp4X0kRkXSg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*B_V-eO0zTMMSp4X0kRkXSg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*B_V-eO0zTMMSp4X0kRkXSg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*B_V-eO0zTMMSp4X0kRkXSg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*B_V-eO0zTMMSp4X0kRkXSg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*B_V-eO0zTMMSp4X0kRkXSg.png 1100w, https://miro.medium.com/v2/resize:fit:850/format:webp/1*B_V-eO0zTMMSp4X0kRkXSg.png 850w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 425px" srcset="https://miro.medium.com/v2/resize:fit:640/1*B_V-eO0zTMMSp4X0kRkXSg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*B_V-eO0zTMMSp4X0kRkXSg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*B_V-eO0zTMMSp4X0kRkXSg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*B_V-eO0zTMMSp4X0kRkXSg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*B_V-eO0zTMMSp4X0kRkXSg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*B_V-eO0zTMMSp4X0kRkXSg.png 1100w, https://miro.medium.com/v2/resize:fit:850/1*B_V-eO0zTMMSp4X0kRkXSg.png 850w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/425/1*B_V-eO0zTMMSp4X0kRkXSg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In <a href="https://arxiv.org/abs/1701.01329" target="_self">this paper</a>, AstraZeneca researchers (joint with others) want to generate novel molecules using <strong>recurrent neural networks </strong>and <strong>reinforcement learning</strong>. This question is important because a creative AI should bring <strong>more diversity</strong> to the lead generation pipeline.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This paper caught my attention because of the large part devoted to the evaluation of the model. It has the appearance of depth. They introduce various metrics, based on <a href="https://en.wikipedia.org/wiki/Jaccard_index" target="_self">Tanimoto-similarity</a> and on <a href="https://en.wikipedia.org/wiki/Levenshtein_distance" target="_self">Levenshtein distance</a>. They provide an impressive number of visualizations, using <a href="https://en.wikipedia.org/wiki/Histogram" target="_self">histograms</a>, <a href="https://en.wikipedia.org/wiki/Violin_plot" target="_self">Violin plots</a> and <a href="https://en.wikipedia.org/wiki/T-distributed_stochastic_neighbor_embedding" target="_self">t-SNE</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">However, all their measures are made between AI-generated molecules on the one hand, and natural molecules on the other hand. They always ‘omitted’ to measure the distance of AI-generated molecules with each other. This omission allows to build an <strong>illusion of diversity</strong>: a large distance between AI-generated and natural molecules allows to think that the AI got creative, and that it explored new directions in the chemical space. It would mean that we got something like this graphic:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:34%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 267px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 1100w, https://miro.medium.com/v2/resize:fit:534/format:webp/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 534w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 267px" srcset="https://miro.medium.com/v2/resize:fit:640/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 1100w, https://miro.medium.com/v2/resize:fit:534/1*CN7RIRaEIFdphns3FfCR-Q.jpeg 534w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/267/1*CN7RIRaEIFdphns3FfCR-Q.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Real diversity: AI-generated molecules (blue), and natural molecules (red).</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">However, if the distance of AI-generated molecules with each other remains small, it means that we fell into the trivial situation where the model generated a stream of molecules located all at the same place. No diversity is generated, and we are actually left in a situation like this:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:17%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 149px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:298/format:webp/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 298w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 149px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:298/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg 298w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/149/1*Vs-oYL7iVPxLGmgHoLWmqA.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Illusion of diversity: there is still a large diversity between the AI-generated molecule (blue) and natural molecules (red).</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Simply put, this AstraZeneca paper misses the <a href="https://en.wikipedia.org/wiki/Elephant_in_the_room" target="_self">elephant in the room</a>. This problem is still not addressed in more recent papers by other AstraZeneca researchers (<a href="https://arxiv.org/abs/1704.07555" target="_self">here</a> and <a href="https://arxiv.org/abs/1711.07839" target="_self">here</a>).</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:61%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 459px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 1100w, https://miro.medium.com/v2/resize:fit:918/format:webp/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 918w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 459px" srcset="https://miro.medium.com/v2/resize:fit:640/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 1100w, https://miro.medium.com/v2/resize:fit:918/1*aN6kNRoxddfHoAdoKUtF9g.jpeg 918w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/459/1*aN6kNRoxddfHoAdoKUtF9g.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Elephant in the room</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">For a more technical discussion, see pages 6–7 of my paper <a href="https://arxiv.org/abs/1708.08227" target="_self">here</a>.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:60%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 449px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*zDf3WXbr1tFGE0YCGojqHA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*zDf3WXbr1tFGE0YCGojqHA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*zDf3WXbr1tFGE0YCGojqHA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*zDf3WXbr1tFGE0YCGojqHA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*zDf3WXbr1tFGE0YCGojqHA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*zDf3WXbr1tFGE0YCGojqHA.png 1100w, https://miro.medium.com/v2/resize:fit:898/format:webp/1*zDf3WXbr1tFGE0YCGojqHA.png 898w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 449px" srcset="https://miro.medium.com/v2/resize:fit:640/1*zDf3WXbr1tFGE0YCGojqHA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*zDf3WXbr1tFGE0YCGojqHA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*zDf3WXbr1tFGE0YCGojqHA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*zDf3WXbr1tFGE0YCGojqHA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*zDf3WXbr1tFGE0YCGojqHA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*zDf3WXbr1tFGE0YCGojqHA.png 1100w, https://miro.medium.com/v2/resize:fit:898/1*zDf3WXbr1tFGE0YCGojqHA.png 898w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/449/1*zDf3WXbr1tFGE0YCGojqHA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">At Harvard, a team noticed this diversity issue. By looking at the samples generated by the AI, they felt something was going wrong. They tried to do something about it, and they proposed the<strong> ORGAN model</strong>, <a href="https://arxiv.org/abs/1705.10843" target="_self">here</a> and <a href="https://chemrxiv.org/articles/ORGANIC_1_pdf/5309668/3" target="_self">here</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Their idea is to bring more chemical diversity, and chemical realism, by correcting the generator with a second neural network, called discriminator<strong>. </strong>It penalizes the generator if the molecules look too unnatural. This idea is drawn from the literature in <strong>Generative Adversarial Networks (GAN)</strong>, a hyped topic within the AI community.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This idea is interesting, but their execution is terrible. They conclude that their ORGAN is better, but this claim is only based on their personal visual observation, without any quantitative support (see page 3 of <a href="https://arxiv.org/abs/1705.10843" target="_self">their paper</a>). Their quantitative <strong>experiments don’t support their conclusion.</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This had to be expected somehow, because as AstraZeneca, they only compare AI-generated molecules with natural ones, and they never compare AI-generated molecules with each other.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Moreover, the way they train their model is problematic. This can be seen by looking at the <a href="https://github.com/gablg1/ORGAN/tree/master/results/mol_results" target="_self">log file of their training</a> (they had the good idea to make it public too). Their discriminator always highly penalizes the generator. They have a <strong>perfect discriminator problem, </strong>which essentially nullifies any practical benefit of using GAN.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">To excuse them, they might have inherited this perfect discriminator problem from the <a href="https://arxiv.org/abs/1609.05473" target="_self">SeqGAN paper</a>, on which ORGAN is built. We can’t know for sure, because contrary to the ORGAN team, the SeqGAN team didn’t make public their training log file, and nobody bothered to reproduce their experiments.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A more technical discussion is available in <a href="https://goo.gl/wsMKBd" target="_self">my paper</a>, pages 5–6. I tweeted my paper to Alan Aspuru-Guzik, the ORGAN team leader. He answered:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:80%;"><iframe  scrolling="auto" width="500.0" height="185.0" frameborder="0" src="https://cdn.embedly.com/widgets/media.html?type=text%2Fhtml&key=a19fcc184b9711e1b4764040d3dc5c07&schema=twitter&url=https%3A//twitter.com/a_aspuru_guzik/status/903074999103258626&image=https%3A//i.embed.ly/1/image%3Furl%3Dhttps%253A%252F%252Fpbs.twimg.com%252Fprofile_images%252F406908595%252FAlan_Aspuru-Guzik-Harvard-2_400x400.jpg%26key%3Da19fcc184b9711e1b4764040d3dc5c07" allowfullscreen=""></iframe></div><br><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I am still waiting for an adequate response.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:44%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 340px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*hvMy729zQZr91ZOSRb7H9Q.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*hvMy729zQZr91ZOSRb7H9Q.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*hvMy729zQZr91ZOSRb7H9Q.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*hvMy729zQZr91ZOSRb7H9Q.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*hvMy729zQZr91ZOSRb7H9Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*hvMy729zQZr91ZOSRb7H9Q.png 1100w, https://miro.medium.com/v2/resize:fit:680/format:webp/1*hvMy729zQZr91ZOSRb7H9Q.png 680w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 340px" srcset="https://miro.medium.com/v2/resize:fit:640/1*hvMy729zQZr91ZOSRb7H9Q.png 640w, https://miro.medium.com/v2/resize:fit:720/1*hvMy729zQZr91ZOSRb7H9Q.png 720w, https://miro.medium.com/v2/resize:fit:750/1*hvMy729zQZr91ZOSRb7H9Q.png 750w, https://miro.medium.com/v2/resize:fit:786/1*hvMy729zQZr91ZOSRb7H9Q.png 786w, https://miro.medium.com/v2/resize:fit:828/1*hvMy729zQZr91ZOSRb7H9Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*hvMy729zQZr91ZOSRb7H9Q.png 1100w, https://miro.medium.com/v2/resize:fit:680/1*hvMy729zQZr91ZOSRb7H9Q.png 680w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/340/1*hvMy729zQZr91ZOSRb7H9Q.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Stanford has a big team dedicated to AI and deep learning for chemistry. The team leader is <a style="color:green" href="https://medium.com/u/deb3786a5151?source=post_page-----315d69a7f863--------------------------------" target="_self">Vijay Pande</a>, who is also a startup investor at Andreessen Horowitz, co-managing their $450 Million bio fund. Their flagship project is <a href="http://moleculenet.ai/" target="_self">MoleculeNet</a>, a ‘benchmark specially designed for testing machine learning methods of molecular properties’. It has the appearance of seriousness, with lots of chemical compounds, lots of graphics, and <a href="http://moleculenet.ai/models" target="_self">lots of deep learning models</a>. In particular, a large place is devoted to graph-CNN and other chemistry-specific neural networks, developed by this Stanford team.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*5dcir2XNGxP0Jdn829ruwA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*5dcir2XNGxP0Jdn829ruwA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*5dcir2XNGxP0Jdn829ruwA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*5dcir2XNGxP0Jdn829ruwA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*5dcir2XNGxP0Jdn829ruwA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*5dcir2XNGxP0Jdn829ruwA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*5dcir2XNGxP0Jdn829ruwA.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*5dcir2XNGxP0Jdn829ruwA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*5dcir2XNGxP0Jdn829ruwA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*5dcir2XNGxP0Jdn829ruwA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*5dcir2XNGxP0Jdn829ruwA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*5dcir2XNGxP0Jdn829ruwA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*5dcir2XNGxP0Jdn829ruwA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*5dcir2XNGxP0Jdn829ruwA.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*5dcir2XNGxP0Jdn829ruwA.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">However, there’s an elephant in this room too: the Pande team did not bother to plug their data into a <strong>character-level Convolutional Neural Network</strong>. <a href="https://arxiv.org/abs/1502.01710" target="_self">Char-CNN</a> is routinely used in AI for text processing since 2015, and it is much simpler than their graph-CNN. To use char-CNN, it is sufficient to plug the <a href="https://en.wikipedia.org/wiki/Simplified_molecular-input_line-entry_system" target="_self">SMILES</a> strings.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Why did they avoid such an easy task? Page 17 of <a href="https://arxiv.org/abs/1703.00564" target="_self">their paper</a>, we can read:</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">“Recent work has demonstrated the ability to learn useful<br></br>representations from SMILES strings using<strong> more sophisticated methods</strong>,<br></br>so it may be feasible to use SMILES strings for further learning tasks<br></br>in the near future.”</p></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I honestly doubt that char-CNN is too sophisticated for this Stanford team. They even use char-CNN in <a href="https://arxiv.org/abs/1706.01643" target="_self">another paper</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Update: they added char-CNN (a.k.a textCNN) to the </em><a href="http://moleculenet.ai/latest-results" target="_self">benchmark</a><em>.</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><mark>A more plausible, and embarrassing explanation is that they were </mark><mark>scared that char-CNN would be better</mark><mark>. This would mean that their beloved model, graph-CNN, would be beaten at their own MoleculeNet benchmark. This wouldn’t fit their agenda.</mark></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Which agenda? MoleculeNet is closely related with the <a href="https://deepchem.io/" target="_self">DeepChem</a> library, which implements MoleculeNet models. DeepChem is open-source and Stanford-led. If char-CNN is better than graph-CNN, then practitioners don’t really need DeepChem, because for a state-of-the-art model, they can simply use plain TensorFlow or PyTorch. We are in 2018, and <strong>adoption of open-source frameworks is a strategic asset.</strong> For example, by open-sourcing Android, Google dominated the mobile OS market. In AI software, Google is leveraging its open-source library TensorFlow to expand its <a href="https://www.forbes.com/sites/janakirammsv/2017/07/09/how-google-turned-open-source-into-a-key-differentiator-for-its-cloud-platform/#4a70500646fb" target="_self">Google Cloud Platform</a>. Likewise, DeepChem might be looking for a domination in the AI for drug discovery niche, and that may be why MoleculeNet ‘omitted’ char-CNN. One concrete possibility is that Andreessen Horowitz could quietly invest in a Cloud drug discovery platform powered by DeepChem.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This conjecture is reinforced by my personal experience with DeepChem. I naively tried to use DeepChem in my project, until I realized that I couldn’t mix DeepChem models and non-DeepChem models. That would be useful for adversarial training, with a DeepChem discriminator and a non-DeepChem generator. On the contrary, I got completely locked-in DeepChem code. I didn’t expect something so vicious. In order to escape from this trap, and to make DeepChem truly open, I had to dig into complex code (my unlocked fork of DeepChem is <a href="https://github.com/mostafachatillon/deepchem" target="_self">here</a>). It will be much more difficult to do that for a more mature project. So my impression is that with this strategy of <a href="https://en.wikipedia.org/wiki/Vendor_lock-in" target="_self">technology lock-in</a><strong>, </strong>DeepChem wants to <strong>eat the world</strong> of AI for chemistry. This would not surprise me from an <a href="https://a16z.com/2015/11/18/bio-fund/" target="_self">investor partnering</a> with <a style="color:green" href="https://medium.com/u/fa65e64cf273?source=post_page-----315d69a7f863--------------------------------" target="_self">Marc Andreessen</a> .</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*whiRX1o_7J3jkxB5Ljskow.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*whiRX1o_7J3jkxB5Ljskow.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*whiRX1o_7J3jkxB5Ljskow.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*whiRX1o_7J3jkxB5Ljskow.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*whiRX1o_7J3jkxB5Ljskow.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*whiRX1o_7J3jkxB5Ljskow.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*whiRX1o_7J3jkxB5Ljskow.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*whiRX1o_7J3jkxB5Ljskow.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*whiRX1o_7J3jkxB5Ljskow.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*whiRX1o_7J3jkxB5Ljskow.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*whiRX1o_7J3jkxB5Ljskow.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*whiRX1o_7J3jkxB5Ljskow.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*whiRX1o_7J3jkxB5Ljskow.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*whiRX1o_7J3jkxB5Ljskow.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*whiRX1o_7J3jkxB5Ljskow.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">DeepChem and Andreessen Horowitz want to eat the world of AI for chemistry, by using technology lock-in.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">While MoleculeNet team members avoided to benchmark char-CNN, they still found time to design fancy landing pages for MoleculeNet and DeepChem, which suggests that their <strong>priority is PR fluff,</strong> and not solid science. It’s a strategy typical in the Silicon Valley, where startups design <strong>mock products</strong> to attract traffic, and then rely on their community to build the real thing.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:62%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 468px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:936/format:webp/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 936w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 468px" srcset="https://miro.medium.com/v2/resize:fit:640/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:936/1*InyYAOTBkhHBC8DK-0MaKg.jpeg 936w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/468/1*InyYAOTBkhHBC8DK-0MaKg.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">The Silicon Valley knows that designing facades can be more useful than building houses.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:24%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 200px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 1100w, https://miro.medium.com/v2/resize:fit:400/format:webp/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 200px" srcset="https://miro.medium.com/v2/resize:fit:640/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 1100w, https://miro.medium.com/v2/resize:fit:400/1*qLMEAZ-MhhkiOGpIS6qRJQ.png 400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/200/1*qLMEAZ-MhhkiOGpIS6qRJQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Insilico Medicine is a pioneer in generative models, among AI startups. In <a href="http://pubs.acs.org/doi/abs/10.1021/acs.molpharmaceut.7b00346" target="_self">this paper</a> (the paywall can be hacked using <a href="https://en.wikipedia.org/wiki/Sci-Hub" target="_self">Sci-Hub</a>), <a style="color:green" href="https://medium.com/u/65c86118948c?source=post_page-----315d69a7f863--------------------------------" target="_self">Alex Zhavoronkov</a> and his team proposed ‘<strong>DruGAN</strong>, an <strong>advanced</strong> generative adversarial autoencoder model’. I keep wondering what is so advanced about this model.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">It is definitely<strong> not advanced</strong> with respect to the demands of drug discovery: it suffers from the same flaws as the other generative models, which can lead to disappointments down the road.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">It’s not advanced either with respect to the previous papers in the literature, which use more sophisticated tools. They make allusions to them pages 9-10 (without citing them):</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">This study uses the MACCS molecular fingerprints that are not ideal representation of molecular structure. Direct SMILES [<a href="https://arxiv.org/abs/1610.02415" target="_self">here</a>], InChI, molecular graphs [<a href="https://arxiv.org/abs/1603.00856" target="_self">here</a>] and<br></br>other more chemically- and biologically-relevant representations of the molecular<br></br>structures may serve as better types of training.</p></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">It is not even advanced with respect to their own Variational Auto-Encoder (VAE) used for benchmarking. In the paper, they claim that DruGAN is better than VAE, but on <a href="https://github.com/greenelab/deep-review/issues/583#issuecomment-316380338" target="_self">Github</a>, one DruGAN author acknowledges the contrary:</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">Actually, we didn’t tune VAE network as much as AAE [DruGAN], so it isn’t very fair comparison. I mean that one can introduce upgrades for VAE and outperform our AAE.</p></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So I am left thinking that DruGAN is only advanced with respect to their previous paper, published 8 months earlier. All over the paper, they keep mentioning the improvements they made to their previous work. So maybe ‘advanced’ was just a term for self-congratulation.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Conclusion</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In conclusion, many researchers in AI for drug discovery are overhyping their results. To navigate in the middle of this <strong>AI bubble</strong>, it is important to hire strong <strong>counter-expertise</strong> services. Startcrowd provides such services, they can be <a href="mailto:mostaphabenhenda@gmail.com" target="_self">ordered here</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Edit: Lot of discussion on <a href="https://news.ycombinator.com/item?id=16079735" target="_self">Hacker News</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Edit: Discussion on Reddit <a href="https://www.reddit.com/r/chemistry/comments/7nm6ih/ai_in_drug_discovery_is_overhyped_examples_from/" target="_self">Chemistry</a> and <a href="https://www.reddit.com/r/bioinformatics/comments/7oere3/opinion_ai_in_drug_discovery_is_overhyped/" target="_self">Bioinformatics</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Edit: The DeepChem team (Stanford) disagrees on <a href="https://www.facebook.com/groups/1362916627160962/permalink/1531967526922537/" target="_self">Facebook</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Edit: Commentary by <a style="color:green" href="https://medium.com/u/274f95ddb667?source=post_page-----315d69a7f863--------------------------------" target="_self">Derek Lowe</a> on his blog:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="http://blogs.sciencemag.org/pipeline/archives/2018/01/10/objections-to-some-drug-discovery-ai"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Objections to (Some) Drug Discovery AI</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Here's a piece to start some arguing: "AI in Drug Discovery is Overhyped", by Mostapha Benhenda. I realize that a lot…</h3><p>blogs.sciencemag.org</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Definitely check the comments from <a href="http://blogs.sciencemag.org/pipeline/archives/2018/01/10/objections-to-some-drug-discovery-ai#comment-288470" target="_self">Alan Aspuru-Guzik</a> (Harvard), <a href="http://blogs.sciencemag.org/pipeline/archives/2018/01/10/objections-to-some-drug-discovery-ai#comment-288468" target="_self">Vijay Pande</a> (Stanford) and <a href="http://blogs.sciencemag.org/pipeline/archives/2018/01/10/objections-to-some-drug-discovery-ai#comment-288522" target="_self">Marwin Segler</a> (AstraZeneca co-author).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">My replies are <a href="https://medium.com/@mostafab/response-to-professor-alan-aspuru-guzik-comment-here-f31f7353b5be" target="_self">here for Alan</a>, <a href="https://medium.com/@mostafab/response-to-vijay-pande-comment-here-da106bc53119" target="_self">here for Vijay</a>, and <a href="https://medium.com/@mostafab/response-to-marwin-segler-astrazeneca-collaboration-18d89844cb3d" target="_self">here for Marwin</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Edit: Commentary in Japanese by <a href="http://computational-chemistry.com/blog/author/zero/" target="_self">管理人</a>:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="http://computational-chemistry.com/blog/2018/01/12/ai-drug-discovery/"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">AI を用いた創薬研究</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">近年の人工知能ブームにより、様々な分野で AI の活用が始まっています。 有名なところでは、将棋、囲碁、画像認識などが挙げられます。 また、不完全情報（運に左右される）ゲームであるポーカーでも人工知能が人間を圧倒しつつあるようです（…</h3><p>computational-chemistry.com</p></a></div></div></div></div></section><br><?php include_once 'Elemental/footer.php'; ?>