<!DOCTYPE html>
                <html>
                <head>
                    <title>CEO cướp nhà băng nhắn nhủ đôi điều đến các bạn trẻ khởi nghiệp</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://thanhcs94.medium.com/l%E1%BB%9Di-nh%E1%BA%AFn-nh%E1%BB%A7-c%E1%BB%A7a-ceo-gnn-express-2-n%C4%83m-tr%C6%B0%E1%BB%9Bc-khi-c%C6%B0%E1%BB%9Bp-ng%C3%A2n-h%C3%A0ng-e058d85b2c1d"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/?source=post_page-----e058d85b2c1d--------------------------------">Author : Thanh Nguyen</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>CEO cướp nhà băng nhắn nhủ đôi điều đến các bạn trẻ khởi nghiệp</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Lưu lại một số ý chính của anh CEO GNN, một số điểm cần lưu ý.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*uYy7oDQdltAAgFmS.jpg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*uYy7oDQdltAAgFmS.jpg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*uYy7oDQdltAAgFmS.jpg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*uYy7oDQdltAAgFmS.jpg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*uYy7oDQdltAAgFmS.jpg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*uYy7oDQdltAAgFmS.jpg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*uYy7oDQdltAAgFmS.jpg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*uYy7oDQdltAAgFmS.jpg 640w, https://miro.medium.com/v2/resize:fit:720/0*uYy7oDQdltAAgFmS.jpg 720w, https://miro.medium.com/v2/resize:fit:750/0*uYy7oDQdltAAgFmS.jpg 750w, https://miro.medium.com/v2/resize:fit:786/0*uYy7oDQdltAAgFmS.jpg 786w, https://miro.medium.com/v2/resize:fit:828/0*uYy7oDQdltAAgFmS.jpg 828w, https://miro.medium.com/v2/resize:fit:1100/0*uYy7oDQdltAAgFmS.jpg 1100w, https://miro.medium.com/v2/resize:fit:1400/0*uYy7oDQdltAAgFmS.jpg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*uYy7oDQdltAAgFmS.jpg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">hình ảnh mang tính chất minh hoạ, gợi nhớ đại ý của bài viết</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4"><em>“Nói thật là mức giá bên em đã hạ hết mức rồi, cũng không thể cạnh tranh được với việc bù lỗ. Em thú thực chắc là em không dám làm ngành chuyển phát nhanh nữa. Hạ giá, chấp nhận lỗ vẫn không thể cạnh tranh…”</em></p></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Cạnh tranh về giá trong khi vốn mình mỏng? giá thì chắc chắn không cạnh tranh lại rồi, có thể cạnh tranh các yếu tố khác không? hay có thể tránh cạnh tranh, đánh vào tập khách hàng ngách nào đó, xây dựng thật tốt nền tảng, đánh trận lâu dài?</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Nhìn thẳng vào sự sụp đổ của GNN Express, Ngọc cho rằng bản thân mình có 2 lỗi:</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">- Startup quá sớm với một số vốn cực nhỏ, giống như xây một lâu đài trên cát</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">- Năng lực quản lý yếu</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4"><em>“Tất cả thành viên bên em quản lý đến bây giờ, từ kế toán chính đến bản thân em cũng không phải những người được đào tạo một cách bài bản. Không một ai được học quản trị. Tất cả quản lý đều dựa trên “kinh nghiệm chủ nghĩa”, làm đến đâu tính đến đó”</em><em>“Em có lời khuyên đến các bạn trẻ khi khởi nghiệp cần trang bị đầy đủ kiến thức, cần trang bị rất nhiều. Nhiệt huyết không ăn thua, tiền tài không ăn thua. Em rất tâm huyết gửi đến các bạn trẻ: Những bạn mong muốn khởi nghiệp, nên cân nhắc chứ đừng tạo thành trào lưu. Hồi em tham gia MFO, đi đâu cũng thấy PR, sau đó một thời gian đi đâu cũng nói M&A (mua bán sáp nhập), rồi bây giờ đi đâu cũng thấy startup. Mọi người có hiểu startup là cái gì không mà mọi người định startup</em>”</p></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Nguồn: <a href="https://cafebiz.vn/loi-nhan-nhu-cua-ceo-gnn-express-2-nam-truoc-khi-cuop-ngan-hang-startup-qua-nhieu-thi-startup-se-chet-20200730120810283.chn" target="_self">cafebiz.vn</a></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>