<!DOCTYPE html>
                <html>
                <head>
                    <title>ChemGAN challenge for drug discovery: can AI reproduce natural chemical diversity?</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/the-ai-lab/chemgan-challenge-for-drug-discovery-can-ai-reproduce-natural-chemical-diversity-8f1f2528ee22"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@mostafab?source=post_page-----8f1f2528ee22--------------------------------">Author : Mostapha Benhenda</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>ChemGAN challenge for drug discovery: can AI reproduce natural chemical diversity?</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Early-stage drug discovery requires a constant supply of new molecules, to be fed into <a href="https://en.wikipedia.org/wiki/High-throughput_screening" target="_self">High Throughput Screening</a> machines. To increase this supply, data scientists are preparing AI systems that can generate virtual molecules on-demand. These <em>in silico</em> simulations should generate drug compounds with a higher hit rate in high throughput screening, and a lower attrition rate later in the drug discovery pipeline.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In this post, I briefly explain how some of these systems work, and also how they don’t work. I present 2 challenges they are facing:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ul><li class="ff3" style="font-size:22px;">multitasking between different objectives</li><li class="ff3" style="font-size:22px;">generating chemically diverse molecules.</li></ul></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:64%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 480px" srcset="https://miro.medium.com/v2/resize:fit:640/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 1100w, https://miro.medium.com/v2/resize:fit:960/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 960w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 480px" srcset="https://miro.medium.com/v2/resize:fit:640/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 1100w, https://miro.medium.com/v2/resize:fit:960/1*-5Gn9M8aIjd3Lh8-J6thaA.gif 960w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/480/1*-5Gn9M8aIjd3Lh8-J6thaA.gif"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;"><a href="https://www.youtube.com/watch?v=xakRli5vxd4" target="_self">High Throughput Screening</a></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">How some generative systems work</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">These systems have two types of components. The first type is <strong>generative</strong>: one model randomly generates virtual molecules, i.e. chemical formulas like this:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:57%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 429px" srcset="https://miro.medium.com/v2/resize:fit:640/1*mtJLUPvPTiA8vMBiEjt9fw.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*mtJLUPvPTiA8vMBiEjt9fw.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*mtJLUPvPTiA8vMBiEjt9fw.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*mtJLUPvPTiA8vMBiEjt9fw.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*mtJLUPvPTiA8vMBiEjt9fw.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*mtJLUPvPTiA8vMBiEjt9fw.gif 1100w, https://miro.medium.com/v2/resize:fit:858/1*mtJLUPvPTiA8vMBiEjt9fw.gif 858w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 429px" srcset="https://miro.medium.com/v2/resize:fit:640/1*mtJLUPvPTiA8vMBiEjt9fw.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*mtJLUPvPTiA8vMBiEjt9fw.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*mtJLUPvPTiA8vMBiEjt9fw.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*mtJLUPvPTiA8vMBiEjt9fw.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*mtJLUPvPTiA8vMBiEjt9fw.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*mtJLUPvPTiA8vMBiEjt9fw.gif 1100w, https://miro.medium.com/v2/resize:fit:858/1*mtJLUPvPTiA8vMBiEjt9fw.gif 858w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/429/1*mtJLUPvPTiA8vMBiEjt9fw.gif"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The second type of components is <strong>predictive</strong>: other models compute chemical properties of generated virtual molecules, properties they would have if they were produced for real. Example of such properties include: activity, toxicity, and solubility in water. In practice, we want to combine different properties into one molecule, and therefore, we have one generator and many predictors, one for each desired property.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Taken together, this generator and these predictors form a <strong>reinforcement learning </strong>system. Predictors provide the <strong>environment</strong>. They <strong>reward</strong> the generator, which acts as an <strong>agent</strong>.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:46%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 350px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*7Ae4mf9gVvpuMgenwtf8wA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*7Ae4mf9gVvpuMgenwtf8wA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*7Ae4mf9gVvpuMgenwtf8wA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*7Ae4mf9gVvpuMgenwtf8wA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*7Ae4mf9gVvpuMgenwtf8wA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*7Ae4mf9gVvpuMgenwtf8wA.png 1100w, https://miro.medium.com/v2/resize:fit:700/format:webp/1*7Ae4mf9gVvpuMgenwtf8wA.png 700w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 350px" srcset="https://miro.medium.com/v2/resize:fit:640/1*7Ae4mf9gVvpuMgenwtf8wA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*7Ae4mf9gVvpuMgenwtf8wA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*7Ae4mf9gVvpuMgenwtf8wA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*7Ae4mf9gVvpuMgenwtf8wA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*7Ae4mf9gVvpuMgenwtf8wA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*7Ae4mf9gVvpuMgenwtf8wA.png 1100w, https://miro.medium.com/v2/resize:fit:700/1*7Ae4mf9gVvpuMgenwtf8wA.png 700w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/350/1*7Ae4mf9gVvpuMgenwtf8wA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">At each iteration, the generator updates its probability distribution on chemical formulas, in a way that tries to improve virtual molecules. The hope is that after enough iterations, virtual molecules will combine all the desired properties together.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Challenge 1: juggling with a multitude of objectives</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">However, in practice, it’s hard to find a reward function that brings good incentives to the generator. Reinforcement learning agents are pretty lazy: they quickly find out the easiest property, focus on it, and just ignore others. On the other hand, if they are forced to consider all the different objectives together, then they just get confused by this multitasking. Multi-objective reinforcement learning is a <a href="https://arxiv.org/abs/1402.0590" target="_self">complex topic</a> that is barely scratched by current systems.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:67%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Wep4GsSxXmvbToTx60c5ug.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*Wep4GsSxXmvbToTx60c5ug.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*Wep4GsSxXmvbToTx60c5ug.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*Wep4GsSxXmvbToTx60c5ug.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*Wep4GsSxXmvbToTx60c5ug.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*Wep4GsSxXmvbToTx60c5ug.gif 1100w, https://miro.medium.com/v2/resize:fit:1000/1*Wep4GsSxXmvbToTx60c5ug.gif 1000w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Wep4GsSxXmvbToTx60c5ug.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*Wep4GsSxXmvbToTx60c5ug.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*Wep4GsSxXmvbToTx60c5ug.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*Wep4GsSxXmvbToTx60c5ug.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*Wep4GsSxXmvbToTx60c5ug.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*Wep4GsSxXmvbToTx60c5ug.gif 1100w, https://miro.medium.com/v2/resize:fit:1000/1*Wep4GsSxXmvbToTx60c5ug.gif 1000w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/500/1*Wep4GsSxXmvbToTx60c5ug.gif"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This is a big problem for drug discovery, because a molecule must satisfy 100% of a large number of properties. That’s the only way to get through clinical trials, and meet FDA standards. For example, the drug must be active on the disease, minimize toxicity, side-effects, and so on.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*WgwQjWhzS2wC82x2QbQrDw.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*WgwQjWhzS2wC82x2QbQrDw.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">To receive FDA approval, a drug must satisfy a multitude of objectives</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Challenge 2: reproducing natural chemical diversity</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Another challenge is that currently, generated molecules lack the chemical diversity found in nature. They look simplistic and repetitive. They seem more like artificially flavored candies:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">COCCNC(=O)CCc1ccccc1<br></br>CCOC(=O)CCCCc1ccccc1CCN(C)CCCCc1ccccc1C<br></br>COCCCC(=O)CC(C)CCCCc1ccccc1C<br></br>CCCC(=O)CSCCC(=O)CCCCC(=O)OC<br></br>CCC(=O)COCCCCCCC(=O)CCCSC</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:81%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 600px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*ogkFUc-EvAuwUuFfl6RoAQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*ogkFUc-EvAuwUuFfl6RoAQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*ogkFUc-EvAuwUuFfl6RoAQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*ogkFUc-EvAuwUuFfl6RoAQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*ogkFUc-EvAuwUuFfl6RoAQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ogkFUc-EvAuwUuFfl6RoAQ.png 1100w, https://miro.medium.com/v2/resize:fit:1200/format:webp/1*ogkFUc-EvAuwUuFfl6RoAQ.png 1200w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 600px" srcset="https://miro.medium.com/v2/resize:fit:640/1*ogkFUc-EvAuwUuFfl6RoAQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*ogkFUc-EvAuwUuFfl6RoAQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*ogkFUc-EvAuwUuFfl6RoAQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*ogkFUc-EvAuwUuFfl6RoAQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*ogkFUc-EvAuwUuFfl6RoAQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*ogkFUc-EvAuwUuFfl6RoAQ.png 1100w, https://miro.medium.com/v2/resize:fit:1200/1*ogkFUc-EvAuwUuFfl6RoAQ.png 1200w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/600/1*ogkFUc-EvAuwUuFfl6RoAQ.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Artificial strawberries: simplistic and repetitive</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">On the other hand, natural molecules look more like organic fruits, flourishing and diverse:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">CS(=O)(=O)CCCOc1ccccc1Br<br></br>CN(Cc1ccccc1F)C[C@@H]1C(=O)C(C)©OC1(C)C<br></br>CC[C@@H]1CN(Cc2nc3ccccc3n2CC)C[C@H]©O1<br></br>CSCC[C@H](NC(=O)c1ccccc1Cl)C(=O)Nc1ccc(O)c(Cl)c1<br></br>O=C(Nc1ccccc1)N1CCC[C@H]1c1nc2ccccc2s1</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*A2JyuQNSe0i6bwX--DOEbg.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*A2JyuQNSe0i6bwX--DOEbg.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Organic strawberries: flourishing and diverse</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A team at Harvard is giving a shot at this problem. They, quite ironically, called their model <a href="https://chemrxiv.org/articles/ORGANIC_1_pdf/5309668/3" target="_self">ORGANIC</a> (Objective-Reinforced Generative Adversarial Network for Inverse-design Chemistry), maybe to sound as if it mimicks nature.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A (modification of) their approach is the following: in reinforcement learning, instead of using predictors to reward the generator, the idea is to use <strong>discriminators</strong>, which are slightly different. A discriminator takes as input two classes of data: generated molecules on one side, and the natural molecules having the desired property on the other side. It rewards the generator for the perceived similarity between generated and natural molecules.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Rr6yQwfKDeKlS4pUOqrRbA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Rr6yQwfKDeKlS4pUOqrRbA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Rr6yQwfKDeKlS4pUOqrRbA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Rr6yQwfKDeKlS4pUOqrRbA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Rr6yQwfKDeKlS4pUOqrRbA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Rr6yQwfKDeKlS4pUOqrRbA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Rr6yQwfKDeKlS4pUOqrRbA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Rr6yQwfKDeKlS4pUOqrRbA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Rr6yQwfKDeKlS4pUOqrRbA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Rr6yQwfKDeKlS4pUOqrRbA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Rr6yQwfKDeKlS4pUOqrRbA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Rr6yQwfKDeKlS4pUOqrRbA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Rr6yQwfKDeKlS4pUOqrRbA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*Rr6yQwfKDeKlS4pUOqrRbA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*Rr6yQwfKDeKlS4pUOqrRbA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Discriminators and the generator are trained alternatively. They learn from each other, and there should be a balance between them. This training method is often called <strong>adversarial training</strong>, although here, the relationship between discriminators and the generator is more cooperative than conflictual. Adversarial training is a method <a href="http://people.idsia.ch/~juergen/edgedetect/node2.html" target="_self">dating back to the 1990’s</a>, and it has recently been revived with <a href="https://en.wikipedia.org/wiki/Generative_adversarial_networks" target="_self">Generative Adversarial Networks</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">However, in practice, it does not work very well: I computed the chemical variance of generated molecules in <a href="https://arxiv.org/abs/1708.08227" target="_self">my paper</a>, and results are awful. Generated molecules still lag far behind natural molecules.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Besides the multi-objective RL problem that I mentioned (challenge 1), what happens is that the generator can’t follow the discriminator for very long. ORGANIC has a <a href="https://arxiv.org/abs/1701.04862" target="_self">perfect discriminator problem</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">There are many possible ways to solve this issue: taking a larger generator, a larger training set, a <a href="http://pubs.acs.org/doi/abs/10.1021/acscentsci.6b00367" target="_self">low-data discriminator</a>, a more modern loss function (like <a href="https://arxiv.org/abs/1705.10743" target="_self">CramerGAN</a>) and using <a href="https://arxiv.org/abs/1606.03498" target="_self">one-sided label smoothing</a>. So that’s not the end of the story.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Conclusion</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you are interested in those challenges as a researcher (amateur or pro), or as a sponsor, you can learn more in <a href="https://arxiv.org/abs/1708.08227" target="_self">my paper</a>, and discuss on the <a href="https://gitter.im/Startcrowd/drugdiscovery" target="_self">Startcrowd chat</a>. If you use my paper in your own academic papers, <a href="https://www.princeton.edu/pr/pub/integrity/pages/sources/" target="_self">don’t forget to cite it</a>. For example:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Benhenda, M. 2017. ChemGAN challenge for drug discovery: can AI reproduce natural chemical diversity? <em>arXiv preprint </em><a href="https://arxiv.org/abs/1708.08227" target="_self">arXiv:1708.08227.</a></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>