<!DOCTYPE html>
                <html>
                <head>
                    <title>Dear CNN — This Sh*t is Unacceptable</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://madesruis.medium.com/dear-cnn-this-sh-t-is-unacceptable-a00904b277e"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/?source=post_page-----a00904b277e--------------------------------">Author : Mickey Desruisseaux</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Dear CNN — This Sh*t is Unacceptable</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5 text-muted">In a world where “woke” is effectively another racial slur, corporate adoption of AAVE phrasings is beyond insulting.</h4></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*x9SVvlpP7wRz7YiU.jpg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*x9SVvlpP7wRz7YiU.jpg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*x9SVvlpP7wRz7YiU.jpg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*x9SVvlpP7wRz7YiU.jpg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*x9SVvlpP7wRz7YiU.jpg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*x9SVvlpP7wRz7YiU.jpg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*x9SVvlpP7wRz7YiU.jpg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*x9SVvlpP7wRz7YiU.jpg 640w, https://miro.medium.com/v2/resize:fit:720/0*x9SVvlpP7wRz7YiU.jpg 720w, https://miro.medium.com/v2/resize:fit:750/0*x9SVvlpP7wRz7YiU.jpg 750w, https://miro.medium.com/v2/resize:fit:786/0*x9SVvlpP7wRz7YiU.jpg 786w, https://miro.medium.com/v2/resize:fit:828/0*x9SVvlpP7wRz7YiU.jpg 828w, https://miro.medium.com/v2/resize:fit:1100/0*x9SVvlpP7wRz7YiU.jpg 1100w, https://miro.medium.com/v2/resize:fit:1400/0*x9SVvlpP7wRz7YiU.jpg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*x9SVvlpP7wRz7YiU.jpg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Hey there, CNN.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I know you’ve had a rough go of it the last few years. To half the country, your name is synonymous with “fake news,” and everything you say is not to be taken with a grain of salt so much as a pillar of it. To a good chunk of the other half, you embody everything that is wrong with corporate journalism in the institutional pursuit of carving out a neutral zone between the FOXes and MSNBCs of the world. You were a particular punching bag of the former president, and while I’ve not entirely forgiven you for the <a href="https://www.seattletimes.com/opinion/cnn-and-jeff-zucker-helped-give-us-trump/" target="_self">role</a> you <a href="https://www.youtube.com/watch?v=5O-87CAAImk" target="_self">played</a> in <a href="https://www.youtube.com/watch?v=OGFff6N0Bsg" target="_self">empowering</a> him in the first place, I can only imagine the toll it’s taken in your offices and how bizarre the comedown must be.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I know, I know. There’s no ethical blah blah blah under bleh bleh bleh. But, look, I don’t need you to be ProPublica out here. And I think that for all the holograms and the chyrons and the flashy effects, you’ve still got good people trying to do good work out there, in the name of a 1st Amendment freedom every bit as important as assembly, religion, or speech.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">(You also let Rick Santorum <a href="https://www.avclub.com/cnn-finally-gets-around-to-firing-rick-santorum-1846948211" target="_self">hang around for a minute</a>, but hey. Let he who has not sinned, amirite?)</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So what I’m about to say doesn’t come from a place of love, <em>per se</em>, but more of constructive criticism. And I hope you’ll take it to heart.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Um… this shit?</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*sTb23CBKTq2LLKephPLIvA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*sTb23CBKTq2LLKephPLIvA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*sTb23CBKTq2LLKephPLIvA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*sTb23CBKTq2LLKephPLIvA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*sTb23CBKTq2LLKephPLIvA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sTb23CBKTq2LLKephPLIvA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*sTb23CBKTq2LLKephPLIvA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*sTb23CBKTq2LLKephPLIvA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*sTb23CBKTq2LLKephPLIvA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*sTb23CBKTq2LLKephPLIvA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*sTb23CBKTq2LLKephPLIvA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*sTb23CBKTq2LLKephPLIvA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*sTb23CBKTq2LLKephPLIvA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*sTb23CBKTq2LLKephPLIvA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*sTb23CBKTq2LLKephPLIvA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This shit right here?</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:49%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 371px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:742/format:webp/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 742w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 371px" srcset="https://miro.medium.com/v2/resize:fit:640/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:742/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg 742w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/371/1*r7dWDQBz-WBonHMK1sk6Mg.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">…don’t do this. I’m willing to give you all the benefit of the doubt that this was a typo, but if it wasn’t?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Then please, for the love of God, <em>do not do this.</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">There’s a very specific subset of the population that talks this way — or to be fair, a very specific subset of the population that talked that way <em>first</em>. And according to your viewership statistics, <a href="https://letter.ly/cable-news-viewership-statistics/" target="_self">that subset only constitutes a fifth of your viewership</a>, at most.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">“This summer about to be lit?”</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Black people talk that way.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Not all black people talk that way, of course. And not only black people talk that way, of courser. And the etymology of the word “lit,” beyond its standard usage as an offshoot of “light,” <a href="https://genius.com/a/what-does-lit-mean" target="_self">reveals a history that dates back decades and crosses all manner of cultural and denotational lines</a>, of coursest. But the word’s resurgence in the past few years, especially in the context in which you used it right there? That’s black shit, stemming from the predominantly black world of hip-hop. And the invisible “is” in that sentence, which would be virtually reflexive to a native speaker of AAVE? That’s very black shit indeed.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Honestly, typo or not, I’d be much more willing to let it slide if there wasn’t an entire political movement that’s currently latched onto another loanword from AAVE. “Woke” has gone from inside baseball among the hallowed halls of Black Twitter to a reflexive conservative catchall to lambast anything that breathes the wrong way in their direction — and a good chunk of the time, that “anything” has more than a couple shades of black in it. Woke brands, woke culture, woke mobs, woke ideologies, <a href="https://www.huffpost.com/entry/tom-cotton-washington-monument_n_5ee3170ac5b67fa8b892423d" target="_self">woke obelisks</a>, for George’s sake. For all intents and purposes, <a href="https://melmagazine.com/en-us/story/woke-with-a-hard-r-how-the-right-created-a-new-dogwhistle" target="_self">woke has essentially become another slur</a>, and the wink-wink nudge-nudge nature of it has long worn thin.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><mark>At this point, I’d rather that they just went back to “nigger.” At least it’s more honest.</mark></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">And hey, I get it. It’s a puff piece meant to give people some light after an incredibly dark year heading into the Memorial Day weekend. You don’t need some embittered internet lake goblin (we do not abide trolls here) with a keyboard and a lukewarm cup of tea to dump all over your parade. After fifteen months of isolation, I’m as ready for my post-COVID summer as anyone.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>(looks at self in mirror)</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Okay, maybe not.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Point being, after everything that’s happened in the past five or so years, and the not-insignificant role that the editorial decisions at CNN played in contributing to it, sprinkling some AAVE into your headlines isn’t cute. At all. It’s another step in a process that has played out throughout American history, as the broader society discovers something they like about black culture, adopts it as their own, and then whips back around and uses it as another cudgel to browbeat us for all of our supposed inferiorities. And after the Big Year in which America was finally supposed to have its grand racial reckoning that ultimately amounted to something north of diddly and south of squat, it’s <em>really</em> annoying.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So unless this is a signal fire that we can expect some serious changes in how the flagship of cable news is run, then please. There are plenty of OED-approved synonyms for “lit” that you can use, and Queen’s English approved sentence constructions in which you can use them, replete with the word “is.”</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Stick to the rivers and the lakes that you’re used to, and leave the lit-mus tests to us.</p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>