<!DOCTYPE html>
                <html>
                <head>
                    <title>Deep Learning is Revolutionary</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/transmission-newsletter/deep-learning-is-revolutionary-d0f3667bafa0"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@olivercameron?source=post_page-----d0f3667bafa0--------------------------------">Author : Oliver Cameron</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Deep Learning is Revolutionary</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5 text-muted">10 reasons why deep learning is living up to the hype</h4></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:69%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 512px" srcset="https://miro.medium.com/v2/resize:fit:640/1*gVvI3V9QZNYFpcaEjKU7-A.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*gVvI3V9QZNYFpcaEjKU7-A.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*gVvI3V9QZNYFpcaEjKU7-A.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*gVvI3V9QZNYFpcaEjKU7-A.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*gVvI3V9QZNYFpcaEjKU7-A.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*gVvI3V9QZNYFpcaEjKU7-A.gif 1100w, https://miro.medium.com/v2/resize:fit:1024/1*gVvI3V9QZNYFpcaEjKU7-A.gif 1024w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 512px" srcset="https://miro.medium.com/v2/resize:fit:640/1*gVvI3V9QZNYFpcaEjKU7-A.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*gVvI3V9QZNYFpcaEjKU7-A.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*gVvI3V9QZNYFpcaEjKU7-A.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*gVvI3V9QZNYFpcaEjKU7-A.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*gVvI3V9QZNYFpcaEjKU7-A.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*gVvI3V9QZNYFpcaEjKU7-A.gif 1100w, https://miro.medium.com/v2/resize:fit:1024/1*gVvI3V9QZNYFpcaEjKU7-A.gif 1024w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/512/1*gVvI3V9QZNYFpcaEjKU7-A.gif"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;"><a href="https://deepmind.com/blog/wavenet-generative-model-raw-audio/" target="_self">WaveNet</a></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Many have written about how deep learning is taking over the world and why that is important; I cannot echo them enough. Playing with deep learning is the closest I’ve ever felt to being a magician, and it’s become clear to me that every <em>(great)</em> piece of software will be powered by deep learning within the next ~3 years. However, deep learning isn’t mainstream yet, so I thought I’d share work by some very talented contributors, in the hopes to bring it just that <em>little</em> bit closer.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5"><strong>Quick note: I’ve started a weekly email newsletter covering all things deep learning and self-driving cars. </strong><a href="http://transmission.ai" target="_self">I call it Transmission, sign up today!</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Here’s ten reasons why I think deep learning is living up to the hype…</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>1</span><strong> </strong><a href="https://github.com/alexjc/neural-enhance" target="_self">Stuck with a low-resolution photo? Deep learning can predict what the higher-resolution photo might look like, and add missing details</a></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://medium.com/media/aa61a220fa2d8c407ac185d512da960a">Click Here!</a></p></div></div></div></section><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://github.com/nagadomi/waifu2x" target="_self">…it’s equally impressive for anime art</a></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*Gkg7yPVtjkF0wOPIWZtxBQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*Gkg7yPVtjkF0wOPIWZtxBQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>2</span><strong> </strong><a href="https://deepmind.com/blog/wavenet-generative-model-raw-audio/" target="_self">Deep learning has enabled a text-to-speech system that is almost indistinguishable from human voice</a><strong>.</strong> Think of the possibilities!</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://medium.com/media/4156f51c702f76eb074f44b0f57e2f4a">Click Here!</a></p></div></div></div></section><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fw.soundcloud.com%2Fplayer%2F%3Furl%3Dhttp%253A%252F%252Fapi.soundcloud.com%252Ftracks%252F290831533%26show_artwork%3Dtrue&url=https%3A%2F%2Fsoundcloud.com%2Foliver-cameron-330659812%2Fwavenet-sample-2&image=http%3A%2F%2Fa1.sndcdn.com%2Fimages%2Ffb_placeholder.png%3F1477928887&key=d04bfffea46d4aeda930ec88cc64b87c&type=text%2Fhtml&schema=soundcloud">Click Here!</a></p></div></div></div></section><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>3</span><a href="https://deepmind.com/blog/wavenet-generative-model-raw-audio/" target="_self"> Deep learning can compose classical music that you’d believe to be created by a human</a></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fw.soundcloud.com%2Fplayer%2F%3Furl%3Dhttp%253A%252F%252Fapi.soundcloud.com%252Ftracks%252F290597221%26show_artwork%3Dtrue&url=https%3A%2F%2Fsoundcloud.com%2Foliver-cameron-330659812%2Fwavenet-sample-1&image=http%3A%2F%2Fa1.sndcdn.com%2Fimages%2Ffb_placeholder.png%3F1477657343&key=d04bfffea46d4aeda930ec88cc64b87c&type=text%2Fhtml&schema=soundcloud">Click Here!</a></p></div></div></div></section><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>4</span><strong> </strong><a href="https://research.googleblog.com/2016/10/supercharging-style-transfer.html" target="_self">Deep learning can replicate the style of your favorite painter with the image of your choice</a></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:87%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 640px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*WsAKFc_5-IJL0O7O0KIE0w.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*WsAKFc_5-IJL0O7O0KIE0w.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*WsAKFc_5-IJL0O7O0KIE0w.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*WsAKFc_5-IJL0O7O0KIE0w.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*WsAKFc_5-IJL0O7O0KIE0w.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*WsAKFc_5-IJL0O7O0KIE0w.png 1100w, https://miro.medium.com/v2/resize:fit:1280/format:webp/1*WsAKFc_5-IJL0O7O0KIE0w.png 1280w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 640px" srcset="https://miro.medium.com/v2/resize:fit:640/1*WsAKFc_5-IJL0O7O0KIE0w.png 640w, https://miro.medium.com/v2/resize:fit:720/1*WsAKFc_5-IJL0O7O0KIE0w.png 720w, https://miro.medium.com/v2/resize:fit:750/1*WsAKFc_5-IJL0O7O0KIE0w.png 750w, https://miro.medium.com/v2/resize:fit:786/1*WsAKFc_5-IJL0O7O0KIE0w.png 786w, https://miro.medium.com/v2/resize:fit:828/1*WsAKFc_5-IJL0O7O0KIE0w.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*WsAKFc_5-IJL0O7O0KIE0w.png 1100w, https://miro.medium.com/v2/resize:fit:1280/1*WsAKFc_5-IJL0O7O0KIE0w.png 1280w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/640/1*WsAKFc_5-IJL0O7O0KIE0w.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Read a paper on this technique <a href="http://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Gatys_Image_Style_Transfer_CVPR_2016_paper.pdf" target="_self">here</a>.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>5</span><strong> </strong><a href="https://erikbern.com/2016/01/21/analyzing-50k-fonts-using-deep-neural-networks/" target="_self">Deep learning can even generate fonts</a><strong>!</strong></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:69%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 512px" srcset="https://miro.medium.com/v2/resize:fit:640/1*HyG_V95simQdR8TuJIrgaw.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*HyG_V95simQdR8TuJIrgaw.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*HyG_V95simQdR8TuJIrgaw.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*HyG_V95simQdR8TuJIrgaw.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*HyG_V95simQdR8TuJIrgaw.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*HyG_V95simQdR8TuJIrgaw.gif 1100w, https://miro.medium.com/v2/resize:fit:1024/1*HyG_V95simQdR8TuJIrgaw.gif 1024w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 512px" srcset="https://miro.medium.com/v2/resize:fit:640/1*HyG_V95simQdR8TuJIrgaw.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*HyG_V95simQdR8TuJIrgaw.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*HyG_V95simQdR8TuJIrgaw.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*HyG_V95simQdR8TuJIrgaw.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*HyG_V95simQdR8TuJIrgaw.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*HyG_V95simQdR8TuJIrgaw.gif 1100w, https://miro.medium.com/v2/resize:fit:1024/1*HyG_V95simQdR8TuJIrgaw.gif 1024w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/512/1*HyG_V95simQdR8TuJIrgaw.gif"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>6</span><a href="https://bamos.github.io/2016/08/09/deep-completion/" target="_self">Deep learning can auto-fill missing parts of an image, by predicting what should be in that space</a></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:69%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 512px" srcset="https://miro.medium.com/v2/resize:fit:640/1*wPaRi774o4z-9QTtDqvhxQ.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*wPaRi774o4z-9QTtDqvhxQ.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*wPaRi774o4z-9QTtDqvhxQ.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*wPaRi774o4z-9QTtDqvhxQ.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*wPaRi774o4z-9QTtDqvhxQ.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*wPaRi774o4z-9QTtDqvhxQ.gif 1100w, https://miro.medium.com/v2/resize:fit:1024/1*wPaRi774o4z-9QTtDqvhxQ.gif 1024w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 512px" srcset="https://miro.medium.com/v2/resize:fit:640/1*wPaRi774o4z-9QTtDqvhxQ.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*wPaRi774o4z-9QTtDqvhxQ.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*wPaRi774o4z-9QTtDqvhxQ.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*wPaRi774o4z-9QTtDqvhxQ.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*wPaRi774o4z-9QTtDqvhxQ.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*wPaRi774o4z-9QTtDqvhxQ.gif 1100w, https://miro.medium.com/v2/resize:fit:1024/1*wPaRi774o4z-9QTtDqvhxQ.gif 1024w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/512/1*wPaRi774o4z-9QTtDqvhxQ.gif"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>7</span><a href="https://blogs.nvidia.com/blog/2016/01/15/deep-learning-robot-walk/" target="_self">Deep learning can train a robot to walk like a human</a></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:95%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 698px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*ClcbwGyCCias_M-JNLkp7A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*ClcbwGyCCias_M-JNLkp7A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*ClcbwGyCCias_M-JNLkp7A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*ClcbwGyCCias_M-JNLkp7A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*ClcbwGyCCias_M-JNLkp7A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ClcbwGyCCias_M-JNLkp7A.png 1100w, https://miro.medium.com/v2/resize:fit:1396/format:webp/1*ClcbwGyCCias_M-JNLkp7A.png 1396w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 698px" srcset="https://miro.medium.com/v2/resize:fit:640/1*ClcbwGyCCias_M-JNLkp7A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*ClcbwGyCCias_M-JNLkp7A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*ClcbwGyCCias_M-JNLkp7A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*ClcbwGyCCias_M-JNLkp7A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*ClcbwGyCCias_M-JNLkp7A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*ClcbwGyCCias_M-JNLkp7A.png 1100w, https://miro.medium.com/v2/resize:fit:1396/1*ClcbwGyCCias_M-JNLkp7A.png 1396w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/698/1*ClcbwGyCCias_M-JNLkp7A.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;"><em>Without being taught, the deep learning robot rises from the floor to a standing position. Image courtesy of the University of Washington</em></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://research.googleblog.com/2016/03/deep-learning-for-robots-learning-from.html" target="_self">…or train a robot to grasp objects like a human</a></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:80%;"><iframe  scrolling="auto" width="854.0" height="480.0" frameborder="0" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FH4V6NZLNu-c%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DH4V6NZLNu-c&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FH4V6NZLNu-c%2Fhqdefault.jpg&key=a19fcc184b9711e1b4764040d3dc5c07&type=text%2Fhtml&schema=youtube" allowfullscreen=""></iframe></div><br><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>8</span><a href="http://karpathy.github.io/2015/05/21/rnn-effectiveness/" target="_self">Deep learning can caption an image, just like a human would</a></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*thSbyGo2JwWPyQIjAhAy7w.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*thSbyGo2JwWPyQIjAhAy7w.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*thSbyGo2JwWPyQIjAhAy7w.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*thSbyGo2JwWPyQIjAhAy7w.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*thSbyGo2JwWPyQIjAhAy7w.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*thSbyGo2JwWPyQIjAhAy7w.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*thSbyGo2JwWPyQIjAhAy7w.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*thSbyGo2JwWPyQIjAhAy7w.png 640w, https://miro.medium.com/v2/resize:fit:720/1*thSbyGo2JwWPyQIjAhAy7w.png 720w, https://miro.medium.com/v2/resize:fit:750/1*thSbyGo2JwWPyQIjAhAy7w.png 750w, https://miro.medium.com/v2/resize:fit:786/1*thSbyGo2JwWPyQIjAhAy7w.png 786w, https://miro.medium.com/v2/resize:fit:828/1*thSbyGo2JwWPyQIjAhAy7w.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*thSbyGo2JwWPyQIjAhAy7w.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*thSbyGo2JwWPyQIjAhAy7w.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*thSbyGo2JwWPyQIjAhAy7w.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>9</span><a href="https://github.com/alexjc/neural-doodle" target="_self">Want to sketch a beautiful landscape but can’t draw? Don’t worry, deep learning can take it from here</a><strong>!</strong></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*DiIg3jMaC237O2GF4DyuYg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*DiIg3jMaC237O2GF4DyuYg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*DiIg3jMaC237O2GF4DyuYg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*DiIg3jMaC237O2GF4DyuYg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*DiIg3jMaC237O2GF4DyuYg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*DiIg3jMaC237O2GF4DyuYg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*DiIg3jMaC237O2GF4DyuYg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*DiIg3jMaC237O2GF4DyuYg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*DiIg3jMaC237O2GF4DyuYg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*DiIg3jMaC237O2GF4DyuYg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*DiIg3jMaC237O2GF4DyuYg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*DiIg3jMaC237O2GF4DyuYg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*DiIg3jMaC237O2GF4DyuYg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*DiIg3jMaC237O2GF4DyuYg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*DiIg3jMaC237O2GF4DyuYg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>10</span><a href="https://arxiv.org/abs/1604.07316" target="_self">Best of all (at least to me), you can train a deep neural network to steer a car</a><strong>, just like a human</strong></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://medium.com/media/341527f46c868ebceb97efe9744b5d53">Click Here!</a></p></div></div></div></section><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://medium.com/media/09cc00fd8e9308da163d8f5cbf5463be">Click Here!</a></p></div></div></div></section><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="http://deepdrive.io" target="_self">…it even turns out Grand Theft Auto is a great simulation environment for training a self-driving car</a></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:80%;"><iframe  scrolling="auto" width="854.0" height="480.0" frameborder="0" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FDeE8tntTSPI%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DDeE8tntTSPI&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FDeE8tntTSPI%2Fhqdefault.jpg&key=d04bfffea46d4aeda930ec88cc64b87c&type=text%2Fhtml&schema=youtube" allowfullscreen=""></iframe></div><br><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>We’ve spent decades building and refining machines to be computationally powerful. In the next decade I hope we discover what the human race will be empowered to do when our software thinks.</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">I’ve started a weekly email newsletter covering all things deep learning and self-driving cars: <a href="http://transmission.ai" target="_self">I call it Transmission, sign up today!</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://twitter.com/olivercameron"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Oliver Cameron (@olivercameron) | Twitter</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">The latest Tweets from Oliver Cameron (@olivercameron). I lead the self-driving car team at @udacity. Previously…</h3><p>twitter.com</p></a></div></div></div></div></section><br><?php include_once 'Elemental/footer.php'; ?>