<!DOCTYPE html>
                <html>
                <head>
                    <title>GNNs to Data Augmentation to Building Distributed Applications at Scale with Open-source</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://pub.towardsai.net/gnns-to-data-augmentation-to-building-distributed-applications-at-scale-with-open-source-15822cc0cc78"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://towardsai.medium.com/?source=post_page-----15822cc0cc78--------------------------------">Author : Towards AI Editorial Team</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://towardsai.net/p/category/news" target="_self">NEWS</a><strong>, </strong><a href="https://towardsai.net/p/category/newsletter" target="_self">NEWSLETTER</a></h4></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>GNNs to Data Augmentation to Building Distributed Applications at Scale with Open-source</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5 text-muted">AI news, research, and updates, an exciting and free-to-attend AI summit, and our monthly editorial picks!</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>If you have trouble reading this email, see it on a </strong><a href="http://ws.towardsai.net/g9k" target="_self">web browser</a><strong>.</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><span>T</span>he open-source <a href="https://members.towardsai.net/" target="_self">AI community</a><strong> </strong>is seeing rapid growth. Open-source projects like TensorFlow, Theano, Caffe, BERT, MXNet, PyTorch, Gluon, and PyStanfordNLP are among the ones helping make AI accessible to everyone. To get you even more excited about scalable AI, check out this excellent and free-to-access event, presented by <strong>Anyscale</strong>:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*f_lO-oGaEosOVJd2msTlgA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*f_lO-oGaEosOVJd2msTlgA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*f_lO-oGaEosOVJd2msTlgA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*f_lO-oGaEosOVJd2msTlgA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*f_lO-oGaEosOVJd2msTlgA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*f_lO-oGaEosOVJd2msTlgA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*f_lO-oGaEosOVJd2msTlgA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*f_lO-oGaEosOVJd2msTlgA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*f_lO-oGaEosOVJd2msTlgA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*f_lO-oGaEosOVJd2msTlgA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*f_lO-oGaEosOVJd2msTlgA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*f_lO-oGaEosOVJd2msTlgA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*f_lO-oGaEosOVJd2msTlgA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*f_lO-oGaEosOVJd2msTlgA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*f_lO-oGaEosOVJd2msTlgA.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">[Free] <a href="http://ws.towardsai.net/inb" target="_self">Ray Summit June 22–24</a>: The best way to scale AI</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="http://ws.towardsai.net/inb" target="_self">Ray Summit</a><strong> </strong>brings together developers, data scientists, architects, and product managers to build scalable AI using Ray, the dominant framework for distributed computing. Topics include top AI trends, ML in production, MLOps, reinforcement learning, cloud computing, serverless & more. <a href="http://ws.towardsai.net/inb" target="_self">Register free to join live or on-demand</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Most commonly used implementations of GNNs in practice use a node-wise thresholding strategy to protect sensitive information (e.g., emails, phone numbers, street addresses, etc.). This approach is vulnerable to information leakage attacks on social networks. Researchers from MIT, Carnegie Mellon, and UIUC led by Peiyuan Liao propose a <a href="https://mktg.best/uyf2b" target="_self">new algorithm graph adversarial network (GAL)</a> with minimax games to protect such sensitive information.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:85%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 623px" srcset="https://miro.medium.com/v2/resize:fit:640/0*dFe625sI6dsOYPwq 640w, https://miro.medium.com/v2/resize:fit:720/0*dFe625sI6dsOYPwq 720w, https://miro.medium.com/v2/resize:fit:750/0*dFe625sI6dsOYPwq 750w, https://miro.medium.com/v2/resize:fit:786/0*dFe625sI6dsOYPwq 786w, https://miro.medium.com/v2/resize:fit:828/0*dFe625sI6dsOYPwq 828w, https://miro.medium.com/v2/resize:fit:1100/0*dFe625sI6dsOYPwq 1100w, https://miro.medium.com/v2/resize:fit:1246/0*dFe625sI6dsOYPwq 1246w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 623px" srcset="https://miro.medium.com/v2/resize:fit:640/0*dFe625sI6dsOYPwq 640w, https://miro.medium.com/v2/resize:fit:720/0*dFe625sI6dsOYPwq 720w, https://miro.medium.com/v2/resize:fit:750/0*dFe625sI6dsOYPwq 750w, https://miro.medium.com/v2/resize:fit:786/0*dFe625sI6dsOYPwq 786w, https://miro.medium.com/v2/resize:fit:828/0*dFe625sI6dsOYPwq 828w, https://miro.medium.com/v2/resize:fit:1100/0*dFe625sI6dsOYPwq 1100w, https://miro.medium.com/v2/resize:fit:1246/0*dFe625sI6dsOYPwq 1246w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/623/0*dFe625sI6dsOYPwq"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In the field of <a href="https://news.towardsai.net/nlp" target="_self">Natural Language Processing (NLP)</a>, data augmentation comes at a premium. Improving model performance by relying on auxiliary datasets is a proven tactic in many NLP subfields. However, it is by no means an “easy” problem. Check out <a href="https://mktg.best/l0l53" target="_self">this paper</a> led by researchers at Google, Carnegie Mellon, and Mila — Quebec AI exploring state-of-the-art techniques used for data augmentation approaches (DAA).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Next, it is common in the supervised <a href="https://mld.ai/mldcmu" target="_self">machine learning</a> literature to assume that early learning implies generalization: to develop a system that performs well on the early part of the training set will result in extrapolation to unseen or future data. <a href="https://mktg.best/pi6it" target="_self">This paper</a> led by Saurabh Garg with <a href="https://mld.ai/mldcmu" target="_self">Machine Learning at CMU</a> presents results that show this hypothesis is true for a wide variety of models and problem types: the work shows that early learning is key to understanding generalization.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now, let’s face it. AI systems are often opaque, strange, and difficult to use. In the field of machine learning, this is particularly true. If we want to make intelligent systems that people can understand and interact with — more easily, a key part of the solution is a community where people can come together, share ideas and learn from each other. That is why we created our <a href="https://members.towardsai.net/" target="_self">AI community on Discord </a>— to connect and learn with other data experts and enthusiasts.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you have not checked it out yet, we recently launched our <a href="https://news.towardsai.net/descriptive-statistics" target="_self">book</a> on <a href="https://gumroad.com/l/descriptive-statistics" target="_self">descriptive statistics</a> with Python. This <a href="https://news.towardsai.net/descriptive-statistics-book-sample" target="_self">article</a> or this <a href="https://github.com/towardsai/tutorials/blob/master/descriptive-statistics/descriptive-statistics-pdf-book-sample.pdf" target="_self">PDF</a> provides a sample of the first 36 pages of the book. Please don’t forget that you can access this work, many more books, and other goodies by becoming a <a href="https://members.towardsai.net/" target="_self">member</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Sharing is caring. Please feel free to share our <a href="http://ws.towardsai.net/g9k" target="_self">newsletter</a> or <a href="https://ws.towardsai.net/subscribe" target="_self">subscription link</a> with your friends, colleagues, and acquaintances. One email per month; unsubscribe anytime! <strong>If you have any feedback on how we can improve, please feel free to </strong><a href="https://app.joinpalette.com/t/amas/n1PYGbcbPthObD71gGCq" target="_self">let us know</a><strong>.</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now into the monthly picks! We pick these articles based on readers, fans, and views a specific piece gets. We hope you enjoy reading them as much as we did. Also, we started doing something new! We will pick our top-performing articles, and our editors will choose a couple of essays that didn’t have outstanding performance, but due to their quality — they made the cut for the month.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">📚 Editor’s choice featured articles of the month ↓ 📚</h4></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*l-uwaNxBfEk67opd 640w, https://miro.medium.com/v2/resize:fit:720/0*l-uwaNxBfEk67opd 720w, https://miro.medium.com/v2/resize:fit:750/0*l-uwaNxBfEk67opd 750w, https://miro.medium.com/v2/resize:fit:786/0*l-uwaNxBfEk67opd 786w, https://miro.medium.com/v2/resize:fit:828/0*l-uwaNxBfEk67opd 828w, https://miro.medium.com/v2/resize:fit:1100/0*l-uwaNxBfEk67opd 1100w, https://miro.medium.com/v2/resize:fit:1400/0*l-uwaNxBfEk67opd 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*l-uwaNxBfEk67opd 640w, https://miro.medium.com/v2/resize:fit:720/0*l-uwaNxBfEk67opd 720w, https://miro.medium.com/v2/resize:fit:750/0*l-uwaNxBfEk67opd 750w, https://miro.medium.com/v2/resize:fit:786/0*l-uwaNxBfEk67opd 786w, https://miro.medium.com/v2/resize:fit:828/0*l-uwaNxBfEk67opd 828w, https://miro.medium.com/v2/resize:fit:1100/0*l-uwaNxBfEk67opd 1100w, https://miro.medium.com/v2/resize:fit:1400/0*l-uwaNxBfEk67opd 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*l-uwaNxBfEk67opd"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/lbczl" target="_self">State of the Art Models in Every Machine Learning Field 2021</a> by <a style="color:green" href="https://medium.com/u/b1f214c06d3e?source=post_page-----15822cc0cc78--------------------------------" target="_self">Mostafa Ibrahim</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">State-of-the-art models keep changing all the time. As someone who has been doing Kaggle competitions for almost a year now, I find myself coming across many of them, making comparisons, evaluating, and testing them. I thought it would be a good idea to list the best models for each ML task so that you know where to start. Without further ado, let’s get started!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/lbczl" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*_dt72tteTfYBmmM0.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*_dt72tteTfYBmmM0.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*_dt72tteTfYBmmM0.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*_dt72tteTfYBmmM0.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*_dt72tteTfYBmmM0.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*_dt72tteTfYBmmM0.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*_dt72tteTfYBmmM0.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*_dt72tteTfYBmmM0.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/0*_dt72tteTfYBmmM0.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/0*_dt72tteTfYBmmM0.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/0*_dt72tteTfYBmmM0.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/0*_dt72tteTfYBmmM0.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/0*_dt72tteTfYBmmM0.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/0*_dt72tteTfYBmmM0.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*_dt72tteTfYBmmM0.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="http://news.towardsai.net/pdm" target="_self">Understanding Pandas Melt — pd.melt()</a> by <a style="color:green" href="https://medium.com/u/aea8a19ea239?source=post_page-----15822cc0cc78--------------------------------" target="_self">Towards AI Team</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The <strong>Pandas melt()</strong> function is within many other methods to reshape the pandas DataFrames from wide to a long format, particularly in <a href="https://mld.ai/mldcmu" target="_self">data science</a>. However, the <code>pd.melt()</code> function is <strong>the most efficient and flexible among them</strong>. The <code>pd.melt()</code> function unpivots/melts the pandas DataFrame from a wide to a long format.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="http://news.towardsai.net/pdm" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*wCWNA1IGIs8NVBpG.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*wCWNA1IGIs8NVBpG.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*wCWNA1IGIs8NVBpG.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*wCWNA1IGIs8NVBpG.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*wCWNA1IGIs8NVBpG.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*wCWNA1IGIs8NVBpG.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*wCWNA1IGIs8NVBpG.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*wCWNA1IGIs8NVBpG.png 640w, https://miro.medium.com/v2/resize:fit:720/0*wCWNA1IGIs8NVBpG.png 720w, https://miro.medium.com/v2/resize:fit:750/0*wCWNA1IGIs8NVBpG.png 750w, https://miro.medium.com/v2/resize:fit:786/0*wCWNA1IGIs8NVBpG.png 786w, https://miro.medium.com/v2/resize:fit:828/0*wCWNA1IGIs8NVBpG.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*wCWNA1IGIs8NVBpG.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*wCWNA1IGIs8NVBpG.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*wCWNA1IGIs8NVBpG.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/entid" target="_self">Will Transformers Replace CNNs in Computer Vision?</a> by <a style="color:green" href="https://medium.com/u/f34bfe2bbaec?source=post_page-----15822cc0cc78--------------------------------" target="_self">Louis (What’s AI) Bouchard</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This article is about most probably the next generation of neural networks for all computer vision applications: The transformer architecture. You’ve certainly already heard about this architecture in the field of natural language processing, or NLP, mainly with GPT3 that made much noise in 2020. Transformers can be used as a general-purpose backbone for many different applications and not only NLP. In a couple of minutes, you will know how the transformer architecture can be applied to computer vision with a new paper called the Swin Transformer by Ze Lio et al. from Microsoft Research [1].</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/entid" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*0j0rOGdACU2gD_Na 640w, https://miro.medium.com/v2/resize:fit:720/0*0j0rOGdACU2gD_Na 720w, https://miro.medium.com/v2/resize:fit:750/0*0j0rOGdACU2gD_Na 750w, https://miro.medium.com/v2/resize:fit:786/0*0j0rOGdACU2gD_Na 786w, https://miro.medium.com/v2/resize:fit:828/0*0j0rOGdACU2gD_Na 828w, https://miro.medium.com/v2/resize:fit:1100/0*0j0rOGdACU2gD_Na 1100w, https://miro.medium.com/v2/resize:fit:1400/0*0j0rOGdACU2gD_Na 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*0j0rOGdACU2gD_Na 640w, https://miro.medium.com/v2/resize:fit:720/0*0j0rOGdACU2gD_Na 720w, https://miro.medium.com/v2/resize:fit:750/0*0j0rOGdACU2gD_Na 750w, https://miro.medium.com/v2/resize:fit:786/0*0j0rOGdACU2gD_Na 786w, https://miro.medium.com/v2/resize:fit:828/0*0j0rOGdACU2gD_Na 828w, https://miro.medium.com/v2/resize:fit:1100/0*0j0rOGdACU2gD_Na 1100w, https://miro.medium.com/v2/resize:fit:1400/0*0j0rOGdACU2gD_Na 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*0j0rOGdACU2gD_Na"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/5364i" target="_self">My VS Code Setup To Prototype Algorithmic Trading Strategies Locally Using LEAN</a> by <a style="color:green" href="https://medium.com/u/3c36dad0dabc?source=post_page-----15822cc0cc78--------------------------------" target="_self">___</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This article represents documentation on my VS Code setup to develop algorithmic trading strategies using QuantConnect’s <a href="https://github.com/quantconnect/lean" target="_self">LEAN </a>engine on a local machine. It is an alternative to using the QuantConnect Lean CLI tool. All the code and scripts to reproduce the results described in this article can be found in this repo.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/5364i" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:80%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 593px" srcset="https://miro.medium.com/v2/resize:fit:640/0*gkRqELWnE0G4Sxn_.gif 640w, https://miro.medium.com/v2/resize:fit:720/0*gkRqELWnE0G4Sxn_.gif 720w, https://miro.medium.com/v2/resize:fit:750/0*gkRqELWnE0G4Sxn_.gif 750w, https://miro.medium.com/v2/resize:fit:786/0*gkRqELWnE0G4Sxn_.gif 786w, https://miro.medium.com/v2/resize:fit:828/0*gkRqELWnE0G4Sxn_.gif 828w, https://miro.medium.com/v2/resize:fit:1100/0*gkRqELWnE0G4Sxn_.gif 1100w, https://miro.medium.com/v2/resize:fit:1186/0*gkRqELWnE0G4Sxn_.gif 1186w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 593px" srcset="https://miro.medium.com/v2/resize:fit:640/0*gkRqELWnE0G4Sxn_.gif 640w, https://miro.medium.com/v2/resize:fit:720/0*gkRqELWnE0G4Sxn_.gif 720w, https://miro.medium.com/v2/resize:fit:750/0*gkRqELWnE0G4Sxn_.gif 750w, https://miro.medium.com/v2/resize:fit:786/0*gkRqELWnE0G4Sxn_.gif 786w, https://miro.medium.com/v2/resize:fit:828/0*gkRqELWnE0G4Sxn_.gif 828w, https://miro.medium.com/v2/resize:fit:1100/0*gkRqELWnE0G4Sxn_.gif 1100w, https://miro.medium.com/v2/resize:fit:1186/0*gkRqELWnE0G4Sxn_.gif 1186w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/593/0*gkRqELWnE0G4Sxn_.gif"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/302g0" target="_self">Plotly Express: Interprete data through interactive visualization</a> by <a style="color:green" href="https://medium.com/u/86fdc517c278?source=post_page-----15822cc0cc78--------------------------------" target="_self">Eugenia Anello</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">It’s the right moment to move forward to other tools to visualize your data. Do you know <strong>Matplotlib</strong>? Forget it. Maybe it can be easy to apply and doesn’t occupy much memory, but it’s hard to observe the change of features over time from static graphs.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/302g0" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*lrGDG1buFWG4OU3e.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*lrGDG1buFWG4OU3e.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*lrGDG1buFWG4OU3e.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*lrGDG1buFWG4OU3e.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*lrGDG1buFWG4OU3e.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*lrGDG1buFWG4OU3e.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*lrGDG1buFWG4OU3e.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*lrGDG1buFWG4OU3e.png 640w, https://miro.medium.com/v2/resize:fit:720/0*lrGDG1buFWG4OU3e.png 720w, https://miro.medium.com/v2/resize:fit:750/0*lrGDG1buFWG4OU3e.png 750w, https://miro.medium.com/v2/resize:fit:786/0*lrGDG1buFWG4OU3e.png 786w, https://miro.medium.com/v2/resize:fit:828/0*lrGDG1buFWG4OU3e.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*lrGDG1buFWG4OU3e.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*lrGDG1buFWG4OU3e.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*lrGDG1buFWG4OU3e.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/oyghe" target="_self">Complete List of Feature Engineering Methods: 40 Techniques, 10 Categories</a> by <a style="color:green" href="https://medium.com/u/153452706ad7?source=post_page-----15822cc0cc78--------------------------------" target="_self">Michelangiolo Mazzeschi</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In reality, feature engineering becomes vital when you start transitioning into Big Data. Big Data analytics is and will always remain in high demand because, as of now, there is almost no way you can learn how to work on a gigantic dataset on your own. The only way to start approaching big data is with a team of experts in the working place. It is the real all-hands-on-deck experience of data science.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/oyghe" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*7MXaqYLGDUmgOGAh.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*7MXaqYLGDUmgOGAh.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*7MXaqYLGDUmgOGAh.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*7MXaqYLGDUmgOGAh.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*7MXaqYLGDUmgOGAh.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*7MXaqYLGDUmgOGAh.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*7MXaqYLGDUmgOGAh.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*7MXaqYLGDUmgOGAh.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/0*7MXaqYLGDUmgOGAh.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/0*7MXaqYLGDUmgOGAh.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/0*7MXaqYLGDUmgOGAh.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/0*7MXaqYLGDUmgOGAh.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/0*7MXaqYLGDUmgOGAh.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/0*7MXaqYLGDUmgOGAh.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*7MXaqYLGDUmgOGAh.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/je65e" target="_self">How to Use Analytical Geometry to Find the Shortest Route/Loop for Any Euclidean Travelling Salesman Problem Efficiently</a> by <a style="color:green" href="https://medium.com/u/edc61e2d976?source=post_page-----15822cc0cc78--------------------------------" target="_self">Ashutosh Malgaonkar</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">“The <strong>traveling salesman problem </strong>(also called the <strong>traveling salesperson problem</strong><a href="https://en.wikipedia.org/wiki/Travelling_salesman_problem#cite_note-1" target="_self">[1]</a> or <strong>TSP</strong>) asks the following question: “Given a list of cities and the distances between each pair of cities, what is the shortest possible route that visits each city exactly once and returns to the origin city?” It is an NP-hard problem in combinatorial optimization, important in theoretical computer science and operations research…</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/je65e" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*Uz3-It80a4YDCQu7.jpg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*Uz3-It80a4YDCQu7.jpg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*Uz3-It80a4YDCQu7.jpg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*Uz3-It80a4YDCQu7.jpg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*Uz3-It80a4YDCQu7.jpg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*Uz3-It80a4YDCQu7.jpg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*Uz3-It80a4YDCQu7.jpg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*Uz3-It80a4YDCQu7.jpg 640w, https://miro.medium.com/v2/resize:fit:720/0*Uz3-It80a4YDCQu7.jpg 720w, https://miro.medium.com/v2/resize:fit:750/0*Uz3-It80a4YDCQu7.jpg 750w, https://miro.medium.com/v2/resize:fit:786/0*Uz3-It80a4YDCQu7.jpg 786w, https://miro.medium.com/v2/resize:fit:828/0*Uz3-It80a4YDCQu7.jpg 828w, https://miro.medium.com/v2/resize:fit:1100/0*Uz3-It80a4YDCQu7.jpg 1100w, https://miro.medium.com/v2/resize:fit:1400/0*Uz3-It80a4YDCQu7.jpg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*Uz3-It80a4YDCQu7.jpg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/zjgbx" target="_self">DeepMind Combines Logic and Neural Networks to Extract Rules from Noisy Data</a> by <a style="color:green" href="https://medium.com/u/46674a2c9422?source=post_page-----15822cc0cc78--------------------------------" target="_self">Jesus Rodriguez</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In his book “The Master Algorithm,” artificial intelligence researcher Pedro Domingos explores the idea of a single algorithm that can combine the significant schools of machine learning. The idea is, without a doubt, extremely ambitious, but we already see some iterations of it. Last year, Google published a research paper under the catchy title of…</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/zjgbx" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*OwOxvJ9uw4n2Q74I.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*OwOxvJ9uw4n2Q74I.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*OwOxvJ9uw4n2Q74I.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*OwOxvJ9uw4n2Q74I.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*OwOxvJ9uw4n2Q74I.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*OwOxvJ9uw4n2Q74I.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*OwOxvJ9uw4n2Q74I.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*OwOxvJ9uw4n2Q74I.png 640w, https://miro.medium.com/v2/resize:fit:720/0*OwOxvJ9uw4n2Q74I.png 720w, https://miro.medium.com/v2/resize:fit:750/0*OwOxvJ9uw4n2Q74I.png 750w, https://miro.medium.com/v2/resize:fit:786/0*OwOxvJ9uw4n2Q74I.png 786w, https://miro.medium.com/v2/resize:fit:828/0*OwOxvJ9uw4n2Q74I.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*OwOxvJ9uw4n2Q74I.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*OwOxvJ9uw4n2Q74I.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*OwOxvJ9uw4n2Q74I.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/n3a7e" target="_self">Understand Time Series Components with Python</a> by <a style="color:green" href="https://medium.com/u/502d63083812?source=post_page-----15822cc0cc78--------------------------------" target="_self">Amit Chauhan</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In this article, we will discuss time series concepts with machine learning examples that deal with the time component in the data. Forecasting is essential in the banking sector, weather, population prediction, and many more that directly deals with real-life problems.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/n3a7e" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*UtbNof3Pioly2GsH 640w, https://miro.medium.com/v2/resize:fit:720/0*UtbNof3Pioly2GsH 720w, https://miro.medium.com/v2/resize:fit:750/0*UtbNof3Pioly2GsH 750w, https://miro.medium.com/v2/resize:fit:786/0*UtbNof3Pioly2GsH 786w, https://miro.medium.com/v2/resize:fit:828/0*UtbNof3Pioly2GsH 828w, https://miro.medium.com/v2/resize:fit:1100/0*UtbNof3Pioly2GsH 1100w, https://miro.medium.com/v2/resize:fit:1400/0*UtbNof3Pioly2GsH 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*UtbNof3Pioly2GsH 640w, https://miro.medium.com/v2/resize:fit:720/0*UtbNof3Pioly2GsH 720w, https://miro.medium.com/v2/resize:fit:750/0*UtbNof3Pioly2GsH 750w, https://miro.medium.com/v2/resize:fit:786/0*UtbNof3Pioly2GsH 786w, https://miro.medium.com/v2/resize:fit:828/0*UtbNof3Pioly2GsH 828w, https://miro.medium.com/v2/resize:fit:1100/0*UtbNof3Pioly2GsH 1100w, https://miro.medium.com/v2/resize:fit:1400/0*UtbNof3Pioly2GsH 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*UtbNof3Pioly2GsH"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/z5ho3" target="_self">Data Versioning for Efficient Workflows with MLFlow and LakeFS</a> by <a style="color:green" href="https://medium.com/u/76c21e75463a?source=post_page-----15822cc0cc78--------------------------------" target="_self">Giorgos Myrianthous</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Version Control Systems, such as Git, are essential tools for versioning and archiving source code. Version Control helps you keep track of the changes in the code. When a change is made, an error could be introduced, too, but with source control tools, developers can roll back to a working state and compare it against the non-working piece of code. This minimizes the disruption to other team members that are probably working with the code and helps them collaborate efficiently.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/z5ho3" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*Jc4NMSdshv0IFPM3.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*Jc4NMSdshv0IFPM3.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*Jc4NMSdshv0IFPM3.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*Jc4NMSdshv0IFPM3.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*Jc4NMSdshv0IFPM3.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*Jc4NMSdshv0IFPM3.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*Jc4NMSdshv0IFPM3.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*Jc4NMSdshv0IFPM3.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/0*Jc4NMSdshv0IFPM3.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/0*Jc4NMSdshv0IFPM3.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/0*Jc4NMSdshv0IFPM3.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/0*Jc4NMSdshv0IFPM3.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/0*Jc4NMSdshv0IFPM3.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/0*Jc4NMSdshv0IFPM3.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*Jc4NMSdshv0IFPM3.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/6vlyj" target="_self">Understand Bayes’ Theorem Through Visualization</a> by <a style="color:green" href="https://medium.com/u/43a2b4818096?source=post_page-----15822cc0cc78--------------------------------" target="_self">Satsawat Natakarnkitkul</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">When we get started in our machine learning journey, we often asked ourselves whether we should learn statistics and probability or not, especially probability. The answers depend on where you are and how much depth you want to get yourself into understanding it. However, keep these in mind…</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/6vlyj" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*V5WlBfqwMtoMJmsr 640w, https://miro.medium.com/v2/resize:fit:720/0*V5WlBfqwMtoMJmsr 720w, https://miro.medium.com/v2/resize:fit:750/0*V5WlBfqwMtoMJmsr 750w, https://miro.medium.com/v2/resize:fit:786/0*V5WlBfqwMtoMJmsr 786w, https://miro.medium.com/v2/resize:fit:828/0*V5WlBfqwMtoMJmsr 828w, https://miro.medium.com/v2/resize:fit:1100/0*V5WlBfqwMtoMJmsr 1100w, https://miro.medium.com/v2/resize:fit:1400/0*V5WlBfqwMtoMJmsr 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*V5WlBfqwMtoMJmsr 640w, https://miro.medium.com/v2/resize:fit:720/0*V5WlBfqwMtoMJmsr 720w, https://miro.medium.com/v2/resize:fit:750/0*V5WlBfqwMtoMJmsr 750w, https://miro.medium.com/v2/resize:fit:786/0*V5WlBfqwMtoMJmsr 786w, https://miro.medium.com/v2/resize:fit:828/0*V5WlBfqwMtoMJmsr 828w, https://miro.medium.com/v2/resize:fit:1100/0*V5WlBfqwMtoMJmsr 1100w, https://miro.medium.com/v2/resize:fit:1400/0*V5WlBfqwMtoMJmsr 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*V5WlBfqwMtoMJmsr"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/nzbhf" target="_self">7 Awesome Jupyter Utilities That You Should Be Aware Of</a> by <a style="color:green" href="https://medium.com/u/9ba949960063?source=post_page-----15822cc0cc78--------------------------------" target="_self">Yash Prakash</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Jupyter Notebooks are considered to be the backbone of any data science experiment and for a good reason. They allow for interactive, literate programming that no other platform provides. In this short article, I share a few tips and tricks that I frequently use while coding data science projects in notebooks.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/nzbhf" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*PzuE-xgqIYpTRmMr.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*PzuE-xgqIYpTRmMr.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*PzuE-xgqIYpTRmMr.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*PzuE-xgqIYpTRmMr.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*PzuE-xgqIYpTRmMr.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*PzuE-xgqIYpTRmMr.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*PzuE-xgqIYpTRmMr.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*PzuE-xgqIYpTRmMr.png 640w, https://miro.medium.com/v2/resize:fit:720/0*PzuE-xgqIYpTRmMr.png 720w, https://miro.medium.com/v2/resize:fit:750/0*PzuE-xgqIYpTRmMr.png 750w, https://miro.medium.com/v2/resize:fit:786/0*PzuE-xgqIYpTRmMr.png 786w, https://miro.medium.com/v2/resize:fit:828/0*PzuE-xgqIYpTRmMr.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*PzuE-xgqIYpTRmMr.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*PzuE-xgqIYpTRmMr.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*PzuE-xgqIYpTRmMr.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/7r3gi" target="_self">Fastai Course Chapter 3 Q&A on Linux</a> by <a style="color:green" href="https://medium.com/u/b07fc33d437e?source=post_page-----15822cc0cc78--------------------------------" target="_self">David Littlefield</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The third chapter of the textbook provides an overview of ethical issues that exist in the field of artificial intelligence. It provides cautionary tales, unintended consequences, and ethical considerations. It also covers biases that cause ethical issues and some tools that can help address them.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/7r3gi" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*tfPu7gAQduyd2mSh.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*tfPu7gAQduyd2mSh.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*tfPu7gAQduyd2mSh.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*tfPu7gAQduyd2mSh.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*tfPu7gAQduyd2mSh.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*tfPu7gAQduyd2mSh.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*tfPu7gAQduyd2mSh.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*tfPu7gAQduyd2mSh.png 640w, https://miro.medium.com/v2/resize:fit:720/0*tfPu7gAQduyd2mSh.png 720w, https://miro.medium.com/v2/resize:fit:750/0*tfPu7gAQduyd2mSh.png 750w, https://miro.medium.com/v2/resize:fit:786/0*tfPu7gAQduyd2mSh.png 786w, https://miro.medium.com/v2/resize:fit:828/0*tfPu7gAQduyd2mSh.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*tfPu7gAQduyd2mSh.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*tfPu7gAQduyd2mSh.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*tfPu7gAQduyd2mSh.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/8ayq8" target="_self">Make Your Dashboard Stand Out — Tile Map</a> by <a style="color:green" href="https://medium.com/u/85370dce2b14?source=post_page-----15822cc0cc78--------------------------------" target="_self">Memphis Meng</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">To me, Tableau is the only kind of tool that allows me to do data science as an artist. However, there will be no fun if everyone does the exact visualization with Tableau. This article is one episode of my series “<em>Make Your Dashboard Stand Out,</em>” which provides you with some brilliant but not default visualization ideas. If you are new to me, do check out the following articles…</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/8ayq8" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*ZlwisLvaxWnfdRPY.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*ZlwisLvaxWnfdRPY.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*ZlwisLvaxWnfdRPY.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*ZlwisLvaxWnfdRPY.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*ZlwisLvaxWnfdRPY.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*ZlwisLvaxWnfdRPY.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*ZlwisLvaxWnfdRPY.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*ZlwisLvaxWnfdRPY.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/0*ZlwisLvaxWnfdRPY.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/0*ZlwisLvaxWnfdRPY.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/0*ZlwisLvaxWnfdRPY.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/0*ZlwisLvaxWnfdRPY.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/0*ZlwisLvaxWnfdRPY.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/0*ZlwisLvaxWnfdRPY.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*ZlwisLvaxWnfdRPY.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><a href="https://mktg.best/e9rhw" target="_self">Generating Cool Storylines Using a T5 Transformer and Having Fun</a> by <a style="color:green" href="https://medium.com/u/5d2dda83897?source=post_page-----15822cc0cc78--------------------------------" target="_self">Vatsal Saglani</a></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The folks at Google AI published a paper “Exploring the Limits of Transfer Learning with a Unified Text-To-Text Transformer” and presented an empirical study on what type of pre-training approaches or transfer learning techniques work the best and then used that study to create a new model, i.e., the Text-To-Text Transformer (T5). This transformer model was pre-trained on a much cleaner version of the Common Crawl Corpus, and Google named it the Colossal Clean Crawled Corpus (C4)…</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://mktg.best/e9rhw" target="_self">Read More</a><strong> ]</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://sponsors.towardsai.net/"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Sponsors | Learn How to Become a Sponsor with Towards AI</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Whether you want to highlight your product in a way that compels readers, reach a highly relevant niche audience, or…</h3><p>sponsors.towardsai.net</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://ws.towardsai.net/shop"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Shop ↓ | Towards AI</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Publishing the Best of Tech, Science, and Engineering | Editorial → https://towardsai.net/p/editorial | Subscribe→…</h3><p>ws.towardsai.net</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://members.towardsai.net/"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Join us ↓ | Towards AI Members | The Data-driven Community</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Join Towards AI. By becoming a member, you will not only be supporting Towards AI, but you will have access to…</h3><p>members.towardsai.net</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>🙏 Thank you for being a </strong><a href="https://ws.towardsai.net/subscribe" target="_self">subscriber</a><strong> with </strong><a href="https://towardsai.net/" target="_self">Towards AI</a><strong>! 🙏</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Follow us ↓</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>[ </strong><a href="https://www.facebook.com/towardsAl/" target="_self">Facebook</a><strong> ] |[ </strong><a href="https://twitter.com/towards_ai?lang=en" target="_self">Twitter</a><strong> ]| [ </strong><a href="https://www.instagram.com/towards_ai/" target="_self">Instagram</a><strong> ]| [ </strong><a href="https://www.linkedin.com/company/towards-artificial-intelligence" target="_self">LinkedIn</a><strong> ] | [ </strong><a href="https://github.com/towardsai" target="_self">Github</a><strong> ] | [ </strong><a href="https://news.google.com/publications/CAAqBwgKMNiLmgswgpayAw?oc=3&ceid=US:en" target="_self">Google News</a><strong> ]</strong></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>