<!DOCTYPE html>
                <html>
                <head>
                    <title>How Artificial Intelligence is Accelerating Drug Discovery</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://towardsdatascience.com/how-artificial-intelligence-is-accelerating-drug-discovery-931047f6ea9a"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@george.seif94?source=post_page-----931047f6ea9a--------------------------------">Author : George Seif</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>How Artificial Intelligence is Accelerating Drug Discovery</h3></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*1FlwFNW1ojjdCed1.jpg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*1FlwFNW1ojjdCed1.jpg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*1FlwFNW1ojjdCed1.jpg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*1FlwFNW1ojjdCed1.jpg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*1FlwFNW1ojjdCed1.jpg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*1FlwFNW1ojjdCed1.jpg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*1FlwFNW1ojjdCed1.jpg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*1FlwFNW1ojjdCed1.jpg 640w, https://miro.medium.com/v2/resize:fit:720/0*1FlwFNW1ojjdCed1.jpg 720w, https://miro.medium.com/v2/resize:fit:750/0*1FlwFNW1ojjdCed1.jpg 750w, https://miro.medium.com/v2/resize:fit:786/0*1FlwFNW1ojjdCed1.jpg 786w, https://miro.medium.com/v2/resize:fit:828/0*1FlwFNW1ojjdCed1.jpg 828w, https://miro.medium.com/v2/resize:fit:1100/0*1FlwFNW1ojjdCed1.jpg 1100w, https://miro.medium.com/v2/resize:fit:1400/0*1FlwFNW1ojjdCed1.jpg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*1FlwFNW1ojjdCed1.jpg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://en.wikipedia.org/wiki/Artificial_intelligence" target="_self">Artificial Intelligence</a> (AI) is taking over every industry. We’ve had electricity, we’ve had the internet, and now, we have AI.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">AI in the Modern Age</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The goal of artificial intelligence is to simulate human intelligence using computers. Humans (at least so far) are a lot smarter than computers. We can solve complex problems such as building bridges. We can understand each other’s feelings and emotions just by looking at one’s body language. A computer can’t do that, at least, not with programming it with millions of lines of code.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Computers are great at performing calculations very very quickly. A modern PC or Macbook that you can buy at the mall for $1000 will contain a processor which runs at 3.0 GHz speed. That’s <em>three billion</em> operations per second.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">These days, that computing power is being leveraged to build AI by <em>teaching</em> computers new concepts, just like we can teach humans new skills. Modern AI is <em>data-driven</em>, meaning that the AI builds up its knowledge by consuming data.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">To teach modern AI system what a car looks like, we can show it a few pictures of a car with different models, shapes, and colors. The AI will then <em>learn</em> from these examples the characteristics that make up a car — the shape, the body, the parts, the overall <em>look</em> of the car. When it sees a new car it’ll know what it is since it’s seen something like it before.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This same concept of teaching AI systems by showing it lots of examples is being applied in nearly every modern industry. AI is being trained to look through legal documents, writing out the perfect sales pitch for a potential client, and predict stocks. All we had to do was show the AI a lot of examples of legal documents for various cases, sales pitches to clients, and stock market data for it to learn how to work with it.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">The Science of Drug Discovery</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The field of <a href="https://en.wikipedia.org/wiki/Drug_discovery" target="_self">Drug Discovery</a> involves the search, discovery, and experimentation of new medications. Typically, this can be done in one of two ways:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">(1) Scientifically identifying the active ingredient in natural methods that perform the same function as we want our drug to. For example, the active ingredient in Advil is <a href="https://en.wikipedia.org/wiki/Ibuprofen" target="_self">Ibuprofen</a> which reduces the hormones responsible for causing inflammation and pain in the body</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">(2) Getting lucky. <a href="https://www.healio.com/endocrinology/news/print/endocrine-today/%7B15afd2a1-2084-4ca6-a4e6-7185f5c4cfb0%7D/penicillin-an-accidental-discovery-changed-the-course-of-medicine" target="_self">Penicillin was discovered by accident</a> when Scottish Scientist Alexander Fleming, after coming back from vacation discovered that he had accidentally left a bacteria out in the lab in an open petri dish. When he examined the dish, he found that a perfectly circular mold had formed in the middle of the bacteria, perfectly uncontaminated. That mold was later classified as Penicillin and went on to save millions of lives.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Method (2) of Drug Discovery is nice. We’d love to have such lucky accidents happen to us every day! But method (1) is the only solution we can count on. Doing a real, scientific search for a solution. That’s where AI can help.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Where AI can help Drug Discovery</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">As we all very well know, science can be complicated. Especially so with something as experimental as Drug Discovery. Scientists have a pretty good idea of how different chemicals in the body will react and work together. But with medications, we’re dealing with human bodies where the stakes are a lot higher, and so are the costs associated with experimenting.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A scientist working in Drug Discovery might conduct hundreds of planned and well-calculated experiments over years of work. It starts in the lab where chemicals are tested with other chemicals in something like a petri dish or test tube. Once those tests “pass” the experiments move on to being conducted on rodents — mice and rats usually. Then, on to dogs and chimps. And last but not least, human trials.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">These procedures are rigorous, often taking years to complete. Costs can get into the billions of dollars and there’s a very high chance of failure. A failure at any one of these stages sends us back to ground zero. There are thousands of chemical combinations and much of the work is experimental with some of the basis of success coming from empirical evidence.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Patients in the human trials are often exposed to side effects that cannot be predicted. Even if the trial is successful in the end, it has to go through regulatory approval. It may or may not receive this approval which in the United States comes from the <a href="https://www.fda.gov/home" target="_self">US Food and Drugs Administration</a> (FDA).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Modern AI is particularly effective in applications where there’s a lot of data and / or a lot of repetitive action. That makes Drug Discovery a prime candidate. Lots of test data gathered over the many years and lots of repetitive experiments being conducted.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">One of the most challenging and time-consuming parts of Drug Discovery is, well, the actual discovery. Getting the right chemical compounds in exactly the right proportions is a big challenge. If it can be solved, it can save on years of experimentation, testing, and human trials.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">That’s where most AI for Drug Discovery companies are focused. Using AI to go through combinations of drugs and <em>learn</em> about them. What would make a good drug for this application? A bad one? If I applied this drug in that way, what would happen? In a way, the AI can conduct the exact same experiments that a Scientist normally would, just in a computer simulation. This way, it can go through many experiments in a very short period of time. This is a huge saving on Scientists, and society’s, time, money, and health.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Showcasing AI for Drug Discovery</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://www.atomwise.com/our-technology/" target="_self">Atomwise</a> develops <a href="https://en.wikipedia.org/wiki/Convolutional_neural_network" target="_self">Convolutional Neural Networks</a> (CNNs) to conduct massive experiment-based searches for certain drugs. Developing the right drug for the right application is a delicate balance of making something that is both effective and safe without side-effects. Normally, this requires many experiments and still, we’re not 100% sure that the drug will always be 100% safe. Atomwise effectively moves that work onto the computer and into an AI system by training CNNs to do the experiments automatically. This allows Scientists to conduct far more experiments, millions of them, to select a more reliable subset of drugs that could be feasible.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Notable startups which are similar to Atomwise are <a href="https://www.deepgenomics.com/" target="_self">Deep Genomics</a>, <a href="https://www.schrodinger.com/" target="_self">Schrodinger</a>, and <a href="https://www.recursionpharma.com/" target="_self">Recursion AI</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://www.pathai.com/" target="_self">PathAI</a> is focused on accurate diagnosis of diseases. <a href="https://en.wikipedia.org/wiki/Pathology" target="_self">Pathologists</a> play a very important role in healthcare. They’ll essentially analyze things like tissue samples in order to diagnose it and determine the next course of action, especially in the case of a potential disease being present. Since such a process requires a specialist — the Pathologist, it quickly becomes expensive, time-consuming, and even prone to human error in some cases.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">PathAI’s proposed solution is to train AI to make these kinds of diagnosis. The AI doesn’t even have to be able to perfectly diagnose every single tissue. But what it can do is greatly reduce the workload on Pathologists. Have the AI examine all of the tissue samples. Since it’s being run on a computer, it’s less limited in terms of workload and can do very complex analysis. The AI system can then pass a <strong>subset</strong> of tissue samples, those which are deemed to be “of interest”, and not bother the Pathologist with samples for which it is very confident in its diagnosis. AI can also be trained to point out “areas of interest” within the tissue that it believes the Pathologist should pay extra attention to. All of these really help streamline the process for both Scientists and their patients.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Notable startups which are similar to PathAI are <a href="https://paige.ai/" target="_self">Paige.AI</a> and <a href="https://ibex-ai.com/" target="_self">IBEX</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">There are several startups working on enhancing and optimizing clinical trials, aiming at making the entire process more effective. <a href="https://athelas.com/" target="_self">Athelas</a> is developing a device that analyzes the <a href="https://en.wikipedia.org/wiki/Biomarker_(medicine)" target="_self">biomarkers</a> of cancer from a single drop of blood, allowing for an incredibly quick analysis of the state of the disease. <a href="https://www.imagia.com/2019/" target="_self">Imagia</a>’s software analyzes radiological images in order to predict the progression of a patient’s disease and response to potential treatments. <a href="https://winterlightlabs.com/" target="_self">WinterLight Labs</a> has a system that assesses and monitors cognitive health by analyzing a short speech sample. It can be used to track a patient’s cognitive state throughout clinical trials and experiments.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">For more on companies applying Artificial Intelligence to Drug Discovery, checkout BenchSci’s articles on Drug Discovery <a href="https://blog.benchsci.com/startups-using-artificial-intelligence-in-drug-discovery" target="_self">startups</a> and <a href="https://blog.benchsci.com/pharma-companies-using-artificial-intelligence-in-drug-discovery" target="_self">Pharma companies</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Like to learn?</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Follow me on <a href="https://twitter.com/GeorgeSeif94" target="_self">Twitter</a>, where I post all about the latest and greatest AI, Technology, and Science. I’d love to connect with you on <a href="https://www.linkedin.com/in/georgeseif/" target="_self">LinkedIn</a> too.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Note from Towards Data Science’s editors:</strong><em> While we allow independent authors to publish articles in accordance with our </em><a href="https://medium.com/questions-96667b06af5" target="_self">rules and guidelines</a><em>, we do not endorse each author’s contribution. You should not rely on an author’s works without seeking professional advice. See our </em><a href="https://medium.com/readers-terms-b5d780a700a4" target="_self">Reader Terms</a><em> for details.</em></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>