<!DOCTYPE html>
                <html>
                <head>
                    <title>How to break a CAPTCHA system in 15 minutes with Machine Learning</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/@ageitgey/how-to-break-a-captcha-system-in-15-minutes-with-machine-learning-dbebb035a710"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@ageitgey?source=post_page-----dbebb035a710--------------------------------">Author : Adam Geitgey</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>How to break a CAPTCHA system in 15 minutes with Machine Learning</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5 text-muted">Let’s hack the world’s most popular Wordpress CAPTCHA Plug-in</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Everyone hates CAPTCHAs — those annoying images that contain text you have to type in before you can access a website. CAPTCHAs were designed to prevent computers from automatically filling out forms by verifying that you are a real person. But with the rise of deep learning and computer vision, they can now often be defeated easily.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I’ve been reading the excellent book <a href="https://getdpd.com/cart/hoplink/20252?referrer=1kfcbhtqp2n4oc0" target="_self">Deep Learning for Computer Vision with Python by Adrian Rosebrock</a>. In the book, Adrian walks through how he bypassed the CAPTCHA on the E-ZPass New York website using machine learning:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*4q8hCiIh1amCf2e9fJBQGg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*4q8hCiIh1amCf2e9fJBQGg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*4q8hCiIh1amCf2e9fJBQGg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*4q8hCiIh1amCf2e9fJBQGg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*4q8hCiIh1amCf2e9fJBQGg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*4q8hCiIh1amCf2e9fJBQGg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*4q8hCiIh1amCf2e9fJBQGg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*4q8hCiIh1amCf2e9fJBQGg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*4q8hCiIh1amCf2e9fJBQGg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*4q8hCiIh1amCf2e9fJBQGg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*4q8hCiIh1amCf2e9fJBQGg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*4q8hCiIh1amCf2e9fJBQGg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*4q8hCiIh1amCf2e9fJBQGg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*4q8hCiIh1amCf2e9fJBQGg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*4q8hCiIh1amCf2e9fJBQGg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Adrian didn’t have access to the source code of the application generating the CAPTCHA image. To break the system, he had to download hundreds of example images and manually solve them to train his system.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">But what if we want to break an open source CAPTCHA system where we do have access to the source code?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I went to the <a href="https://wordpress.org/plugins/" target="_self">WordPress.org Plugin Registry</a> and searched for “captcha”. The top result is called “Really Simple CAPTCHA” and has over 1 million active installations:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*3qc-gFTRWmleRXomopMAUQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*3qc-gFTRWmleRXomopMAUQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*3qc-gFTRWmleRXomopMAUQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*3qc-gFTRWmleRXomopMAUQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*3qc-gFTRWmleRXomopMAUQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*3qc-gFTRWmleRXomopMAUQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*3qc-gFTRWmleRXomopMAUQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*3qc-gFTRWmleRXomopMAUQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*3qc-gFTRWmleRXomopMAUQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*3qc-gFTRWmleRXomopMAUQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*3qc-gFTRWmleRXomopMAUQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*3qc-gFTRWmleRXomopMAUQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*3qc-gFTRWmleRXomopMAUQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*3qc-gFTRWmleRXomopMAUQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*3qc-gFTRWmleRXomopMAUQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">And best of all, it comes with source! Since we’ll have the source code that generates the CAPTCHAs, this should be pretty easy to break. To make things a little more challenging, let’s give ourself a time limit. Can we fully break this CAPTCHA system in less than 15 minutes? Let’s try it!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Important note:</strong><em> This is in no way a criticism of the ‘Really Simple CAPTCHA’ plugin or its author. The plugin author himself says that it’s not secure anymore and recommends that you use something else. This is just meant as a fun and quick technical challenge. But if you are one of the remaining 1+ million users, maybe you should switch to something else :)</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">The Challenge</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">To form a plan of attack, let’s see what kinds of images <a href="https://wordpress.org/plugins/really-simple-captcha/" target="_self">Really Simple CAPTCHA</a> generates. On the demo site, we see this:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*WDu1xgEEQuP3tqgC-cPmzA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*WDu1xgEEQuP3tqgC-cPmzA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*WDu1xgEEQuP3tqgC-cPmzA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*WDu1xgEEQuP3tqgC-cPmzA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*WDu1xgEEQuP3tqgC-cPmzA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*WDu1xgEEQuP3tqgC-cPmzA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*WDu1xgEEQuP3tqgC-cPmzA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*WDu1xgEEQuP3tqgC-cPmzA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*WDu1xgEEQuP3tqgC-cPmzA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*WDu1xgEEQuP3tqgC-cPmzA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*WDu1xgEEQuP3tqgC-cPmzA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*WDu1xgEEQuP3tqgC-cPmzA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*WDu1xgEEQuP3tqgC-cPmzA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*WDu1xgEEQuP3tqgC-cPmzA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*WDu1xgEEQuP3tqgC-cPmzA.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">A demo CAPTCHA image</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Ok, so the CAPTCHA images seem to be four letters. Let’s verify that in the PHP source code:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="iframe"><pre>	public function __construct() {
		/* Characters available in images */
		$this->chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

		/* Length of a word in an image */
		$this->char_length = 4;

		/* Array of fonts. Randomly picked up per character */
		$this->fonts = array(
			dirname( __FILE__ ) . '/gentium/GenBkBasR.ttf',
			dirname( __FILE__ ) . '/gentium/GenBkBasI.ttf',
			dirname( __FILE__ ) . '/gentium/GenBkBasBI.ttf',
			dirname( __FILE__ ) . '/gentium/GenBkBasB.ttf',
		);</pre></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Yep, it generates 4-letter CAPTCHAs using a random mix of four different fonts. And we can see that it never uses “O” or “I” in the codes to avoid user confusion. That leaves us with a total of 32 possible letters and numbers that we need to recognize. No problem!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Time elapsed so far: 2 minutes</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Our Toolset</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Before we go any further, let’s mention the tools that we’ll use to solve this problem:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Python 3</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Python is a fun programming language with great libraries for machine learning and computer vision.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>OpenCV</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">OpenCV is a popular framework for computer vision and image processing. We’ll use OpenCV to process the CAPTCHA images. It has a Python API so we can use it directly from Python.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Keras</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Keras is a deep learning framework written in Python. It makes it easy to define, train and use deep neural networks with minimal coding.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>TensorFlow</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">TensorFlow is Google’s library for machine learning. We’ll be coding in Keras, but Keras doesn’t actually implement the neural network logic itself. Instead, it uses Google’s TensorFlow library behind the scenes to do the heavy lifting.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Ok, back to the challenge!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Creating our Dataset</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">To train any machine learning system, we need training data. To break a CAPTCHA system, we want training data that looks like this:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*dC78m_XpcZmuaV_GlnAh5g.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*dC78m_XpcZmuaV_GlnAh5g.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*dC78m_XpcZmuaV_GlnAh5g.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*dC78m_XpcZmuaV_GlnAh5g.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*dC78m_XpcZmuaV_GlnAh5g.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*dC78m_XpcZmuaV_GlnAh5g.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*dC78m_XpcZmuaV_GlnAh5g.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*dC78m_XpcZmuaV_GlnAh5g.png 640w, https://miro.medium.com/v2/resize:fit:720/1*dC78m_XpcZmuaV_GlnAh5g.png 720w, https://miro.medium.com/v2/resize:fit:750/1*dC78m_XpcZmuaV_GlnAh5g.png 750w, https://miro.medium.com/v2/resize:fit:786/1*dC78m_XpcZmuaV_GlnAh5g.png 786w, https://miro.medium.com/v2/resize:fit:828/1*dC78m_XpcZmuaV_GlnAh5g.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*dC78m_XpcZmuaV_GlnAh5g.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*dC78m_XpcZmuaV_GlnAh5g.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*dC78m_XpcZmuaV_GlnAh5g.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Since we have the source code to the WordPress plug-in, we can modify it to save out 10,000 CAPTCHA images along with the expected answer for each image.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">After a couple of minutes of hacking on the code and adding a simple <em>‘for’</em> loop, I had a folder with training data — 10,000 PNG files with the correct answer for each as the filename:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*leaOO0EYbgKVl7MEhflIFA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*leaOO0EYbgKVl7MEhflIFA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*leaOO0EYbgKVl7MEhflIFA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*leaOO0EYbgKVl7MEhflIFA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*leaOO0EYbgKVl7MEhflIFA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*leaOO0EYbgKVl7MEhflIFA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*leaOO0EYbgKVl7MEhflIFA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*leaOO0EYbgKVl7MEhflIFA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*leaOO0EYbgKVl7MEhflIFA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*leaOO0EYbgKVl7MEhflIFA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*leaOO0EYbgKVl7MEhflIFA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*leaOO0EYbgKVl7MEhflIFA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*leaOO0EYbgKVl7MEhflIFA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*leaOO0EYbgKVl7MEhflIFA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*leaOO0EYbgKVl7MEhflIFA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This is the only part where I won’t give you working example code. We’re doing this for education and I don’t want you to actually go out and spam real WordPress sites. However I will give you the 10,000 images I generated at the end so that you can replicate my results.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Time elapsed so far: 5 minutes</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Simplifying the Problem</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now that we have our training data, we <em>could</em> use it directly to train a neural network:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Ufp_x7c1tf9nkPd9htdDjA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ufp_x7c1tf9nkPd9htdDjA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Ufp_x7c1tf9nkPd9htdDjA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Ufp_x7c1tf9nkPd9htdDjA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Ufp_x7c1tf9nkPd9htdDjA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Ufp_x7c1tf9nkPd9htdDjA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Ufp_x7c1tf9nkPd9htdDjA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Ufp_x7c1tf9nkPd9htdDjA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Ufp_x7c1tf9nkPd9htdDjA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Ufp_x7c1tf9nkPd9htdDjA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Ufp_x7c1tf9nkPd9htdDjA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Ufp_x7c1tf9nkPd9htdDjA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Ufp_x7c1tf9nkPd9htdDjA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*Ufp_x7c1tf9nkPd9htdDjA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*Ufp_x7c1tf9nkPd9htdDjA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">With enough training data, this approach might even work — but we can make the problem a lot simpler to solve. The simpler the problem, the less training data and the less computational power we’ll need to solve it. We’ve only got 15 minutes after all!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Luckily the CAPTCHA images are always made up of only four letters. If we can somehow split the image apart so that that each letter is a separate image, then we only have to train the neural network to recognize a single letter at a time:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*4ScTIDYJ6rPCAtopRulzOg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*4ScTIDYJ6rPCAtopRulzOg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*4ScTIDYJ6rPCAtopRulzOg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*4ScTIDYJ6rPCAtopRulzOg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*4ScTIDYJ6rPCAtopRulzOg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*4ScTIDYJ6rPCAtopRulzOg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*4ScTIDYJ6rPCAtopRulzOg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*4ScTIDYJ6rPCAtopRulzOg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*4ScTIDYJ6rPCAtopRulzOg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*4ScTIDYJ6rPCAtopRulzOg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*4ScTIDYJ6rPCAtopRulzOg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*4ScTIDYJ6rPCAtopRulzOg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*4ScTIDYJ6rPCAtopRulzOg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*4ScTIDYJ6rPCAtopRulzOg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*4ScTIDYJ6rPCAtopRulzOg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I don’t have time to go through 10,000 training images and manually split them up into separate images in Photoshop. That would take days and I’ve only got 10 minutes left. And we can’t just split the images into four equal-size chunks because the CAPTCHA randomly places the letters in different horizontal locations to prevent that:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:38%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 300px" srcset="https://miro.medium.com/v2/resize:fit:640/1*yyfjNSCKt8IvY7JqANnOZg.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*yyfjNSCKt8IvY7JqANnOZg.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*yyfjNSCKt8IvY7JqANnOZg.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*yyfjNSCKt8IvY7JqANnOZg.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*yyfjNSCKt8IvY7JqANnOZg.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*yyfjNSCKt8IvY7JqANnOZg.gif 1100w, https://miro.medium.com/v2/resize:fit:600/1*yyfjNSCKt8IvY7JqANnOZg.gif 600w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 300px" srcset="https://miro.medium.com/v2/resize:fit:640/1*yyfjNSCKt8IvY7JqANnOZg.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*yyfjNSCKt8IvY7JqANnOZg.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*yyfjNSCKt8IvY7JqANnOZg.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*yyfjNSCKt8IvY7JqANnOZg.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*yyfjNSCKt8IvY7JqANnOZg.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*yyfjNSCKt8IvY7JqANnOZg.gif 1100w, https://miro.medium.com/v2/resize:fit:600/1*yyfjNSCKt8IvY7JqANnOZg.gif 600w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/300/1*yyfjNSCKt8IvY7JqANnOZg.gif"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">The letters in each image are randomly placed to make it a little more difficult to split apart the image.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Luckily, we can still automate this. In image processing, we often need to detect “blobs” of pixels that have the same color. The boundaries around those continuous pixels blobs are called <em>contours</em>. OpenCV has a built-in <em>findContours()</em> function that we can use to detect these continuous regions.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So we’ll start with a raw CAPTCHA image:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:67%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*EgwdO6bSUFYPTU8m4oIf4A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*EgwdO6bSUFYPTU8m4oIf4A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*EgwdO6bSUFYPTU8m4oIf4A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*EgwdO6bSUFYPTU8m4oIf4A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*EgwdO6bSUFYPTU8m4oIf4A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*EgwdO6bSUFYPTU8m4oIf4A.png 1100w, https://miro.medium.com/v2/resize:fit:1000/format:webp/1*EgwdO6bSUFYPTU8m4oIf4A.png 1000w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*EgwdO6bSUFYPTU8m4oIf4A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*EgwdO6bSUFYPTU8m4oIf4A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*EgwdO6bSUFYPTU8m4oIf4A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*EgwdO6bSUFYPTU8m4oIf4A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*EgwdO6bSUFYPTU8m4oIf4A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*EgwdO6bSUFYPTU8m4oIf4A.png 1100w, https://miro.medium.com/v2/resize:fit:1000/1*EgwdO6bSUFYPTU8m4oIf4A.png 1000w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/500/1*EgwdO6bSUFYPTU8m4oIf4A.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">And then we’ll convert the image into pure black and white (this is called t<em>hresholding</em>) so that it will be easy to find the continuous regions:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:67%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*NMEsX6kq5sFqHpnCsg6nXg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*NMEsX6kq5sFqHpnCsg6nXg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*NMEsX6kq5sFqHpnCsg6nXg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*NMEsX6kq5sFqHpnCsg6nXg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*NMEsX6kq5sFqHpnCsg6nXg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*NMEsX6kq5sFqHpnCsg6nXg.png 1100w, https://miro.medium.com/v2/resize:fit:1000/format:webp/1*NMEsX6kq5sFqHpnCsg6nXg.png 1000w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*NMEsX6kq5sFqHpnCsg6nXg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*NMEsX6kq5sFqHpnCsg6nXg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*NMEsX6kq5sFqHpnCsg6nXg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*NMEsX6kq5sFqHpnCsg6nXg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*NMEsX6kq5sFqHpnCsg6nXg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*NMEsX6kq5sFqHpnCsg6nXg.png 1100w, https://miro.medium.com/v2/resize:fit:1000/1*NMEsX6kq5sFqHpnCsg6nXg.png 1000w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/500/1*NMEsX6kq5sFqHpnCsg6nXg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Next, we’ll use OpenCV’s <em>findContours()</em> function to detect the separate parts of the image that contain continuous blobs of pixels of the same color:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:67%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*CFJkKt857-9qv8PJBqe8JA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*CFJkKt857-9qv8PJBqe8JA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*CFJkKt857-9qv8PJBqe8JA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*CFJkKt857-9qv8PJBqe8JA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*CFJkKt857-9qv8PJBqe8JA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*CFJkKt857-9qv8PJBqe8JA.png 1100w, https://miro.medium.com/v2/resize:fit:1000/format:webp/1*CFJkKt857-9qv8PJBqe8JA.png 1000w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*CFJkKt857-9qv8PJBqe8JA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*CFJkKt857-9qv8PJBqe8JA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*CFJkKt857-9qv8PJBqe8JA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*CFJkKt857-9qv8PJBqe8JA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*CFJkKt857-9qv8PJBqe8JA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*CFJkKt857-9qv8PJBqe8JA.png 1100w, https://miro.medium.com/v2/resize:fit:1000/1*CFJkKt857-9qv8PJBqe8JA.png 1000w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/500/1*CFJkKt857-9qv8PJBqe8JA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Then it’s just a simple matter of saving each region out as a separate image file. And since we know each image should contain four letters from left-to-right, we can use that knowledge to label the letters as we save them. As long as we save them out in that order, we should be saving each image letter with the proper letter name.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">But wait — I see a problem! Sometimes the CAPTCHAs have overlapping letters like this:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:67%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*h0yC3aLQU1as2HnogUXjVQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*h0yC3aLQU1as2HnogUXjVQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*h0yC3aLQU1as2HnogUXjVQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*h0yC3aLQU1as2HnogUXjVQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*h0yC3aLQU1as2HnogUXjVQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*h0yC3aLQU1as2HnogUXjVQ.png 1100w, https://miro.medium.com/v2/resize:fit:1000/format:webp/1*h0yC3aLQU1as2HnogUXjVQ.png 1000w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*h0yC3aLQU1as2HnogUXjVQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*h0yC3aLQU1as2HnogUXjVQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*h0yC3aLQU1as2HnogUXjVQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*h0yC3aLQU1as2HnogUXjVQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*h0yC3aLQU1as2HnogUXjVQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*h0yC3aLQU1as2HnogUXjVQ.png 1100w, https://miro.medium.com/v2/resize:fit:1000/1*h0yC3aLQU1as2HnogUXjVQ.png 1000w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/500/1*h0yC3aLQU1as2HnogUXjVQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">That means that we’ll end up extracting regions that mash together two letters as one region:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:67%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*CaBtSHUmQ77E8zNi0C7wMQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*CaBtSHUmQ77E8zNi0C7wMQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*CaBtSHUmQ77E8zNi0C7wMQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*CaBtSHUmQ77E8zNi0C7wMQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*CaBtSHUmQ77E8zNi0C7wMQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*CaBtSHUmQ77E8zNi0C7wMQ.png 1100w, https://miro.medium.com/v2/resize:fit:1000/format:webp/1*CaBtSHUmQ77E8zNi0C7wMQ.png 1000w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*CaBtSHUmQ77E8zNi0C7wMQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*CaBtSHUmQ77E8zNi0C7wMQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*CaBtSHUmQ77E8zNi0C7wMQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*CaBtSHUmQ77E8zNi0C7wMQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*CaBtSHUmQ77E8zNi0C7wMQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*CaBtSHUmQ77E8zNi0C7wMQ.png 1100w, https://miro.medium.com/v2/resize:fit:1000/1*CaBtSHUmQ77E8zNi0C7wMQ.png 1000w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/500/1*CaBtSHUmQ77E8zNi0C7wMQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If we don’t handle this problem, we’ll end up creating bad training data. We need to fix this so that we don’t accidentally teach the machine to recognize those two squashed-together letters as one letter.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A simple hack here is to say that if a single contour area is a lot wider than it is tall, that means we probably have two letters squished together. In that case, we can just split the conjoined letter in half down the middle and treat it as two separate letters:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:67%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*ehE02z5AzBv1zt3UExB2_w.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*ehE02z5AzBv1zt3UExB2_w.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*ehE02z5AzBv1zt3UExB2_w.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*ehE02z5AzBv1zt3UExB2_w.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*ehE02z5AzBv1zt3UExB2_w.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ehE02z5AzBv1zt3UExB2_w.png 1100w, https://miro.medium.com/v2/resize:fit:1000/format:webp/1*ehE02z5AzBv1zt3UExB2_w.png 1000w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*ehE02z5AzBv1zt3UExB2_w.png 640w, https://miro.medium.com/v2/resize:fit:720/1*ehE02z5AzBv1zt3UExB2_w.png 720w, https://miro.medium.com/v2/resize:fit:750/1*ehE02z5AzBv1zt3UExB2_w.png 750w, https://miro.medium.com/v2/resize:fit:786/1*ehE02z5AzBv1zt3UExB2_w.png 786w, https://miro.medium.com/v2/resize:fit:828/1*ehE02z5AzBv1zt3UExB2_w.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*ehE02z5AzBv1zt3UExB2_w.png 1100w, https://miro.medium.com/v2/resize:fit:1000/1*ehE02z5AzBv1zt3UExB2_w.png 1000w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/500/1*ehE02z5AzBv1zt3UExB2_w.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">We’ll split any regions that are much wider than they are tall in half and treat it as two letters. It’s hacky, but it works fine for these CAPTCHAs.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now that we have a way to extract individual letters, let’s run it across all the CAPTCHA images we have. The goal is to collect different variations of each letter. We can save each letter in it’s own folder to keep things organized.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Here’s a picture of what my “W” folder looked like after I extracted all the letters:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*jtp8JImlEe11ViiqqFoTvg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*jtp8JImlEe11ViiqqFoTvg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*jtp8JImlEe11ViiqqFoTvg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*jtp8JImlEe11ViiqqFoTvg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*jtp8JImlEe11ViiqqFoTvg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*jtp8JImlEe11ViiqqFoTvg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*jtp8JImlEe11ViiqqFoTvg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*jtp8JImlEe11ViiqqFoTvg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*jtp8JImlEe11ViiqqFoTvg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*jtp8JImlEe11ViiqqFoTvg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*jtp8JImlEe11ViiqqFoTvg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*jtp8JImlEe11ViiqqFoTvg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*jtp8JImlEe11ViiqqFoTvg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*jtp8JImlEe11ViiqqFoTvg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*jtp8JImlEe11ViiqqFoTvg.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Some of the “W” letters extracted from our 10,000 CAPTCHA images. I ended up with 1,147 different “W” images.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Time elapsed so far: 10 minutes</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Building and Training the Neural Network</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Since we only need to recognize images of single letters and numbers, we don’t need a very complex neural network architecture. Recognizing letters is a much easier problem than recognizing complex images like pictures like cats and dogs.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We’ll use a simple convolutional neural network architecture with two convolutional layers and two fully-connected layers:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*4AZO0vgnZXnlEgQZYeJ2EQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*4AZO0vgnZXnlEgQZYeJ2EQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you want to know more about how convolutional neural networks work and why they are ideal for image recognition, check out <a href="https://getdpd.com/cart/hoplink/20252?referrer=1kfcbhtqp2n4oc0" target="_self">Adrian’s book</a> or <a href="https://medium.com/@ageitgey/machine-learning-is-fun-part-3-deep-learning-and-convolutional-neural-networks-f40359318721" target="_self">my previous article</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Defining this neural network architecture only takes a few lines of code using Keras:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now we can train it!</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">After 10 passes over the training data set, we hit nearly 100% accuracy. At this point, we should be able to automatically bypass this CAPTCHA whenever we want! We did it!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Time elapsed: 15 minutes (whew!)</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Using the Trained Model to Solve CAPTCHAs</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now that we have a trained neural network, using it to break a real CAPTCHA is pretty simple:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;">Grab a real CAPTCHA image from a website that uses this WordPress plugin.</li><li class="ff3" style="font-size:22px;">Break up the CAPTCHA image into four separate letter images using the same approach we used to create the training dataset.</li><li class="ff3" style="font-size:22px;">Ask our neural network to make a separate prediction for each letter image.</li><li class="ff3" style="font-size:22px;">Use the four predicted letters as the answer to the CAPTCHA.</li><li class="ff3" style="font-size:22px;">Hijinks ensue!</li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Here’s how our model looks decoding real CAPTCHAs:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:67%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*L6scb0B2nCirZ_ZLyuONPg.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*L6scb0B2nCirZ_ZLyuONPg.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*L6scb0B2nCirZ_ZLyuONPg.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*L6scb0B2nCirZ_ZLyuONPg.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*L6scb0B2nCirZ_ZLyuONPg.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*L6scb0B2nCirZ_ZLyuONPg.gif 1100w, https://miro.medium.com/v2/resize:fit:1000/1*L6scb0B2nCirZ_ZLyuONPg.gif 1000w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*L6scb0B2nCirZ_ZLyuONPg.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*L6scb0B2nCirZ_ZLyuONPg.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*L6scb0B2nCirZ_ZLyuONPg.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*L6scb0B2nCirZ_ZLyuONPg.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*L6scb0B2nCirZ_ZLyuONPg.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*L6scb0B2nCirZ_ZLyuONPg.gif 1100w, https://miro.medium.com/v2/resize:fit:1000/1*L6scb0B2nCirZ_ZLyuONPg.gif 1000w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/500/1*L6scb0B2nCirZ_ZLyuONPg.gif"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Or from the command line:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:83%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 615px" srcset="https://miro.medium.com/v2/resize:fit:640/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 1100w, https://miro.medium.com/v2/resize:fit:1230/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 1230w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 615px" srcset="https://miro.medium.com/v2/resize:fit:640/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 640w, https://miro.medium.com/v2/resize:fit:720/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 720w, https://miro.medium.com/v2/resize:fit:750/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 750w, https://miro.medium.com/v2/resize:fit:786/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 786w, https://miro.medium.com/v2/resize:fit:828/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 828w, https://miro.medium.com/v2/resize:fit:1100/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 1100w, https://miro.medium.com/v2/resize:fit:1230/1*7RE-Ql6jaDu1jCfi0OgtTw.gif 1230w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/615/1*7RE-Ql6jaDu1jCfi0OgtTw.gif"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Try it out!</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you want to try this yourself, you can <a href="https://s3-us-west-2.amazonaws.com/mlif-example-code/solving_captchas_code_examples.zip" target="_self">grab the code here</a>. It includes the 10,000 sample images and all the code for each step in this article. Check out the included README.md file for instructions on how to run it.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Update May 2, 2019:</strong><em> OpenCV 4 changed the API of one of the functions used in the code. If you are using OpenCV 4, you need to change one line in the example code:</em></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="iframe"><pre><span><em># Change this line:<br/></em><em>contours = contours[0] if imutils.is_cv2() else contours[1]</em></span><span><em># To this:<br/>contours = contours[1] if imutils.is_cv3() else contours[0]</em></span></pre></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">But if you want to learn what every line of the code does, I highly recommend grabbing a copy of <a href="https://getdpd.com/cart/hoplink/20252?referrer=1kfcbhtqp2n4oc0" target="_self">Deep Learning for Computer Vision with Python</a>. It goes into a lot more detail and has tons of detailed examples. It’s the only book I’ve seen so far that covers both <em>how things work</em> and how to<em> actually use them in the real world</em> <em>to solve difficult problems</em>. Check it out!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you liked this article, consider signing up for my Machine Learning is Fun! newsletter:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">You can also follow me on Twitter at <a href="https://twitter.com/ageitgey" target="_self">@ageitgey</a>, <a href="mailto:ageitgey@gmail.com" target="_self">email me directly</a> or <a href="https://www.linkedin.com/in/ageitgey" target="_self">find me on linkedin</a>. I’d love to hear from you if I can help you or your team with machine learning.</p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>