<!DOCTYPE html>
                <html>
                <head>
                    <title>How Serious is Big Pharma About AI in Drug Discovery?</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/@longevity/how-serious-is-big-pharma-about-ai-in-drug-discovery-f4cfe23cfe85"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@longevity?source=post_page-----f4cfe23cfe85--------------------------------">Author : Alex Zhavoronkov, PhD</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>How Serious is Big Pharma About AI in Drug Discovery?</h3></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*6w1JY1Uw3vZkx-WKvL9ntw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*6w1JY1Uw3vZkx-WKvL9ntw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*6w1JY1Uw3vZkx-WKvL9ntw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*6w1JY1Uw3vZkx-WKvL9ntw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*6w1JY1Uw3vZkx-WKvL9ntw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*6w1JY1Uw3vZkx-WKvL9ntw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*6w1JY1Uw3vZkx-WKvL9ntw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*6w1JY1Uw3vZkx-WKvL9ntw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*6w1JY1Uw3vZkx-WKvL9ntw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*6w1JY1Uw3vZkx-WKvL9ntw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*6w1JY1Uw3vZkx-WKvL9ntw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*6w1JY1Uw3vZkx-WKvL9ntw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*6w1JY1Uw3vZkx-WKvL9ntw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*6w1JY1Uw3vZkx-WKvL9ntw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*6w1JY1Uw3vZkx-WKvL9ntw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I am not trying to be critical here, we love Big Pharma companies and explore the various strategies to work with them. Some of the best biostats scientists I know are working for the pharma companies. This year to date I presented at 64 conferences, workshops and pharma events and my team published over 20 research papers and presented at over 100 conferences. But one of the events which captivated us for the entire year is NeurIPS. It is a great place to meet the many friends in one place and it is the #1 event in AI. To quote VentureBeat:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*m2aWuvz1kw3VhM0DpSC_kQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*m2aWuvz1kw3VhM0DpSC_kQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*m2aWuvz1kw3VhM0DpSC_kQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*m2aWuvz1kw3VhM0DpSC_kQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*m2aWuvz1kw3VhM0DpSC_kQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*m2aWuvz1kw3VhM0DpSC_kQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*m2aWuvz1kw3VhM0DpSC_kQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*m2aWuvz1kw3VhM0DpSC_kQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*m2aWuvz1kw3VhM0DpSC_kQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*m2aWuvz1kw3VhM0DpSC_kQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*m2aWuvz1kw3VhM0DpSC_kQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*m2aWuvz1kw3VhM0DpSC_kQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*m2aWuvz1kw3VhM0DpSC_kQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*m2aWuvz1kw3VhM0DpSC_kQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*m2aWuvz1kw3VhM0DpSC_kQ.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;"><a href="https://venturebeat.com/2018/11/23/ai-weekly-what-to-expect-at-neurips-2018-the-biggest-ai-conference-of-the-year/" target="_self">Venture Beat</a></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Sponsorships were gone almost immediately. Even the $80K+sponsorships.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Every AI company is here and a couple of AI companies. Benevolent AI also has a nice booth. They hired Marwin Segler, the young pharma AI superstar, who is doing very respectable work there and started a program in generative chemistry and who brought a lot of credibility to the company’s AI efforts. No doubt every pharma would like to hire him now to kick-start their AI programs. I did not see the other pharma AI companies on the floor with a booth.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">But the pharma industry is way under-represented. Out of curiosity, I did a quick search using the official Whova app to see who from the pharma industry is here. A few stats:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">GSK — 4<br></br>Merck KGA — 4<br></br>Novartis — 2 <br></br>Genentech — 2<br></br>Roche -1 <br></br>Roche Diagnostics — 1<br></br>Merck — 1<br></br>Pfizer — 1<br></br>AstraZeneca — 1<br></br>Johnson & Johnson / Janssen — 0<br></br>Bayer — 0 <br></br>Lilly — 0 <br></br>Sanofi — 0 <br></br>Abbvie — 0<br></br>Amgen — 0<br></br>Gilead — 0</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">17 people from Big Pharma are in attendance at NeurIPS. I am not being critical here but it shows the level of interest and expertise. There are fewer delegates from pharma then Googlers whose family names start with “C”.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I was happy to see Sean Grullon and Laura Acquialanga from GSK in the poster area and Jian Dai from Genentech at our workshop at NeurIPS Expo yesterday. <br></br>WuXi AppTech’s strategic investment team has a strong presence speaking to every company in the Expo area. They invested in Insilico and at least 4 other companies in the AI space that I know of. They are probably the most active investor building an ecosystem for AI-powered biology and chemistry to maximize the value for their research platform partners.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">It may be a good idea for the pharma companies to send a few more data scientists to the ICML and NeurIPS next year. And I feel that this post will help prioritize these conferences in pharma…</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">And for all my friends reading this message, check out the latest episode of our favorite youtube channel. You will love it:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:80%;"><iframe  scrolling="auto" width="854.0" height="480.0" frameborder="0" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FCIDRdLOWrXQ%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCIDRdLOWrXQ&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FCIDRdLOWrXQ%2Fhqdefault.jpg&key=a19fcc184b9711e1b4764040d3dc5c07&type=text%2Fhtml&schema=youtube" allowfullscreen=""></iframe></div><br><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">2-minute Papers with Károly Zsolnai-Fehér</p><br></div></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>