<!DOCTYPE html>
                <html>
                <head>
                    <title>Introducing TensorFlow.js: Machine Learning in Javascript</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/tensorflow/introducing-tensorflow-js-machine-learning-in-javascript-bf3eab376db"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@tensorflow?source=post_page-----bf3eab376db--------------------------------">Author : TensorFlow</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Introducing TensorFlow.js: Machine Learning in Javascript</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Posted by </em><a href="http://twitter.com/random_forests" target="_self">Josh Gordon</a><em> and </em><a href="http://twitter.com/srobTweets" target="_self">Sara Robinson</a><em>, Developer Advocates</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We’re excited to introduce <a href="https://js.tensorflow.org" target="_self">TensorFlow.js</a>, an open-source library you can use to define, train, and run machine learning models entirely in the browser, using Javascript and a high-level layers API. If you’re a Javascript developer who’s new to ML, TensorFlow.js is a great way to begin learning. Or, if you’re a ML developer who’s new to Javascript, read on to learn more about new opportunities for in-browser ML. In this post, we’ll give you a quick overview of TensorFlow.js, and getting started resources you can use to try it out.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">In-Browser ML</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Running machine learning programs entirely client-side in the browser unlocks new opportunities, like interactive ML! If you’re watching the <a href="https://www.youtube.com/tensorflow" target="_self">livestream</a> for the <a href="https://www.tensorflow.org/dev-summit/" target="_self">TensorFlow Developer Summit</a>, during the TensorFlow.js talk you’ll find a demo where <a href="http://twitter.com/dsmilkov" target="_self">@dsmilkov</a> and <a href="http://twitter.com/nsthorat" target="_self">@nsthorat</a> train a model to control a PAC-MAN game using computer vision and a webcam, entirely in the browser. You can try it out yourself, too, with the link below — and find the source in the <a href="https://github.com/tensorflow/tfjs-examples" target="_self">examples</a> folder.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*hfplSJ9gMJCjluG-. 640w, https://miro.medium.com/v2/resize:fit:720/0*hfplSJ9gMJCjluG-. 720w, https://miro.medium.com/v2/resize:fit:750/0*hfplSJ9gMJCjluG-. 750w, https://miro.medium.com/v2/resize:fit:786/0*hfplSJ9gMJCjluG-. 786w, https://miro.medium.com/v2/resize:fit:828/0*hfplSJ9gMJCjluG-. 828w, https://miro.medium.com/v2/resize:fit:1100/0*hfplSJ9gMJCjluG-. 1100w, https://miro.medium.com/v2/resize:fit:1400/0*hfplSJ9gMJCjluG-. 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*hfplSJ9gMJCjluG-. 640w, https://miro.medium.com/v2/resize:fit:720/0*hfplSJ9gMJCjluG-. 720w, https://miro.medium.com/v2/resize:fit:750/0*hfplSJ9gMJCjluG-. 750w, https://miro.medium.com/v2/resize:fit:786/0*hfplSJ9gMJCjluG-. 786w, https://miro.medium.com/v2/resize:fit:828/0*hfplSJ9gMJCjluG-. 828w, https://miro.medium.com/v2/resize:fit:1100/0*hfplSJ9gMJCjluG-. 1100w, https://miro.medium.com/v2/resize:fit:1400/0*hfplSJ9gMJCjluG-. 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*hfplSJ9gMJCjluG-."></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;"><em>Turn your webcam into a controller for PAC-MAN </em><a href="https://storage.googleapis.com/tfjs-examples/webcam-transfer-learning/dist/index.html" target="_self">using a Neural Network</a><em>.</em></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you’d like to try another game, give the <a href="https://emojiscavengerhunt.withgoogle.com/" target="_self">Emoji Scavenger Hunt</a> a whirl — this time, from a browser on your mobile phone.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*33Y-pYAmL5D1WFYK. 640w, https://miro.medium.com/v2/resize:fit:720/0*33Y-pYAmL5D1WFYK. 720w, https://miro.medium.com/v2/resize:fit:750/0*33Y-pYAmL5D1WFYK. 750w, https://miro.medium.com/v2/resize:fit:786/0*33Y-pYAmL5D1WFYK. 786w, https://miro.medium.com/v2/resize:fit:828/0*33Y-pYAmL5D1WFYK. 828w, https://miro.medium.com/v2/resize:fit:1100/0*33Y-pYAmL5D1WFYK. 1100w, https://miro.medium.com/v2/resize:fit:1400/0*33Y-pYAmL5D1WFYK. 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*33Y-pYAmL5D1WFYK. 640w, https://miro.medium.com/v2/resize:fit:720/0*33Y-pYAmL5D1WFYK. 720w, https://miro.medium.com/v2/resize:fit:750/0*33Y-pYAmL5D1WFYK. 750w, https://miro.medium.com/v2/resize:fit:786/0*33Y-pYAmL5D1WFYK. 786w, https://miro.medium.com/v2/resize:fit:828/0*33Y-pYAmL5D1WFYK. 828w, https://miro.medium.com/v2/resize:fit:1100/0*33Y-pYAmL5D1WFYK. 1100w, https://miro.medium.com/v2/resize:fit:1400/0*33Y-pYAmL5D1WFYK. 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*33Y-pYAmL5D1WFYK."></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;"><em>The </em><a href="https://emojiscavengerhunt.withgoogle.com/" target="_self">Emoji Scavenger Hunt</a><em> is another fun example of an application built using TensorFlow.js. Try it using your phone, and find the source </em><a href="https://github.com/google/emoji-scavenger-hunt" target="_self">here</a><em>.</em></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">ML running in the browser means that from a user’s perspective, there’s no need to install any libraries or drivers. Just open a webpage, and your program is ready to run. In addition, it’s ready to run with GPU acceleration. TensorFlow.js automatically supports WebGL, and will accelerate your code behind the scenes when a GPU is available. <mark>Users may also open your webpage from a mobile device, in which case your model can take advantage of sensor data, say from a gyroscope or accelerometer.</mark> Finally, all data stays on the client, making TensorFlow.js useful for low-latency inference, as well as for privacy preserving applications.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">What can you do with TensorFlow.js?</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you’re developing with TensorFlow.js, here are three workflows you can consider.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ul><li class="ff3" style="font-size:22px;"><strong>You can import an existing, pre-trained model for inference. </strong>If you have an existing TensorFlow or <a href="http://keras.io" target="_self">Keras</a> model you’ve previously trained offline, you can convert into TensorFlow.js format, and load it into the browser for inference.</li><li class="ff3" style="font-size:22px;"><strong>You can re-train an imported model. </strong>As in the Pac-Man demo above, you can use transfer learning to augment an existing model trained offline using a small amount of data collected in the browser using a technique called Image Retraining. This is one way to train an accurate model quickly, using only a small amount of data.</li><li class="ff3" style="font-size:22px;"><strong>Author models directly in browser. </strong>You can also use TensorFlow.js to define, train, and run models entirely in the browser using Javascript and a high-level layers API. If you’re familiar with <a href="http://keras.io" target="_self">Keras</a>, the high-level layers API should feel familiar.</li></ul></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Let’s see some code</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you like, you can head directly to the <a href="https://github.com/tensorflow/tfjs-examples" target="_self">samples</a> or <a href="http://js.tensorflow.org" target="_self">tutorials</a> to get started. These show how-to export a model defined in Python for inference in the browser, as well as how to define and train models entirely in Javascript. As a quick preview, here’s a snippet of code that defines a neural network to classify flowers, much like on the getting started <a href="https://www.tensorflow.org/get_started/" target="_self">guide</a> on TensorFlow.org. Here, we’ll define a model using a stack of layers.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="iframe"><pre>import * as tf from ‘@tensorflow/tfjs’;
const model = tf.sequential();
model.add(tf.layers.dense({inputShape: [4], units: 100}));
model.add(tf.layers.dense({units: 4}));
model.compile({loss: ‘categoricalCrossentropy’, optimizer: ‘sgd’});</pre></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The layers API we’re using here supports all of the Keras layers found in the examples <a href="https://github.com/keras-team/keras/tree/master/examples" target="_self">directory</a> (including Dense, CNN, LSTM, and so on). We can then train our model using the same Keras-compatible API with a method call:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="iframe"><pre>await model.fit(
  xData, yData, {
    batchSize: batchSize,
    epochs: epochs
});</pre></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The model is now ready to use to make predictions:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="iframe"><pre>// Get measurements for a new flower to generate a prediction
// The first argument is the data, and the second is the shape.
const inputData = tf.tensor2d([[4.8, 3.0, 1.4, 0.1]], [1, 4]);

// Get the highest confidence prediction from our model
const result = model.predict(inputData);
const winner = irisClasses[result.argMax().dataSync()[0]];

// Display the winner
console.log(winner);</pre></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">TensorFlow.js also includes a low-level API (previously <a href="https://deeplearnjs.org/" target="_self">deeplearn.js</a>) and support for <a href="https://github.com/tensorflow/tensorflow/tree/r1.7/tensorflow/contrib/eager" target="_self">Eager execution</a>. You can learn more about these by watching the talk at the TensorFlow Developer Summit.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*oY2OG7MFBN4eK1AN. 640w, https://miro.medium.com/v2/resize:fit:720/0*oY2OG7MFBN4eK1AN. 720w, https://miro.medium.com/v2/resize:fit:750/0*oY2OG7MFBN4eK1AN. 750w, https://miro.medium.com/v2/resize:fit:786/0*oY2OG7MFBN4eK1AN. 786w, https://miro.medium.com/v2/resize:fit:828/0*oY2OG7MFBN4eK1AN. 828w, https://miro.medium.com/v2/resize:fit:1100/0*oY2OG7MFBN4eK1AN. 1100w, https://miro.medium.com/v2/resize:fit:1400/0*oY2OG7MFBN4eK1AN. 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*oY2OG7MFBN4eK1AN. 640w, https://miro.medium.com/v2/resize:fit:720/0*oY2OG7MFBN4eK1AN. 720w, https://miro.medium.com/v2/resize:fit:750/0*oY2OG7MFBN4eK1AN. 750w, https://miro.medium.com/v2/resize:fit:786/0*oY2OG7MFBN4eK1AN. 786w, https://miro.medium.com/v2/resize:fit:828/0*oY2OG7MFBN4eK1AN. 828w, https://miro.medium.com/v2/resize:fit:1100/0*oY2OG7MFBN4eK1AN. 1100w, https://miro.medium.com/v2/resize:fit:1400/0*oY2OG7MFBN4eK1AN. 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*oY2OG7MFBN4eK1AN."></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>An overview of TensorFlow.js APIs. TensorFlow.js is powered by WebGL and provides a high-level layers API for defining models, and a low-level API for linear algebra and automatic differentiation. TensorFlow.js supports importing TensorFlow SavedModels and Keras models.</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">How does TensorFlow.js relate to deeplearn.js?</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Good question! TensorFlow.js, an ecosystem of JavaScript tools for machine learning, is the successor to deeplearn.js which is now called TensorFlow.js Core. TensorFlow.js also includes a Layers API, which is a higher level library for building machine learning models that uses Core, as well as tools for automatically porting TensorFlow SavedModels and Keras hdf5 models. For answers to more questions like this, check out the <a href="https://js.tensorflow.org/faq/" target="_self">FAQ</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Where’s the best place to learn more?</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">To learn more about TensorFlow.js, visit the project <a href="https://js.tensorflow.org/" target="_self">homepage</a>, check out the <a href="https://js.tensorflow.org/tutorials/" target="_self">tutorials</a>, and try the <a href="https://github.com/tensorflow/tfjs-examples" target="_self">examples</a>. You can also watch the talk from the 2018 TensorFlow Developer Summit, and follow TensorFlow on <a href="http://twitter.com/tensorflow" target="_self">Twitter</a>.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:80%;"><iframe  scrolling="auto" width="854.0" height="480.0" frameborder="0" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fvideoseries%3Flist%3DPLQY2H8rRoyvxjVx3zfw4vA4cvlKogyLNN%26start%3D0&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DgplTc2F5Wvk&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FgplTc2F5Wvk%2Fhqdefault.jpg&key=a19fcc184b9711e1b4764040d3dc5c07&type=text%2Fhtml&schema=youtube" allowfullscreen=""></iframe></div><br><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Live from Mountain View, CA! Join the TensorFlow team as they host the second annual TensorFlow Dev Summit. All the sessions will be recorded and uploaded to the channel today.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Thanks for reading, and we’re excited to see what you’ll create with TensorFlow.js! If you like, you can follow <a href="http://twitter.com/dsmilkov" target="_self">@dsmilkov</a>, <a href="http://twitter.com/nsthorat" target="_self">@nsthorat</a>, and <a href="http://twitter.com/sqcai" target="_self">@sqcai</a> from the TensorFlow.js team on Twitter for updates.</p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>