<!DOCTYPE html>
                <html>
                <head>
                    <title>Kine Protocol Airdrop Campaign is LIVE</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/@KineProtocol/kine-protocol-airdrop-campaign-is-live-fb3661ab6507"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@KineProtocol?source=post_page-----fb3661ab6507--------------------------------">Author : Kine Protocol</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Kine Protocol Airdrop Campaign is LIVE</h3></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">Reward Pool: 4000 KINE Token (10000 USD equivalent)Get up to 1 KINE token for participation and 0.5 KINE token for referral<strong>Airdrop Link: </strong><a href="https://t.me/KineProtocolAirdropBot?start=r0617145492" target="_self">https://t.me/KineProtocolAirdropBot?start=r0617145492</a></p></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Z709ZrzUUU46LNlkXM-OyA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Z709ZrzUUU46LNlkXM-OyA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Z709ZrzUUU46LNlkXM-OyA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Z709ZrzUUU46LNlkXM-OyA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Z709ZrzUUU46LNlkXM-OyA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Z709ZrzUUU46LNlkXM-OyA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Z709ZrzUUU46LNlkXM-OyA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Z709ZrzUUU46LNlkXM-OyA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Z709ZrzUUU46LNlkXM-OyA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Z709ZrzUUU46LNlkXM-OyA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Z709ZrzUUU46LNlkXM-OyA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Z709ZrzUUU46LNlkXM-OyA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Z709ZrzUUU46LNlkXM-OyA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*Z709ZrzUUU46LNlkXM-OyA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*Z709ZrzUUU46LNlkXM-OyA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5"><strong>Do 6 Tasks & Get 1 KINE token</strong></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;">To follow <a href="https://twitter.com/KineProtocol" target="_self">Twitter</a></li><li class="ff3" style="font-size:22px;">To join the <a href="http://t.me/kineprotocol" target="_self">Telegram</a> group</li><li class="ff3" style="font-size:22px;">To follow <a href="https://medium.com/@KineProtocol" target="_self">Medium</a></li><li class="ff3" style="font-size:22px;">To follow <a href="https://www.reddit.com/r/KineProtocolOfficial/" target="_self">Reddit</a></li><li class="ff3" style="font-size:22px;">To follow <a href="https://discord.com/invite/rzFpssXHcT" target="_self">Discord</a></li><li class="ff3" style="font-size:22px;">To like, tag 3 members and retweet the pinned tweet</li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Refer More To Earn More</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>⚠️Airdrop Link:</strong> <a href="https://t.me/KineProtocolAirdropBot?start=r0617145492" target="_self">https://t.me/KineProtocolAirdropBot?start=r0617145492</a></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5"><strong>Rules and Tips</strong></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;">Early Participants Get Better Rewards</li><li class="ff3" style="font-size:22px;">First Come, First Served</li><li class="ff3" style="font-size:22px;">It all depends on how soon you participate after we announce an airdrop. Be alert, and you’ll get a greater chance of receiving an airdrop on 100% completion of the tasks.</li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5"><strong>Other Activity Rules</strong></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">- All rewards will be distributed directly to participants’ BEP-20 (Binance smart chain) wallet addresses and will not be confirmed in a further announcement.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">- Kine Protocol reserves the right to cancel or amend any Activity or Activity Rules at our sole discretion.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Good Luck !</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Kine Team</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">2021–10–07</p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>