<!DOCTYPE html>
                <html>
                <head>
                    <title>Reinventing Health, Disease Diagnosis & Management, Drug Discovery</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/@vkhosla/reinventing-health-disease-diagnosis-management-drug-discovery-12e34052a8fb"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@vkhosla?source=post_page-----12e34052a8fb--------------------------------">Author : Vinod Khosla</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Reinventing Health, Disease Diagnosis & Management, Drug Discovery</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Section 7 of “Reinventing Societal Infrastructure with Technology” which will be released end of January. I will be posting a new section daily. Please share your feedback as this is a work in progress.</em></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:67%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1000/format:webp/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 1000w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 500px" srcset="https://miro.medium.com/v2/resize:fit:640/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1000/1*g-j-OyV69FdCONN3Lpl9fg.jpeg 1000w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/500/1*g-j-OyV69FdCONN3Lpl9fg.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Key drivers: Artificial intelligence for comprehensive understanding of medical knowledge, new measurement techniques enabled by and for machines allowing for 1000x or more data for algorithms to use, new algorithms to discover new knowledge in medicine, better research based on more data, more , better drug discovery using AI, and AI guided robotic surgery.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Is it likely technology could multiply doctors including many, if not most, specialties by many fold? Perhaps it could even, invent a better doctor, making them always available everywhere, accessible, and affordable or near free like Google search? Maybe people should only provide the human element of medical care if they prove to be better than AI? There is probably a million doctors in the United States, give or take, but with AI systems, we could create ten or a few hundred million doctors worth of expertise and use human doctors only for what they love to do, which is interfacing with patients, making health more more personal, accessible, convenient, and less costly.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The reality of medicine today is very different; doctors have a few minutes per patient visit for the top half of the planet’s population and <a href="https://www.youtube.com/watch?v=L-Qyzs1kZco" target="_self">little to none for everyone else</a>. In the future, almost certainly data science and AI will provide much better diagnosis, monitoring, and follow-up than most human doctors, as per my <a href="https://www.khoslaventures.com/20-percent-doctor-included-speculations-and-musings-of-a-technology-optimist" target="_self">paper in 2016</a>. It will do much better prescription, whether prescribing a drug or a procedure. We will have real science behind medicine as doctors today learn mostly from constantly improving iterative practice. Every AI agent will be updated with the latest research and up-to-date with every speciality, instead of being knowledgeable in just their own vertical specialty. That will allow for a holistic approach to treating patients because of integrative knowledge, as opposed to the current separating of the specialists, like patient’s cardiologist from their orthopedist or endocrinologist.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Medicine’s much better than it has ever been, so we have to acknowledge every aspect of medicine has improved over the last ten years, thirty years, hundred years. That, however, does not mean it cannot be even better. At the moment, the “iteration of practice” has done a pretty damn good job to improve medicine; when AI does medicine, it will be so much better. AI will enable less errors in doctor diagnosis and surgery, better drug discovery, and personalized prescriptions. Care will be based on thousands of biomarkers, genes, transcriptome, proteome, sometimes called “all *-omics medicine”. We will be able to measure many more variables (thousands or millions per sample or more) and make decisions based on complexity no human doctor could master. It will be possible to even specify dosage for drugs for each patient’s current state and monitor disease progression as well as side effects at the molecular level.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">It seems silly there is one dosage prescription for aspirin or opioids for seven billion people on the planet. Drug discovery and surgery will change primarily to computational techniques, opening up more possibilities. Procedures like surgery and anesthesia could get roboticized, either with a human assisting robot or the other way around. Should you have bypass surgery or a stent? Most of that medicine is based on debatable evidence. According to the <a href="https://www.ncbi.nlm.nih.gov/pubmed/19244190" target="_self">American Heart Association, t</a>here is class A evidence for only about 11 percent of their cardiac-related recommendations, meaning exhibit evidence from multiple randomized trials or meta-analyses exists to support the diagnosis. Whereas 45 percent are based on recommendations founded on expert opinion <a href="https://www.khoslaventures.com/20-percent-doctor-included-speculations-and-musings-of-a-technology-optimist" target="_self">(level C evidence, the worst kind</a>).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">And great quality will only be possible to achieve because of very low marginal costs, as has happened in so many other computationally based services. Better and faster patient outcomes, lesser healthcare costs, and more accessibility to all people are most likely to happen simultaneously. Technology has generally increased healthcare costs, but hopefully, it will be different this time as marginal cost will be much lower, as opposed to those of proton beam accelerators.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Much has been discussed about precision medicine. Unfortunately, however, it is mostly focused on genomic data. That is mostly tunnel vision; a much more promising “all omics” medicine has the potential to use your genome, your microbiome, your blood transcriptome, proteome, metabolome, exposome and generally “all ohmics” to precisely characterize the state of each human body. Such approach would be more personalized than precision medicine. I suspect most diseases will be defined and diagnosed this way, with broad terms like “diabetes” becoming obsolete and patients being classified by the molecular pathways, causing the high blood sugar “symptom” to become obsolete just as the term “dropsy” has, thus marginalizing symptom-based medicine. One of the fundamental limitations in medical practice has been the propensity to collect data that people can interpret. What is promising to me is the number of fundamental technologies being attempted to collect large AI scale data from everything, from an MRI image to a blood sample to the lowly ECG. If one had 300,000 biomarkers form every drop of blood for the same cost as today’s blood test and diabetes was defined and differentiated based on patterns of these markers, one would be able to predict which diabetic was at risk of cardiac disease and which of diabetic neuropathy. All this would be much better for the patient. Imaging is also ripe for re-invention, using computational capabilities and consumerized components. Much more is possible than we settle for today, in X-rays, ultrasound, MRI, CT scans, fMRI and more. Looking into the body should be routine, radiation-free and inexpensive.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I think very little about medicine needs to stay the same. We have to get away from the idea that we use symptoms to diagnose disease. Data science should diagnose disease and monitor progress or recommend dosage of a medication and therapy to best treatment. We should get away from the notion of one prescription for all seven billion people on the planet based mostly on their weight. As I described <a href="https://www.quora.com/If-Vinod-Khosla-were-to-start-a-company-today-what-would-it-be-Why" target="_self">on Quora</a> last year, one should take a million people, measure hundreds, if not thousands of variables, their blood and their microbiome and their physiology, every week, for a year. That way we’d have fifty million data points, each data point being thousands of data points in itself. Such a data set could predict most diseases, diagnose most diseases, and do it early — when it is truly beginning, not when it becomes symptomatic. This can not only contribute to preventive health. It can and will combat diseases and cancer by very early diagnosis. Plus, layer this into gene editing techniques and microbiome research. There is much to be done around personalization and targeted medicine. That’s the startup I would do and get excited about doing. We have already seen entrepreneurs working on it in bits and pieces. While it’s very complex and cannot be done in one step today, we will get there in the end. I only half jokingly told the Stanford Medical School audience about it three years ago: If I wanted to be a really good doctor in fifteen years, I would not go to the med school, I’d go to the math department.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Here are the facts: if you give a doctor five thousand data points, they wouldn’t know how to diagnose you. If you give a system five-thousand data points, it can do really good diagnosis, and if you do fifty-thousand more, it’d be better. Applied Proteomics turned this data science project into one to say most people who need colonoscopy don’t get it. It all amounts to the fact it is difficult, unpleasant, and expensive. With such analysis, we can get enough information to recommend whether you really, are at high risk and should get a colonoscopy This analysis will get better and, eventually, replace colonoscopy.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Disease will be detected early. Right now, most people with heart disease learn about their disease from a heart attack, not twenty years earlier when it started. When this is no longer the norm, we will move closer to healthcare from the sickcare we have today. We should have real science behind medicine. Medicine is much better than it has ever been, so we have to acknowledge every aspect of medicine has improved over the last ten, thirty or hundred years. But that doesn’t mean it’s as good as it can be. The people who object to this, don’t realize that at least three billion of the seven billion people on this planet have never seen a doctor, don’t have access to one, or cannot afford one. They definitely couldn’t afford the drugs that pharma companies have been putting out recently. It is criminal that they cannot, especially if medication exists.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">**This is a section from “Reinventing Societal Infrastructure with Technology”. To read the previous section,<a href="https://medium.com/@vkhosla/reinventing-transportation-64a39b1152dd" target="_self"> click here.</a></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>