<!DOCTYPE html>
                <html>
                <head>
                    <title>Thoughts after taking the Deeplearning.ai courses</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://towardsdatascience.com/thoughts-after-taking-the-deeplearning-ai-courses-8568f132153"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@gedanken.thesis?source=post_page-----8568f132153--------------------------------">Author : Arvind N</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Thoughts after taking the Deeplearning.ai courses</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">[<em>Update — Feb 2nd 2018: When this blog post was written, only 3 courses had been released. </em><a href="https://www.coursera.org/account/accomplishments/specialization/certificate/2VB5TAAWSWNK" target="_self">All 5 courses in this specialization are now out</a><em>. I will have a follow-up blog post soon.</em>]</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Introduction:</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Between a full time job and a toddler at home, I spend my spare time learning about the ideas in <mark>cognitive science</mark> & AI. Once in a while a great paper/video/course comes out and you’re instantly hooked.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Andrew Ng’s new deeplearning.ai course is like that <a href="https://www.quora.com/What-is-Shane-Carruths-new-film-Upstream-Color-all-about/answer/Arvind-Nagaraj?srid=TS2A" target="_self">Shane Carruth</a> or <a href="https://www.youtube.com/watch?v=hDJEn9xTe5c" target="_self">Rajnikanth movie</a> that one yearns for!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Naturally, as soon as the course was released on coursera, I registered and spent the past 4 evenings binge watching the lectures, working through quizzes and programming assignments.</p></div></div></div></section><section data-bs-version="5.1" class="gallery3 cid-ttaWMCQCls" id="gallery3-7" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container" style="width:60%;"><div class="row mt-4">
            <div class="item features-image сol-12 col-md-6 col-lg-6">
                <div class="item-wrapper" >
                    <div class="item-img"><img src ="https://miro.medium.com/v2/resize:fit:1006/format:webp/1*-K7y1ZjfkkxCsU49UhPBHw.png" style="height:auto; max-width: 100%;"></div></div></div><br>
            <div class="item features-image сol-12 col-md-6 col-lg-6">
                <div class="item-wrapper" >
                    <div class="item-img"><img src ="https://miro.medium.com/v2/resize:fit:996/format:webp/1*34kWXN1Jc7L1phvgoIzs8w.png" style="height:auto; max-width: 100%;"></div></div></div><br></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">DL practitioners and ML engineers typically spend most days working at an abstract Keras or TensorFlow level. But it’s nice to take a break once in a while to get down to the nuts and bolts of learning algorithms and actually do back-propagation by hand. It is both fun and <a href="https://medium.com/@karpathy/yes-you-should-understand-backprop-e2f06eab496b" target="_self">incredibly useful</a>!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">What this course is about:</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Andrew Ng’s new <em>ad</em>venture is a <a href="https://en.wikipedia.org/wiki/Top-down_and_bottom-up_design" target="_self">bottom-up approach</a> to teaching neural networks — powerful non-linearity learning algorithms, at a beginner-mid level.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In classic Ng style, the course is delivered through a carefully chosen curriculum, neatly timed videos and precisely positioned information nuggets. Andrew picks up from where his classic ML course left off and introduces the idea of neural networks using a single neuron(logistic regression) and slowly adding complexity — more neurons and layers. By the end of the 4 weeks(course 1), a student is introduced to all the core ideas required to build a dense neural network such as cost/loss functions, learning iteratively using gradient descent and vectorized parallel python(numpy) implementations.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Andrew patiently explains the requisite math and programming concepts in a carefully planned order and a well regulated pace suitable for learners who could be rusty in math/coding.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Course material and tools:</h4></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*XR_t6ydPWgdsC08NcE4Qjw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*XR_t6ydPWgdsC08NcE4Qjw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*XR_t6ydPWgdsC08NcE4Qjw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*XR_t6ydPWgdsC08NcE4Qjw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*XR_t6ydPWgdsC08NcE4Qjw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*XR_t6ydPWgdsC08NcE4Qjw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*XR_t6ydPWgdsC08NcE4Qjw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*XR_t6ydPWgdsC08NcE4Qjw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*XR_t6ydPWgdsC08NcE4Qjw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*XR_t6ydPWgdsC08NcE4Qjw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*XR_t6ydPWgdsC08NcE4Qjw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*XR_t6ydPWgdsC08NcE4Qjw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*XR_t6ydPWgdsC08NcE4Qjw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*XR_t6ydPWgdsC08NcE4Qjw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*XR_t6ydPWgdsC08NcE4Qjw.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">video lecture</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Lectures are delivered using presentation slides on which Andrew writes using digital pens. It felt like an effective way to get the listener to focus. I felt comfortable watching videos at 1.25x or 1.5x speed.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 640w, https://miro.medium.com/v2/resize:fit:720/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 720w, https://miro.medium.com/v2/resize:fit:750/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 750w, https://miro.medium.com/v2/resize:fit:786/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 786w, https://miro.medium.com/v2/resize:fit:828/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*N39jZ0L8Ezz0bVGBWeRq_Q.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*N39jZ0L8Ezz0bVGBWeRq_Q.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">quiz tool</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Quizzes are placed at the end of each lecture sections and are in the multiple choice question format. If you watch the videos once, you should be able to quickly answer all the quiz questions. You can attempt quizzes multiple times and the system is designed to keep your highest score.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*5yzRONhHHvUS2gaRyI2_ZA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*5yzRONhHHvUS2gaRyI2_ZA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*5yzRONhHHvUS2gaRyI2_ZA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*5yzRONhHHvUS2gaRyI2_ZA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*5yzRONhHHvUS2gaRyI2_ZA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*5yzRONhHHvUS2gaRyI2_ZA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*5yzRONhHHvUS2gaRyI2_ZA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*5yzRONhHHvUS2gaRyI2_ZA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*5yzRONhHHvUS2gaRyI2_ZA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*5yzRONhHHvUS2gaRyI2_ZA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*5yzRONhHHvUS2gaRyI2_ZA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*5yzRONhHHvUS2gaRyI2_ZA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*5yzRONhHHvUS2gaRyI2_ZA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*5yzRONhHHvUS2gaRyI2_ZA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*5yzRONhHHvUS2gaRyI2_ZA.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Jupyter notebook programming assignment</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Programming assignments are done via J<a href="http://jupyter.org/" target="_self">upyter notebooks</a> — powerful browser based applications.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Assignments have a nice guided sequential structure and you are not required to write more than 2–3 lines of code in each section. If you understand the concepts like vectorization intuitively, you can complete most programming sections with just 1 line of code!</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Yzi8FNFjEQASlARYj7TExA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Yzi8FNFjEQASlARYj7TExA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Yzi8FNFjEQASlARYj7TExA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Yzi8FNFjEQASlARYj7TExA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Yzi8FNFjEQASlARYj7TExA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Yzi8FNFjEQASlARYj7TExA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Yzi8FNFjEQASlARYj7TExA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Yzi8FNFjEQASlARYj7TExA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Yzi8FNFjEQASlARYj7TExA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Yzi8FNFjEQASlARYj7TExA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Yzi8FNFjEQASlARYj7TExA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Yzi8FNFjEQASlARYj7TExA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Yzi8FNFjEQASlARYj7TExA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*Yzi8FNFjEQASlARYj7TExA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*Yzi8FNFjEQASlARYj7TExA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">After the assignment is coded, it takes 1 button click to submit your code to the automated grading system which returns your score in a few minutes. Some assignments have time restrictions — say, three attempts in 8 hours etc.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Jupyter notebooks are well designed and work without any issues. Instructions are precise and it feels like a polished product.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Who is this course for:</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Anyone interested in understanding what neural networks are, how they work, how to build them and the tools available to bring your ideas to life.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*dzTM7T1doDVn0cCZ5Mi5pQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*dzTM7T1doDVn0cCZ5Mi5pQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If your math is rusty, there is no need to worry — Andrew explains all the required calculus and provides derivatives at every occasion so that you can focus on building the network and concentrate on implementing your ideas in code.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If your programming is rusty, there is a nice coding assignment to teach you numpy. But I recommend learning python first on <a href="https://www.codecademy.com/learn/learn-python" target="_self">codecademy</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">How this DL course is different from Jeremy Howard’s Fast.ai course:</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Let me explain this with an analogy: <em>Assume you are trying to learn how to drive a car.</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Jeremy’s FAST.AI course</strong> puts you in the drivers seat from the get-go. He teaches you to move the steering wheel, press the brake, accelerator etc. Then he slowly explains more details about how the car works — why rotating the wheel makes the car turn, why pressing the brake pedal makes you slow down and stop etc. He keeps getting deeper into the inner workings of the car and by the end of the course, you know how the internal combustion engine works, how the fuel tank is designed etc. <em>The goal of the course is to get you driving. You can choose to stop at any point after you can drive reasonably well — there is no need to learn how to build/repair the car.</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Andrew’s DL course</strong> does all of this, but in <strong>the complete opposite order</strong>. He teaches you about internal combustion engine first! He keeps adding <em>layers </em>of abstraction and by the end of the course you are driving like an F1 racer!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><mark>The fast AI course mainly teaches you the </mark><mark>art of driving </mark><mark>while Andrew’s course primarily teaches you the </mark><mark>engineering behind the car</mark><mark>.</mark></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">How to approach this course:</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you have not done any machine learning before this, don’t take this course first. The best starting point is Andrew’s original <a href="https://www.coursera.org/learn/machine-learning" target="_self">ML course on coursera</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">After you complete that course, please try to complete part-1 of Jeremy Howard’s excellent <a href="http://course.fast.ai/" target="_self">deep learning course</a>. Jeremy teaches deep learning <a href="http://course.fast.ai/about.html" target="_self">Top-Down which is essential for absolute beginners</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Once you are comfortable creating deep neural networks, it makes sense to take this <a href="https://www.deeplearning.ai/" target="_self">new deeplearning.ai course specialization</a> which fills up any gaps in your understanding of the underlying details and concepts.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Things I liked in this course:</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;">Facts are pretty much laid out bare — All uncertainties & ambiguities are periodically eliminated</li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">2. Andrew stresses on the engineering aspects of deep learning and provides plenty of practical tips to save time and money — the third course in the DL specialization felt incredibly useful for my role as an <a href="https://www.linkedin.com/in/arvind-nagaraj-9a17aa82/" target="_self">architect leading engineering teams</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">3. Jargon is handled well. Andrew explains that an <em>empirical process = trial & error</em> — He is brutally honest about the reality of designing and training deep nets. At some point I felt <em>he might have as well just called Deep Learning as glorified curve-fitting</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">4. Squashes all hype around DL and AI — Andrew makes restrained, careful comments about proliferation of AI hype in the mainstream media and by the end of the course it is pretty clear that DL is nothing like the terminator.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">5.Wonderful boilerplate code that just works out of the box!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">6. Excellent course structure.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">7. Nice, consistent and useful notation. Andrew strives to establish a fresh nomenclature for neural nets and I feel he could be quite successful in this endeavor.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">8. Style of teaching that is unique to Andrew and carries over from ML — I could feel the same excitement I felt in 2013 when I took his original ML course.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">9.The interviews with deep learning heroes are refreshing — It is motivating and fun to hear personal stories and anecdotes.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Things I found lacking:</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I wish that he’d said ‘<em>concretely</em>’ <a href="https://www.youtube.com/watch?v=5ZNJPSe1nZs" target="_self">more often</a>!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Some additional things I learnt along the way:</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;">DL is not easy. It takes some hard work over time to “get” the concepts and make them work well. <a href="https://www.quora.com/How-should-you-start-a-career-in-Machine-Learning/answer/Andrew-Ng?srid=TS2A" target="_self">Andrew had written a quora answer</a> a while ago that deeply resonated with me.</li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">2. Good tools are important and will help you accelerate your learning pace. I bought a digital pen after seeing Andrew teach with one. It helped me work more efficiently.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*ZYt3L21yU4rgtGjV3w3Wwg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*ZYt3L21yU4rgtGjV3w3Wwg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*ZYt3L21yU4rgtGjV3w3Wwg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*ZYt3L21yU4rgtGjV3w3Wwg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*ZYt3L21yU4rgtGjV3w3Wwg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ZYt3L21yU4rgtGjV3w3Wwg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*ZYt3L21yU4rgtGjV3w3Wwg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*ZYt3L21yU4rgtGjV3w3Wwg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*ZYt3L21yU4rgtGjV3w3Wwg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*ZYt3L21yU4rgtGjV3w3Wwg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*ZYt3L21yU4rgtGjV3w3Wwg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*ZYt3L21yU4rgtGjV3w3Wwg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*ZYt3L21yU4rgtGjV3w3Wwg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*ZYt3L21yU4rgtGjV3w3Wwg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*ZYt3L21yU4rgtGjV3w3Wwg.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Black ink is Andrew’s and colors are mine</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">3. There is <a href="https://oliveremberton.com/2014/how-to-find-your-passion/" target="_self">a psychological reason</a> why I recommend the Fast.ai course before this one. Once you find your passion, you can learn uninhibited.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">4. You just get that dopamine rush each time you score full points:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*SmQBLjz0DU4q3-z13QEcLg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*SmQBLjz0DU4q3-z13QEcLg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*SmQBLjz0DU4q3-z13QEcLg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*SmQBLjz0DU4q3-z13QEcLg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*SmQBLjz0DU4q3-z13QEcLg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*SmQBLjz0DU4q3-z13QEcLg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*SmQBLjz0DU4q3-z13QEcLg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*SmQBLjz0DU4q3-z13QEcLg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*SmQBLjz0DU4q3-z13QEcLg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*SmQBLjz0DU4q3-z13QEcLg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*SmQBLjz0DU4q3-z13QEcLg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*SmQBLjz0DU4q3-z13QEcLg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*SmQBLjz0DU4q3-z13QEcLg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*SmQBLjz0DU4q3-z13QEcLg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*SmQBLjz0DU4q3-z13QEcLg.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">hell yeah!</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">5. Don’t be scared by DL jargon (<em>hyperparameters = settings, architecture/topology=style etc.</em>) or the math symbols. If you take a leap of faith and pay attention to the lectures, Andrew shows why the symbols and notation are actually quite useful. <em>They will soon become your tools of choice and you will wield them with style</em>!</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*q2yV1deBvD--hZYzZcPqGw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*q2yV1deBvD--hZYzZcPqGw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*q2yV1deBvD--hZYzZcPqGw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*q2yV1deBvD--hZYzZcPqGw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*q2yV1deBvD--hZYzZcPqGw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*q2yV1deBvD--hZYzZcPqGw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*q2yV1deBvD--hZYzZcPqGw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*q2yV1deBvD--hZYzZcPqGw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*q2yV1deBvD--hZYzZcPqGw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*q2yV1deBvD--hZYzZcPqGw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*q2yV1deBvD--hZYzZcPqGw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*q2yV1deBvD--hZYzZcPqGw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*q2yV1deBvD--hZYzZcPqGw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*q2yV1deBvD--hZYzZcPqGw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*q2yV1deBvD--hZYzZcPqGw.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">some scary looking symbols which will begin to make sense when you watch the lecture videos</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Closing comments(optional read):</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;">Everyone starts in this field as a beginner. If you are a complete newcomer to the DL field, it’s natural to feel intimidated by all the jargon and concepts. Please don’t give up. You probably were drawn to this field hoping to find your calling. Trust your gut and stay focused and you will be successful sooner than you realize! <em>Even Andrew Ng had to learn linear algebra at some point in the past — he wasn’t born with that knowledge.</em></li><li class="ff3" style="font-size:22px;">While this is an incredible resource, this is not the only DL course in the world. Many generous teachers like <a href="https://www.khanacademy.org/" target="_self">Salman Khan</a>, Jeremy Howard, Sebastian Thrun, Geoff Hinton have shared their knowledge online for free just like Andrew Ng. I wasn’t lucky enough to pursue a masters or PhD as I had to enter the workforce and support my family — But that didn’t mean the learning had to stop. I have had the opportunity to customize my own learning plan, thanks to the democratization of knowledge. And I could choose to learn from the people I admired most: Programming(Gerald Sussman), Linear Algebra(Gilbert Strang), AI(Marvin Minsky), Philosophy(Daniel Dennett), Psychology(Jean Piaget), Physics(Hans Bethe)…</li><li class="ff3" style="font-size:22px;">Most of applied DL is really disciplined engineering — And Prof. Ng provides a fantastic compilation in course-3(<em>My favorite of the 3 courses released so far</em>). The mindset required for making DL work for your problems are no different than that required while approaching any other hard engineering problem. Everything you need to know has been <a href="https://medium.com/the-mission/a-genius-explains-how-to-be-creative-claude-shannons-long-lost-1952-speech-fbbcb2ebe07f" target="_self">documented clearly by Claude Shannon decades ago</a>.</li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Thanks for reading and best wishes!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Update: Thanks for the overwhelmingly positive response! Many people are asking me to explain gradient descent and the differential calculus. </em><a href="https://medium.com/@gedanken.thesis/gradient-descent-back-prop-and-derivatives-5b286bb8d8b5" target="_self">I hope this helps</a><em>!</em></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>