<!DOCTYPE html>
                <html>
                <head>
                    <title>Yale & IBM Propose KerGNNs: Interpretable GNNs with Graph Kernels That Achieve SOTA-Competitive Performance</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/syncedreview/yale-ibm-propose-kergnns-interpretable-gnns-with-graph-kernels-that-achieve-sota-competitive-7ec60ff6ec3"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@synced?source=post_page-----7ec60ff6ec3--------------------------------">Author : Synced</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Yale & IBM Propose KerGNNs: Interpretable GNNs with Graph Kernels That Achieve SOTA-Competitive Performance</h3></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*_aOtq5nE94RlrV9XgNHXKw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*_aOtq5nE94RlrV9XgNHXKw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*_aOtq5nE94RlrV9XgNHXKw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*_aOtq5nE94RlrV9XgNHXKw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*_aOtq5nE94RlrV9XgNHXKw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*_aOtq5nE94RlrV9XgNHXKw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*_aOtq5nE94RlrV9XgNHXKw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*_aOtq5nE94RlrV9XgNHXKw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*_aOtq5nE94RlrV9XgNHXKw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*_aOtq5nE94RlrV9XgNHXKw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*_aOtq5nE94RlrV9XgNHXKw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*_aOtq5nE94RlrV9XgNHXKw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*_aOtq5nE94RlrV9XgNHXKw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*_aOtq5nE94RlrV9XgNHXKw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/1*_aOtq5nE94RlrV9XgNHXKw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Graph kernel methods have traditionally been the most common technique for graph classification tasks, even though their performance is restricted by their hand-crafted combinatorial features. The emergence in recent years of graph neural networks (GNNs) based on high-performance message-passing neural networks (MPNNs) has made these increasingly popular choices for graph classification. MPNN frameworks however also have drawbacks, namely their poor expressivity.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In the new paper <em>KerGNNs: Interpretable Graph Neural Networks with Graph Kernels</em>, a research team from Yale University and IBM proposes Kernel Graph Neural Networks (KerGNNs), which integrate graph kernels and the GNN message-passing process in a single framework. KerGNNs achieve performance comparable to state-of-the-art methods while significantly improving model interpretability compared to conventional GNNs.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*jJ2PAhbSqQR-XaED.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*jJ2PAhbSqQR-XaED.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*jJ2PAhbSqQR-XaED.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*jJ2PAhbSqQR-XaED.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*jJ2PAhbSqQR-XaED.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*jJ2PAhbSqQR-XaED.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*jJ2PAhbSqQR-XaED.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*jJ2PAhbSqQR-XaED.png 640w, https://miro.medium.com/v2/resize:fit:720/0*jJ2PAhbSqQR-XaED.png 720w, https://miro.medium.com/v2/resize:fit:750/0*jJ2PAhbSqQR-XaED.png 750w, https://miro.medium.com/v2/resize:fit:786/0*jJ2PAhbSqQR-XaED.png 786w, https://miro.medium.com/v2/resize:fit:828/0*jJ2PAhbSqQR-XaED.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*jJ2PAhbSqQR-XaED.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*jJ2PAhbSqQR-XaED.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*jJ2PAhbSqQR-XaED.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The team summarizes their work’s main contributions as:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;">We use neighbourhood subgraph topology combined with kernel methods for GNN neighbourhood aggregation, and show with proof that the expressivity of this approach is not limited by the 1-WL algorithm.</li><li class="ff3" style="font-size:22px;">We provide a new perspective to generalize CNNs into the graph domain, by showing that both 2-D convolution and graph neighbourhood aggregation can be interpreted using the language of kernel methods.</li><li class="ff3" style="font-size:22px;">Besides envisioning the output graphs of the model, KerGNNs can further reveal the local structure of the input graphs by visualizing the topology of trained graph filters, which significantly improves the model interpretability and transparency compared with standard MPNNs.</li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The main idea behind KerGNNs is combining graph kernels with the GNN message-passing process to exploit the strengths of both methods. Graph kernels have been widely used for assessing the similarity between graphs, enabling classification and regression with graph-structured data. Kernel functions can operate in a high-dimensional feature space by simply computing the kernel value in the low-dimensional feature space, which is more computationally efficient than directly computing in the high-dimensional space. Graph kernels’ ability to capture high-dimensional information in large graphs is however restricted by their hand-crafted features and fixed feature construction scheme.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">MPNNs meanwhile are neural models that capture the dependence of graphs via message-passing between their nodes, operating in two stages: neighbourhood aggregation and graph-level readout. Although MPNNs have advanced the state-of-the-art on graph-related tasks, they have theoretical limits in terms of expressivity, as studies have shown they cannot exceed the power of the WeisfeilerLehman (WL) algorithm on the graph isomorphism test.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:88%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 648px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*XGcI0BSlzQobBvkF.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*XGcI0BSlzQobBvkF.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*XGcI0BSlzQobBvkF.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*XGcI0BSlzQobBvkF.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*XGcI0BSlzQobBvkF.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*XGcI0BSlzQobBvkF.png 1100w, https://miro.medium.com/v2/resize:fit:1296/format:webp/0*XGcI0BSlzQobBvkF.png 1296w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 648px" srcset="https://miro.medium.com/v2/resize:fit:640/0*XGcI0BSlzQobBvkF.png 640w, https://miro.medium.com/v2/resize:fit:720/0*XGcI0BSlzQobBvkF.png 720w, https://miro.medium.com/v2/resize:fit:750/0*XGcI0BSlzQobBvkF.png 750w, https://miro.medium.com/v2/resize:fit:786/0*XGcI0BSlzQobBvkF.png 786w, https://miro.medium.com/v2/resize:fit:828/0*XGcI0BSlzQobBvkF.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*XGcI0BSlzQobBvkF.png 1100w, https://miro.medium.com/v2/resize:fit:1296/0*XGcI0BSlzQobBvkF.png 1296w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/648/0*XGcI0BSlzQobBvkF.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The researchers propose a subgraph-based node aggregation algorithm to leverage these two approaches. For neighbourhood aggregation, they apply graph kernels that use the subgraph induced by node neighbours, such that the expressivity will not be limited by 1-WL isomorphism test. In a bid to boost adaptability, they make the graph kernels’ feature construction scheme trainable in accordance with the standard GNN training framework.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The proposed KerGNN model generalizes the scenario introduced in<em> Random Walk Graph Neural Networks </em>(<a href="https://proceedings.neurips.cc/paper/2020/file/ba95d78a7c942571185308775a97a3a0-Paper.pdf" target="_self">Nikolentzos and Vazirgiannis, 2020</a>), applying hidden graphs to extract local structural information instead of the entire graph, producing a multi-layer structure with better graph classification performance. To improve graph interpretability, KerGNN not only visualizes output graphs as GNNs do, it also produces trained hidden graphs as a byproduct of training. These contain useful structural information on common characteristics of the whole dataset instead of one specific graph.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The team notes that KerGNNs can generalize convolutional neural networks (CNNs) into the graph domain by replacing the kernel function for vectors with the graph kernel function, providing new insights on the design of GNN architectures. KerGNNs can also generalize most standard MPNN structures by deploying more complex graph filters with multiple nodes and a learnable adjacency matrix and using more expressive and efficient graph kernels.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*ouWKoFvHQnUR5Tu-.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*ouWKoFvHQnUR5Tu-.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*ouWKoFvHQnUR5Tu-.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*ouWKoFvHQnUR5Tu-.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*ouWKoFvHQnUR5Tu-.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*ouWKoFvHQnUR5Tu-.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*ouWKoFvHQnUR5Tu-.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*ouWKoFvHQnUR5Tu-.png 640w, https://miro.medium.com/v2/resize:fit:720/0*ouWKoFvHQnUR5Tu-.png 720w, https://miro.medium.com/v2/resize:fit:750/0*ouWKoFvHQnUR5Tu-.png 750w, https://miro.medium.com/v2/resize:fit:786/0*ouWKoFvHQnUR5Tu-.png 786w, https://miro.medium.com/v2/resize:fit:828/0*ouWKoFvHQnUR5Tu-.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*ouWKoFvHQnUR5Tu-.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*ouWKoFvHQnUR5Tu-.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*ouWKoFvHQnUR5Tu-.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The team evaluated KerGNNs on graph and node classification tasks, where they outperformed conventional GNNs with 1-WL limits and achieved similar performance to high-order GNNs while reducing running time. Also, unlike standard GNN variants, KerGNNs’ graph filters can provide extra information that can be used to help explain model predictions.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:82%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 607px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*fCXk6dmFI5N37jP3.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*fCXk6dmFI5N37jP3.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*fCXk6dmFI5N37jP3.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*fCXk6dmFI5N37jP3.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*fCXk6dmFI5N37jP3.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*fCXk6dmFI5N37jP3.png 1100w, https://miro.medium.com/v2/resize:fit:1214/format:webp/0*fCXk6dmFI5N37jP3.png 1214w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 607px" srcset="https://miro.medium.com/v2/resize:fit:640/0*fCXk6dmFI5N37jP3.png 640w, https://miro.medium.com/v2/resize:fit:720/0*fCXk6dmFI5N37jP3.png 720w, https://miro.medium.com/v2/resize:fit:750/0*fCXk6dmFI5N37jP3.png 750w, https://miro.medium.com/v2/resize:fit:786/0*fCXk6dmFI5N37jP3.png 786w, https://miro.medium.com/v2/resize:fit:828/0*fCXk6dmFI5N37jP3.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*fCXk6dmFI5N37jP3.png 1100w, https://miro.medium.com/v2/resize:fit:1214/0*fCXk6dmFI5N37jP3.png 1214w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/607/0*fCXk6dmFI5N37jP3.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Overall, KerGNNs demonstrate performance competitive with state-of-the-art methods while providing improved explainability and transparency via their visualization of graph filters and output graphs, indicating their potential to increase the representation ability of GNNs.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The paper <em>KerGNNs: Interpretable Graph Neural Networks with Graph Kernels </em>is on <a href="https://arxiv.org/abs/2201.00491" target="_self">arXiv</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Author</strong>: Hecate He | <strong>Editor</strong>: Michael Sarazen</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*nKPfa_LluIuBCRkn.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*nKPfa_LluIuBCRkn.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*nKPfa_LluIuBCRkn.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*nKPfa_LluIuBCRkn.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*nKPfa_LluIuBCRkn.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*nKPfa_LluIuBCRkn.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*nKPfa_LluIuBCRkn.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*nKPfa_LluIuBCRkn.png 640w, https://miro.medium.com/v2/resize:fit:720/0*nKPfa_LluIuBCRkn.png 720w, https://miro.medium.com/v2/resize:fit:750/0*nKPfa_LluIuBCRkn.png 750w, https://miro.medium.com/v2/resize:fit:786/0*nKPfa_LluIuBCRkn.png 786w, https://miro.medium.com/v2/resize:fit:828/0*nKPfa_LluIuBCRkn.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*nKPfa_LluIuBCRkn.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*nKPfa_LluIuBCRkn.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/max/700/0*nKPfa_LluIuBCRkn.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We know you don’t want to miss any news or research breakthroughs. <strong>Subscribe to our popular newsletter </strong><a href="https://mailchi.mp/2fb3aa308ad3/welcome-to-synced-global-ai-weekly-newsletter" target="_self">Synced Global AI Weekly</a><strong> to get weekly AI updates.</strong></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>