<!DOCTYPE html>
                <html>
                <head>
                    <title>An Interesting Interview Question.</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/y-math/an-interesting-interview-question-625c4878d91b"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@stephenwithaphd?source=post_page-----625c4878d91b--------------------------------">Author : StephenwithaPhD</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>An Interesting Interview Question.</h3></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:49%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 377px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 1100w, https://miro.medium.com/v2/resize:fit:754/format:webp/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 754w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 377px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 1100w, https://miro.medium.com/v2/resize:fit:754/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg 754w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:377/1*Dvdocu1ZTOT7sDeKjvWPEw.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Very recently, one of my students had an interview for an internship at a very prestigious investment bank. They were asked the following question as part of the interview. Can you solve it?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The question was reportedly given in the following way:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:39%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 307px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*fP6md4ngrqH3HV479vctRw.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*fP6md4ngrqH3HV479vctRw.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*fP6md4ngrqH3HV479vctRw.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*fP6md4ngrqH3HV479vctRw.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*fP6md4ngrqH3HV479vctRw.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*fP6md4ngrqH3HV479vctRw.jpeg 1100w, https://miro.medium.com/v2/resize:fit:614/format:webp/1*fP6md4ngrqH3HV479vctRw.jpeg 614w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 307px" srcset="https://miro.medium.com/v2/resize:fit:640/1*fP6md4ngrqH3HV479vctRw.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*fP6md4ngrqH3HV479vctRw.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*fP6md4ngrqH3HV479vctRw.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*fP6md4ngrqH3HV479vctRw.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*fP6md4ngrqH3HV479vctRw.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*fP6md4ngrqH3HV479vctRw.jpeg 1100w, https://miro.medium.com/v2/resize:fit:614/1*fP6md4ngrqH3HV479vctRw.jpeg 614w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:307/1*fP6md4ngrqH3HV479vctRw.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Make sure to give the problem a go yourself before reading on.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The student, let’s call her Amanda, admitted they were feeling a bit down as they were sure they had gotten the wrong answer. I told her not to worry too much about this as generally these questions are not asked to see if an applicant gets the right answer, but instead to see how they approach the question. I left Amanda, a little more upbeat than I found her, promising to think about the problem later and devise a solution.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Admittedly, at first, I didn’t see the purpose of asking about this particular problem. It was only when developing a solution that I think I cracked the reasoning behind it. To make sure I was right, the next day I asked Amanda if the interviewer had explicitly banned the use of a calculator, she, surprised at my question, confirmed they had indeed. This left me pretty confident my logic was correct, let’s see if you agree.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Here’s my thinking on it. From teaching as much as I have, I know exactly how most students would approach this question, and it’s probably exactly how most of you also approached it, simultaneous equations! You re-write</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:36%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 285px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:570/format:webp/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 570w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 285px" srcset="https://miro.medium.com/v2/resize:fit:640/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:570/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg 570w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:285/1*uP2AVB-6dmuJ3TZ3dZ-iIA.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">and then put this into the second equation to get the quadratic</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:62%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 463px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:926/format:webp/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 926w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 463px" srcset="https://miro.medium.com/v2/resize:fit:640/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:926/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg 926w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:463/1*qjrzcIPIlW2B_9NEWqj5cQ.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">You can now solve this to find that</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:18%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 156px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:312/format:webp/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 312w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 156px" srcset="https://miro.medium.com/v2/resize:fit:640/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:312/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg 312w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:156/1*0Ug4Yq5MJMXWNTnpI_6poA.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">which in turn tells you that</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:18%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 160px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:320/format:webp/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 320w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 160px" srcset="https://miro.medium.com/v2/resize:fit:640/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:320/1*7_fHNhkFBHegAc6uAYoqjA.jpeg 320w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:160/1*7_fHNhkFBHegAc6uAYoqjA.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Great, you have found the two solutions to your simultaneous equations</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:94%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 691px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1382/format:webp/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 1382w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 691px" srcset="https://miro.medium.com/v2/resize:fit:640/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1382/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg 1382w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:691/1*KB5Rxfof_sSW9uOVEWDBvQ.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">and so you could fill these in and solve</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:17%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 153px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*umM2rm13GWTC1u05bGugZQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*umM2rm13GWTC1u05bGugZQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*umM2rm13GWTC1u05bGugZQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*umM2rm13GWTC1u05bGugZQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*umM2rm13GWTC1u05bGugZQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*umM2rm13GWTC1u05bGugZQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:306/format:webp/1*umM2rm13GWTC1u05bGugZQ.jpeg 306w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 153px" srcset="https://miro.medium.com/v2/resize:fit:640/1*umM2rm13GWTC1u05bGugZQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*umM2rm13GWTC1u05bGugZQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*umM2rm13GWTC1u05bGugZQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*umM2rm13GWTC1u05bGugZQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*umM2rm13GWTC1u05bGugZQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*umM2rm13GWTC1u05bGugZQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:306/1*umM2rm13GWTC1u05bGugZQ.jpeg 306w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:153/1*umM2rm13GWTC1u05bGugZQ.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you solved the problem this way, like Amanda admitted she had, then you are completely right. This is a perfectly legitimate solution. However, did you use a calculator? If not, I’m very impressed. I would not have the patience, or willpower, to calculate either</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:43%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 334px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*dGurzzP8L_8BADhDLqrlgg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*dGurzzP8L_8BADhDLqrlgg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*dGurzzP8L_8BADhDLqrlgg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*dGurzzP8L_8BADhDLqrlgg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*dGurzzP8L_8BADhDLqrlgg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*dGurzzP8L_8BADhDLqrlgg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:668/format:webp/1*dGurzzP8L_8BADhDLqrlgg.jpeg 668w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 334px" srcset="https://miro.medium.com/v2/resize:fit:640/1*dGurzzP8L_8BADhDLqrlgg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*dGurzzP8L_8BADhDLqrlgg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*dGurzzP8L_8BADhDLqrlgg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*dGurzzP8L_8BADhDLqrlgg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*dGurzzP8L_8BADhDLqrlgg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*dGurzzP8L_8BADhDLqrlgg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:668/1*dGurzzP8L_8BADhDLqrlgg.jpeg 668w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:334/1*dGurzzP8L_8BADhDLqrlgg.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">by hand. On a side note, now that you are aware that you cannot use a calculator why not try to solve the problem again?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Can you solve the problem without a calculator you may ask? Yes, but not by first solving for the values of a and b. Instead, we will just use some basic expanding of brackets and then fill in the information we were given. I show one way, there are, I am sure, many more. To begin, we note that</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:61%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 458px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*UvCDiycvu9lrJoXElyINRg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*UvCDiycvu9lrJoXElyINRg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*UvCDiycvu9lrJoXElyINRg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*UvCDiycvu9lrJoXElyINRg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*UvCDiycvu9lrJoXElyINRg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*UvCDiycvu9lrJoXElyINRg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:916/format:webp/1*UvCDiycvu9lrJoXElyINRg.jpeg 916w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 458px" srcset="https://miro.medium.com/v2/resize:fit:640/1*UvCDiycvu9lrJoXElyINRg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*UvCDiycvu9lrJoXElyINRg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*UvCDiycvu9lrJoXElyINRg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*UvCDiycvu9lrJoXElyINRg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*UvCDiycvu9lrJoXElyINRg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*UvCDiycvu9lrJoXElyINRg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:916/1*UvCDiycvu9lrJoXElyINRg.jpeg 916w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:458/1*UvCDiycvu9lrJoXElyINRg.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We now have a formula for getting what we want, we now just need to manipulate our two given equations, which recall where a+b=1 and a²+b²=3, to find values for a⁴+b⁴ and ab. Let’s begin with ab:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:36%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 284px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:568/format:webp/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 568w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 284px" srcset="https://miro.medium.com/v2/resize:fit:640/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:568/1*wryWQ4w1QS4baa2tmjTiZg.jpeg 568w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:284/1*wryWQ4w1QS4baa2tmjTiZg.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now to find a value for a⁴+b⁴, we could do the following:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:46%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 352px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:704/format:webp/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 704w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 352px" srcset="https://miro.medium.com/v2/resize:fit:640/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:704/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg 704w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:352/1*-4fk_2QgK8b7RDHmA5sDEQ.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Finally, using what we have found, we get that</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:43%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 332px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 1100w, https://miro.medium.com/v2/resize:fit:664/format:webp/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 664w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 332px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 1100w, https://miro.medium.com/v2/resize:fit:664/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg 664w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:332/1*Ox-fWMHsx2PCopTL2JMX-A.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">As we can see, we get the same correct solution, with roughly the same amount of work, but without needing to use a calculator.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Getting back to the purpose of the question. Do I think that an investment bank really cared that an applicant could solve this question without a calculator? No, of course not. Instead, I think there were two important qualities that they could observe in an applicant by watching them solve this question:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;">If the applicant had tried to solve the question using the first method, in which we found the values of a and b, what I would be curious to see is whether they next spent all their remaining time slogging away at trying to calculate a⁸ and b⁸, or if they were mature enough to realize this wasn’t a fruitful way to approach this question, under the given restrictions, and were capable of thinking about it in another way.</li><li class="ff3" style="font-size:22px;">Would the applicant be capable of enough forward thinking to realize that trying to solve this question using the first method would lead to a problem, under the given restrictions, and then preemptively try a different method? This would be an impressive attribute to observe in an applicant, especially for an investment bank in which forward thinking is a rather important aspect of the job.</li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">You may argue that if an applicant had used a different method then this may have just been by chance and so this would give the interviewer no information. This is a legitimate point of view, and you certainly could have been right if it wasn’t for what happened less than a week later. Amanda told me how her friend had an interview at the same place and that she had shown this friend how to solve the problem using the method I outlined above. What’s interesting is that after this friend gave their solution the interviewer asked whether “there was a particular reason why they didn’t try to solve the question by first solving for a and b”.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">To me, this completely validates my second point. The interviewer was indeed trying to check if the applicant had preemptively avoided doing it this way, or whether they had done it by chance. Sadly, this friend replied that they just hadn’t thought to do it that way, what a missed opportunity to impress!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Do you have any other thoughts about why this question would be asked, or perhaps you have a more clever way to solve it? Please share what you think in the comments!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Also, if you found this interesting, you might also be interested in reading about this other interesting interview question reportedly used by Google and other tech companies</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://medium.com/y-math/a-second-interesting-interview-question-used-by-google-f0bc1b9ac719"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">A Second Interesting Interview Question- Used By Google.</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">A couple of articles ago, I discussed an interview question a student had been asked that I found interesting.</h3><p>medium.com</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Thanks for reading.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>I would appreciate it if you would consider following me and my publication Y(Math) so that my articles can reach a wider audience.</em></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>