<!DOCTYPE html>
                <html>
                <head>
                    <title>Best Online Resources To Learn Math</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/@ASTRAEVS/best-online-resources-to-learn-math-9935f031650c"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@ASTRAEVS?source=post_page-----9935f031650c--------------------------------">Author : Bogdan Yatsy</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Best Online Resources To Learn Math</h3></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*tBIyyKQ7OF56cpkVHcwAEA.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Photo by <a href="https://unsplash.com/@antoine1003" target="_self">Antoine Dautry</a> on <a href="https://unsplash.com/photos/05A-kdOH6Hw" target="_self">Unspash</a></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Like many people who are interested in computer science, at a certain stage of my studying journey, I realized that I lacked knowledge of mathematics.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">When I was in school, I was not bad at math, but many years have passed since then and, due to lack of practice, I forgot a lot. So when I opened some new book on algorithms and came across mathematics, I understood almost nothing.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">First, when I decided to start learning math again, I opened school textbooks, but I quickly realized that they were boring, so I need some other resources. Two years have passed since then, and now I want to share with you the best resources that helped me in my studies.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:83%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 609px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*QTDK6hdBy4ePcaYV_k9m_g.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*QTDK6hdBy4ePcaYV_k9m_g.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*QTDK6hdBy4ePcaYV_k9m_g.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*QTDK6hdBy4ePcaYV_k9m_g.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*QTDK6hdBy4ePcaYV_k9m_g.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*QTDK6hdBy4ePcaYV_k9m_g.png 1100w, https://miro.medium.com/v2/resize:fit:1218/format:webp/1*QTDK6hdBy4ePcaYV_k9m_g.png 1218w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 609px" srcset="https://miro.medium.com/v2/resize:fit:640/1*QTDK6hdBy4ePcaYV_k9m_g.png 640w, https://miro.medium.com/v2/resize:fit:720/1*QTDK6hdBy4ePcaYV_k9m_g.png 720w, https://miro.medium.com/v2/resize:fit:750/1*QTDK6hdBy4ePcaYV_k9m_g.png 750w, https://miro.medium.com/v2/resize:fit:786/1*QTDK6hdBy4ePcaYV_k9m_g.png 786w, https://miro.medium.com/v2/resize:fit:828/1*QTDK6hdBy4ePcaYV_k9m_g.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*QTDK6hdBy4ePcaYV_k9m_g.png 1100w, https://miro.medium.com/v2/resize:fit:1218/1*QTDK6hdBy4ePcaYV_k9m_g.png 1218w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:609/1*QTDK6hdBy4ePcaYV_k9m_g.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;"><a href="https://brilliant.org/" target="_self">Brilliant</a> is an interactive platform that has many courses about algebra, geometry, physics, and other fields of science. The learning method is fun and interesting, including many quizzes and a good explanation of hard topics. The first three lessons on each topic are free, but if you want to continue learning, you need to buy a subscription.</li></ol></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*QKWL8nI2ExhcIt5VrCJS7A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*QKWL8nI2ExhcIt5VrCJS7A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*QKWL8nI2ExhcIt5VrCJS7A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*QKWL8nI2ExhcIt5VrCJS7A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*QKWL8nI2ExhcIt5VrCJS7A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*QKWL8nI2ExhcIt5VrCJS7A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*QKWL8nI2ExhcIt5VrCJS7A.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*QKWL8nI2ExhcIt5VrCJS7A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*QKWL8nI2ExhcIt5VrCJS7A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*QKWL8nI2ExhcIt5VrCJS7A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*QKWL8nI2ExhcIt5VrCJS7A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*QKWL8nI2ExhcIt5VrCJS7A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*QKWL8nI2ExhcIt5VrCJS7A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*QKWL8nI2ExhcIt5VrCJS7A.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*QKWL8nI2ExhcIt5VrCJS7A.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">2. <a href="https://www.khanacademy.org/" target="_self">Khan Academy</a><strong> </strong>is a non-profit (which means is completely free) website, targeting mathematics (there are also many lessons on other topics, but math is the core theme for Khan Academy). On this resource, you can watch many lessons explaining various math topics, from elementary school to statistics, calculus, linear algebra, and solve tests to strengthen your knowledge.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:87%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 640px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*cM5kdhrXYar_tQ7NlfCh5w.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*cM5kdhrXYar_tQ7NlfCh5w.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*cM5kdhrXYar_tQ7NlfCh5w.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*cM5kdhrXYar_tQ7NlfCh5w.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*cM5kdhrXYar_tQ7NlfCh5w.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*cM5kdhrXYar_tQ7NlfCh5w.png 1100w, https://miro.medium.com/v2/resize:fit:1280/format:webp/1*cM5kdhrXYar_tQ7NlfCh5w.png 1280w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 640px" srcset="https://miro.medium.com/v2/resize:fit:640/1*cM5kdhrXYar_tQ7NlfCh5w.png 640w, https://miro.medium.com/v2/resize:fit:720/1*cM5kdhrXYar_tQ7NlfCh5w.png 720w, https://miro.medium.com/v2/resize:fit:750/1*cM5kdhrXYar_tQ7NlfCh5w.png 750w, https://miro.medium.com/v2/resize:fit:786/1*cM5kdhrXYar_tQ7NlfCh5w.png 786w, https://miro.medium.com/v2/resize:fit:828/1*cM5kdhrXYar_tQ7NlfCh5w.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*cM5kdhrXYar_tQ7NlfCh5w.png 1100w, https://miro.medium.com/v2/resize:fit:1280/1*cM5kdhrXYar_tQ7NlfCh5w.png 1280w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:640/1*cM5kdhrXYar_tQ7NlfCh5w.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">3. <a href="https://openstax.org/" target="_self">OpenStax</a><strong> </strong>is another non-profit resource. It contains textbooks on various topics, including mathematics. Yes, I remember I wrote above that textbooks are boring for me, but OpenStax books are well-written and may be a good addition to Khan Academy and Brilliant courses, so I encourage you to try them.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In addition to these three resources, I also recommend you to subscribe to YouTube channels <a href="https://www.youtube.com/c/3blue1brown" target="_self">3Blue1Brown</a> and <a href="https://www.youtube.com/c/TheMathSorcerer" target="_self">The Math Sorcerer</a>. These two channels contain a good explanation of some math topics and tips for studying.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I hope I helped you and good luck with your math studies :)</p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>