<!DOCTYPE html>
                <html>
                <head>
                    <title>ChatGPT Cheating Scandal Shocks Florida High School</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://odsc.medium.com/chatgpt-cheating-scandal-shocks-florida-high-school-c3d2372e680b"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/?source=post_page-----c3d2372e680b--------------------------------">Author : ODSC - Open Data Science</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>ChatGPT Cheating Scandal Shocks Florida High School</h3></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:81%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 600px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*rPYvwEY75lbfyQfe.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*rPYvwEY75lbfyQfe.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*rPYvwEY75lbfyQfe.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*rPYvwEY75lbfyQfe.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*rPYvwEY75lbfyQfe.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*rPYvwEY75lbfyQfe.png 1100w, https://miro.medium.com/v2/resize:fit:1200/format:webp/0*rPYvwEY75lbfyQfe.png 1200w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 600px" srcset="https://miro.medium.com/v2/resize:fit:640/0*rPYvwEY75lbfyQfe.png 640w, https://miro.medium.com/v2/resize:fit:720/0*rPYvwEY75lbfyQfe.png 720w, https://miro.medium.com/v2/resize:fit:750/0*rPYvwEY75lbfyQfe.png 750w, https://miro.medium.com/v2/resize:fit:786/0*rPYvwEY75lbfyQfe.png 786w, https://miro.medium.com/v2/resize:fit:828/0*rPYvwEY75lbfyQfe.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*rPYvwEY75lbfyQfe.png 1100w, https://miro.medium.com/v2/resize:fit:1200/0*rPYvwEY75lbfyQfe.png 1200w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:600/0*rPYvwEY75lbfyQfe.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">An NBC <a href="https://nbc-2.com/news/local/2023/02/15/students-at-cape-coral-high-school-accused-of-using-artificial-intelligence-to-cheat-on-essay/amp/" target="_self">affiliate</a> in south Florida is reporting that a cheating scandal has erupted at Cape Coral High School involving the use of ChatGPT, a popular language model used for answering questions and completing assignments. It seems that several students have been caught using the AI-powered tool to cheat on tests and assignments. This an issue educators <a href="https://opendatascience.com/could-ai-powered-tools-such-as-chatgpt-provide-students-with-an-unfair-advantage/" target="_self">have warned</a> about since AI’s ascendance into the public imagination in late 2022.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The scandal came to light after a teacher noticed similarities in the responses of multiple students on an assignment. The teacher investigated further and discovered that the students had all used ChatGPT to complete the assignment. The school launched an investigation, and it was revealed that several other students had also used the tool to cheat on tests and other assignments. A program coordinator at the school wrote to parents, “<em>There have been some IB papers submitted that are questionable in a few ways… including being very different styles of writing from previously submitted papers.”</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The use of AI-powered tools for cheating is a growing problem in schools across the country. While ChatGPT is designed to provide helpful responses to questions, it can also be used to cheat by generating answers that are not the student’s own work. This is an issue that OpenAI, ChatGPT creator, wanted to get ahead of with their own <a href="https://opendatascience.com/new-app-can-detect-if-an-essay-was-authored-by-ai/" target="_self">AI-detection tool for educators</a>. But it seems that the problem is getting ahead of both groups.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So far, the school has taken action to address the cheating scandal, including notifying parents and implementing stricter measures to prevent cheating in the future. However, this incident highlights how quickly AI is disrupting certain sectors, and the need for educators to keep up with current technology trends. Though AI, in this form, is quite new, the desire to use tools to cheat is as old as public education. So it’s no surprise that students have evolved with what is available to them.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">OpenAI, ChatGPT’s developers, have also expressed <a href="https://opendatascience.com/new-app-can-detect-if-an-essay-was-authored-by-ai/" target="_self">concern</a> about the misuse of their product for cheating. They have stated that the tool is designed to assist students in their learning and not to provide answers to assignments or tests. They are working on implementing measures to prevent the misuse of the tool and have advised educators to be vigilant and take steps to prevent cheating.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Either way, with AI’s presence in our daily lives growing in scale, the importance of the field of <a href="https://opendatascience.com/odsc-west-2022-keynote-kay-firth-butterfield-on-responsible-ai-in-government-and-business/" target="_self">responsible AI</a> will also continue to grow. If you’re interested in the ethics behind artificial intelligence, then join us at ODSC East 2023 for the <a href="https://odsc.com/boston/responsible-ai/?__hstc=39712252.8eec8d7f5738faf6416f0c6bad9fe9a5.1634042255273.1677774737943.1677780716047.1044&__hssc=39712252.21.1677780716047&__hsfp=901111203" target="_self">Responsible AI Track</a>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://opendatascience.com/chatgpt-cheating-scandal-shocks-florida-high-school/" target="_self">Originally posted on OpenDataScience.com</a></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Read more data science articles on </em><a href="https://opendatascience.com/?source=post_page---------------------------" target="_self">OpenDataScience.com</a><em>, including tutorials and guides from beginner to advanced levels! </em><a href="https://opendatascience.com/newsletter/?source=post_page---------------------------" target="_self">Subscribe to our weekly newsletter here</a><em> and receive the latest news every Thursday. You can also get data science training on-demand wherever you are with our </em><a href="https://aiplus.odsc.com/" target="_self">Ai+ Training</a><em> platform. Subscribe to our fast-growing Medium Publication too, the </em><a href="https://medium.com/odscjournal" target="_self">ODSC Journal</a><em>, and inquire about becoming a writer.</em></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>