<!DOCTYPE html>
                <html>
                <head>
                    <title>Combinations vs Permutations</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/i-math/combinations-permutations-fa7ac680f0ac"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@brettelizabethberry?source=post_page-----fa7ac680f0ac--------------------------------">Author : Brett Berry</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7">Intro to Combinatorics</h4></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Combinations vs Permutations</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>We throw around the term “combination</em><strong>”</strong><em> loosely, and usually in the wrong way. We say things like, “Hey, what’s your locker combination?” but what we really ought to be sayings is “Hey, what’s your locker </em><strong>permutation</strong><em>?”</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>So what’s the difference? And what exactly is a permutation? Watch or read on :)</em></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:80%;"><iframe  scrolling="auto" width="854.0" height="480.0" frameborder="0" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FssoTzwA_Aug%3Ffeature%3Doembed&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DssoTzwA_Aug&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FssoTzwA_Aug%2Fhqdefault.jpg&key=a19fcc184b9711e1b4764040d3dc5c07&type=text%2Fhtml&schema=youtube" allowfullscreen=""></iframe></div><br><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;"><a href="https://www.youtube.com/c/mathhacks?sub_confirmation=1" target="_self">Click here to subscribe to Math Hacks</a></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">How To Tell the Difference</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The difference between combinations and permutations is ordering. <mark>With permutations we care about the order of the elements, whereas with combinations we don’t.</mark></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">For example, say your locker “combo” is 5432. If you enter 4325 into your locker it won’t open because it is a different ordering (aka permutation).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The <strong>permutations</strong> of 2, 3, 4, 5 are:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ul><li class="ff3" style="font-size:22px;"><strong>5432,</strong> 5423, 5324, 5342, 5234, 5243, 4532, 4523, 4325, 4352, 4253, 4235, 3542, 3524, 3425, 3452, 3254, 3245, 2543, 2534, 2435, 2453, 2354, 2345</li></ul></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Your locker “combo” is a specific permutation of 2, 3, 4 and 5. If your locker worked truly by combination, you could enter any of the above permutations and it would open!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Calculating Permutations with Ease</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Suppose you want to know how many permutations exist of the numbers 2, 3, 4, 5 without listing them like I did above. How would you accomplish this?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Let’s use a line diagram to help us visualize the problem.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We want to find how many possible 4-digit permutations can be made from four distinct numbers. Begin by drawing four lines to represent the 4 digits.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:68%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 509px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 1100w, https://miro.medium.com/v2/resize:fit:1018/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 1018w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 509px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Y4F7mIVnPxMSds9Y5Vdrng.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Y4F7mIVnPxMSds9Y5Vdrng.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Y4F7mIVnPxMSds9Y5Vdrng.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Y4F7mIVnPxMSds9Y5Vdrng.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Y4F7mIVnPxMSds9Y5Vdrng.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Y4F7mIVnPxMSds9Y5Vdrng.png 1100w, https://miro.medium.com/v2/resize:fit:1018/1*Y4F7mIVnPxMSds9Y5Vdrng.png 1018w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:509/1*Y4F7mIVnPxMSds9Y5Vdrng.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The first digit can be any of the 4 numbers, so place a “4” in the first blank.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:69%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 513px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*FrB_WhfLRLHLmIGWQaGkVA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*FrB_WhfLRLHLmIGWQaGkVA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*FrB_WhfLRLHLmIGWQaGkVA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*FrB_WhfLRLHLmIGWQaGkVA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*FrB_WhfLRLHLmIGWQaGkVA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*FrB_WhfLRLHLmIGWQaGkVA.png 1100w, https://miro.medium.com/v2/resize:fit:1026/format:webp/1*FrB_WhfLRLHLmIGWQaGkVA.png 1026w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 513px" srcset="https://miro.medium.com/v2/resize:fit:640/1*FrB_WhfLRLHLmIGWQaGkVA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*FrB_WhfLRLHLmIGWQaGkVA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*FrB_WhfLRLHLmIGWQaGkVA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*FrB_WhfLRLHLmIGWQaGkVA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*FrB_WhfLRLHLmIGWQaGkVA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*FrB_WhfLRLHLmIGWQaGkVA.png 1100w, https://miro.medium.com/v2/resize:fit:1026/1*FrB_WhfLRLHLmIGWQaGkVA.png 1026w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:513/1*FrB_WhfLRLHLmIGWQaGkVA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now there are 3 options left for the second blank because you’ve already used one of the numbers in the first blank. Place a “3” in the next space.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:66%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 493px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*3Yub5OQQieyLAlq8iIUFcQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*3Yub5OQQieyLAlq8iIUFcQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*3Yub5OQQieyLAlq8iIUFcQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*3Yub5OQQieyLAlq8iIUFcQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*3Yub5OQQieyLAlq8iIUFcQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*3Yub5OQQieyLAlq8iIUFcQ.png 1100w, https://miro.medium.com/v2/resize:fit:986/format:webp/1*3Yub5OQQieyLAlq8iIUFcQ.png 986w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 493px" srcset="https://miro.medium.com/v2/resize:fit:640/1*3Yub5OQQieyLAlq8iIUFcQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*3Yub5OQQieyLAlq8iIUFcQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*3Yub5OQQieyLAlq8iIUFcQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*3Yub5OQQieyLAlq8iIUFcQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*3Yub5OQQieyLAlq8iIUFcQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*3Yub5OQQieyLAlq8iIUFcQ.png 1100w, https://miro.medium.com/v2/resize:fit:986/1*3Yub5OQQieyLAlq8iIUFcQ.png 986w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:493/1*3Yub5OQQieyLAlq8iIUFcQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">For the third position, you have two numbers left.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:69%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 514px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*8n2ZRi2Xnpw9YosrSCanwQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*8n2ZRi2Xnpw9YosrSCanwQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*8n2ZRi2Xnpw9YosrSCanwQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*8n2ZRi2Xnpw9YosrSCanwQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*8n2ZRi2Xnpw9YosrSCanwQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*8n2ZRi2Xnpw9YosrSCanwQ.png 1100w, https://miro.medium.com/v2/resize:fit:1028/format:webp/1*8n2ZRi2Xnpw9YosrSCanwQ.png 1028w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 514px" srcset="https://miro.medium.com/v2/resize:fit:640/1*8n2ZRi2Xnpw9YosrSCanwQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*8n2ZRi2Xnpw9YosrSCanwQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*8n2ZRi2Xnpw9YosrSCanwQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*8n2ZRi2Xnpw9YosrSCanwQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*8n2ZRi2Xnpw9YosrSCanwQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*8n2ZRi2Xnpw9YosrSCanwQ.png 1100w, https://miro.medium.com/v2/resize:fit:1028/1*8n2ZRi2Xnpw9YosrSCanwQ.png 1028w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:514/1*8n2ZRi2Xnpw9YosrSCanwQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">And there is one number left for the last position, so place a “1” there.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:68%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 504px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*6ADwMaU8fIcAd4dT3Cnq0g.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*6ADwMaU8fIcAd4dT3Cnq0g.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*6ADwMaU8fIcAd4dT3Cnq0g.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*6ADwMaU8fIcAd4dT3Cnq0g.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*6ADwMaU8fIcAd4dT3Cnq0g.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*6ADwMaU8fIcAd4dT3Cnq0g.png 1100w, https://miro.medium.com/v2/resize:fit:1008/format:webp/1*6ADwMaU8fIcAd4dT3Cnq0g.png 1008w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 504px" srcset="https://miro.medium.com/v2/resize:fit:640/1*6ADwMaU8fIcAd4dT3Cnq0g.png 640w, https://miro.medium.com/v2/resize:fit:720/1*6ADwMaU8fIcAd4dT3Cnq0g.png 720w, https://miro.medium.com/v2/resize:fit:750/1*6ADwMaU8fIcAd4dT3Cnq0g.png 750w, https://miro.medium.com/v2/resize:fit:786/1*6ADwMaU8fIcAd4dT3Cnq0g.png 786w, https://miro.medium.com/v2/resize:fit:828/1*6ADwMaU8fIcAd4dT3Cnq0g.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*6ADwMaU8fIcAd4dT3Cnq0g.png 1100w, https://miro.medium.com/v2/resize:fit:1008/1*6ADwMaU8fIcAd4dT3Cnq0g.png 1008w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:504/1*6ADwMaU8fIcAd4dT3Cnq0g.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7">The Multiplication Principle</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Using the <em>Multiplication Principle of combinatorics,</em> we know that if there are <em>x</em> ways of doing one thing and <em>y</em> ways of doing another, then the total number of ways of doing both things is <em>x•y</em>. That means we need to multiply to find the total permutations.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This is a great opportunity to use shorthand <strong>factorial notation (!)</strong>:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*qRPnSJlZeZL-nFGupZ22aQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*qRPnSJlZeZL-nFGupZ22aQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*qRPnSJlZeZL-nFGupZ22aQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*qRPnSJlZeZL-nFGupZ22aQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*qRPnSJlZeZL-nFGupZ22aQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*qRPnSJlZeZL-nFGupZ22aQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*qRPnSJlZeZL-nFGupZ22aQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*qRPnSJlZeZL-nFGupZ22aQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*qRPnSJlZeZL-nFGupZ22aQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*qRPnSJlZeZL-nFGupZ22aQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*qRPnSJlZeZL-nFGupZ22aQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*qRPnSJlZeZL-nFGupZ22aQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*qRPnSJlZeZL-nFGupZ22aQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*qRPnSJlZeZL-nFGupZ22aQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*qRPnSJlZeZL-nFGupZ22aQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">There are 24 permutations, which matches the listing we made at the beginning of this post.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Permutations with Repetition</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">What if I wanted to find the total number of permutations involving the numbers 2, 3, 4, and 5 but want to include orderings such as 5555 or 2234 where not all of the numbers are used, and some are used more than once?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>How many of these permutations exist?</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This turns out to be a simple calculation. Again we are composing a 4-digit number, so draw 4 lines to represent the digits.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:68%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 509px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 1100w, https://miro.medium.com/v2/resize:fit:1018/format:webp/1*Y4F7mIVnPxMSds9Y5Vdrng.png 1018w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 509px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Y4F7mIVnPxMSds9Y5Vdrng.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Y4F7mIVnPxMSds9Y5Vdrng.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Y4F7mIVnPxMSds9Y5Vdrng.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Y4F7mIVnPxMSds9Y5Vdrng.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Y4F7mIVnPxMSds9Y5Vdrng.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Y4F7mIVnPxMSds9Y5Vdrng.png 1100w, https://miro.medium.com/v2/resize:fit:1018/1*Y4F7mIVnPxMSds9Y5Vdrng.png 1018w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:509/1*Y4F7mIVnPxMSds9Y5Vdrng.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In the first position we have 4 number options, so like before place a “4” in the first blank. Since we are allowed to reuse numbers, we now have 4 number options available for the second digit, third digit, and fourth digit as well.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">That’s the same as:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*vt9ECotPOLv1WYiJA02FxQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*vt9ECotPOLv1WYiJA02FxQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*vt9ECotPOLv1WYiJA02FxQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*vt9ECotPOLv1WYiJA02FxQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*vt9ECotPOLv1WYiJA02FxQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*vt9ECotPOLv1WYiJA02FxQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*vt9ECotPOLv1WYiJA02FxQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*vt9ECotPOLv1WYiJA02FxQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*vt9ECotPOLv1WYiJA02FxQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*vt9ECotPOLv1WYiJA02FxQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*vt9ECotPOLv1WYiJA02FxQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*vt9ECotPOLv1WYiJA02FxQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*vt9ECotPOLv1WYiJA02FxQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*vt9ECotPOLv1WYiJA02FxQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*vt9ECotPOLv1WYiJA02FxQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">By allowing numbers to be repeated, we end up with 256 permutations!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Choosing a Subset</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Let’s up the ante with a more challenging problem:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>How many different 5-card hands can be made from a standard deck of cards?</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In this problem the order is irrelevant since it doesn’t matter what order we select the cards.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We’ll begin with five lines to represent our 5-card hand.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*bDhJ4kIPVJHom-IRWL36JA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*bDhJ4kIPVJHom-IRWL36JA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*bDhJ4kIPVJHom-IRWL36JA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*bDhJ4kIPVJHom-IRWL36JA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*bDhJ4kIPVJHom-IRWL36JA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*bDhJ4kIPVJHom-IRWL36JA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*bDhJ4kIPVJHom-IRWL36JA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*bDhJ4kIPVJHom-IRWL36JA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*bDhJ4kIPVJHom-IRWL36JA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*bDhJ4kIPVJHom-IRWL36JA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*bDhJ4kIPVJHom-IRWL36JA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*bDhJ4kIPVJHom-IRWL36JA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*bDhJ4kIPVJHom-IRWL36JA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*bDhJ4kIPVJHom-IRWL36JA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*bDhJ4kIPVJHom-IRWL36JA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Assuming no one else is drawing cards from the deck, there are 52 cards available on the first draw, so place “52” in the first blank.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Once you choose a card, there will be one less card available on the next draw. So the second blank will have 51 options. The next draw will have two less cards in the deck, so there are now 50 options, and so on.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*SRJuOmcsnQlLj3GnBShuIQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*SRJuOmcsnQlLj3GnBShuIQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*SRJuOmcsnQlLj3GnBShuIQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*SRJuOmcsnQlLj3GnBShuIQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*SRJuOmcsnQlLj3GnBShuIQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*SRJuOmcsnQlLj3GnBShuIQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*SRJuOmcsnQlLj3GnBShuIQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*SRJuOmcsnQlLj3GnBShuIQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*SRJuOmcsnQlLj3GnBShuIQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*SRJuOmcsnQlLj3GnBShuIQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*SRJuOmcsnQlLj3GnBShuIQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*SRJuOmcsnQlLj3GnBShuIQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*SRJuOmcsnQlLj3GnBShuIQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*SRJuOmcsnQlLj3GnBShuIQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*SRJuOmcsnQlLj3GnBShuIQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">That’s 311,875,200 <em>permutations</em>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">That’s permutations, not combinations. To fix this we need to divide by the number of hands that are different permutations but the same combination.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This is the same as saying <em>how many different ways can I arrange 5 cards?</em></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*hZYHw0aPSQi3Kosg5tLv9A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*hZYHw0aPSQi3Kosg5tLv9A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*hZYHw0aPSQi3Kosg5tLv9A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*hZYHw0aPSQi3Kosg5tLv9A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*hZYHw0aPSQi3Kosg5tLv9A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*hZYHw0aPSQi3Kosg5tLv9A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*hZYHw0aPSQi3Kosg5tLv9A.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*hZYHw0aPSQi3Kosg5tLv9A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*hZYHw0aPSQi3Kosg5tLv9A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*hZYHw0aPSQi3Kosg5tLv9A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*hZYHw0aPSQi3Kosg5tLv9A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*hZYHw0aPSQi3Kosg5tLv9A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*hZYHw0aPSQi3Kosg5tLv9A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*hZYHw0aPSQi3Kosg5tLv9A.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*hZYHw0aPSQi3Kosg5tLv9A.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;"><em>Note: This is mathematically similar to finding the different permutations of our locker combo</em></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So the number of five-card hands combinations is:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*gUGiA9R_p5uymfeacclkAw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*gUGiA9R_p5uymfeacclkAw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*gUGiA9R_p5uymfeacclkAw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*gUGiA9R_p5uymfeacclkAw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*gUGiA9R_p5uymfeacclkAw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*gUGiA9R_p5uymfeacclkAw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*gUGiA9R_p5uymfeacclkAw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*gUGiA9R_p5uymfeacclkAw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*gUGiA9R_p5uymfeacclkAw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*gUGiA9R_p5uymfeacclkAw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*gUGiA9R_p5uymfeacclkAw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*gUGiA9R_p5uymfeacclkAw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*gUGiA9R_p5uymfeacclkAw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*gUGiA9R_p5uymfeacclkAw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*gUGiA9R_p5uymfeacclkAw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Rewriting with Factorials</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">With a little ingenuity we can rewrite the above calculation using factorials.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We know 52! = 52•51•50•…•3•2•1, but we only need the products of the integers from 52 to 48. How can we isolate just those integers?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We’d like to divide out all the integers except those from 48 to 52. To do this divide by 47! since it’s the product of the integers from 47 to 1.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*QHWK5sy9YX3a0j6jSNvOLw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*QHWK5sy9YX3a0j6jSNvOLw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*QHWK5sy9YX3a0j6jSNvOLw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*QHWK5sy9YX3a0j6jSNvOLw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*QHWK5sy9YX3a0j6jSNvOLw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*QHWK5sy9YX3a0j6jSNvOLw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*QHWK5sy9YX3a0j6jSNvOLw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*QHWK5sy9YX3a0j6jSNvOLw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*QHWK5sy9YX3a0j6jSNvOLw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*QHWK5sy9YX3a0j6jSNvOLw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*QHWK5sy9YX3a0j6jSNvOLw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*QHWK5sy9YX3a0j6jSNvOLw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*QHWK5sy9YX3a0j6jSNvOLw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*QHWK5sy9YX3a0j6jSNvOLw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*QHWK5sy9YX3a0j6jSNvOLw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Make sure to divide by<strong> 5!</strong> to get rid of the extra permutations:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:32%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 254px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*BAkJ645c6yt4-IJZifGC_A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*BAkJ645c6yt4-IJZifGC_A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*BAkJ645c6yt4-IJZifGC_A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*BAkJ645c6yt4-IJZifGC_A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*BAkJ645c6yt4-IJZifGC_A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*BAkJ645c6yt4-IJZifGC_A.png 1100w, https://miro.medium.com/v2/resize:fit:508/format:webp/1*BAkJ645c6yt4-IJZifGC_A.png 508w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 254px" srcset="https://miro.medium.com/v2/resize:fit:640/1*BAkJ645c6yt4-IJZifGC_A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*BAkJ645c6yt4-IJZifGC_A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*BAkJ645c6yt4-IJZifGC_A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*BAkJ645c6yt4-IJZifGC_A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*BAkJ645c6yt4-IJZifGC_A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*BAkJ645c6yt4-IJZifGC_A.png 1100w, https://miro.medium.com/v2/resize:fit:508/1*BAkJ645c6yt4-IJZifGC_A.png 508w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:254/1*BAkJ645c6yt4-IJZifGC_A.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">There we go!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now here’s the cool part → we have actually derived the formula for <strong>combinations.</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Combinations Formula</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If we have <em>n </em>objects and we want to choose <em>k </em>of them<em>, </em>we can find the total number of combinations by using the following formula:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:93%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 684px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*rjxvbR1YNhWVR-BWC0nlPg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*rjxvbR1YNhWVR-BWC0nlPg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*rjxvbR1YNhWVR-BWC0nlPg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*rjxvbR1YNhWVR-BWC0nlPg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*rjxvbR1YNhWVR-BWC0nlPg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*rjxvbR1YNhWVR-BWC0nlPg.png 1100w, https://miro.medium.com/v2/resize:fit:1368/format:webp/1*rjxvbR1YNhWVR-BWC0nlPg.png 1368w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 684px" srcset="https://miro.medium.com/v2/resize:fit:640/1*rjxvbR1YNhWVR-BWC0nlPg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*rjxvbR1YNhWVR-BWC0nlPg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*rjxvbR1YNhWVR-BWC0nlPg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*rjxvbR1YNhWVR-BWC0nlPg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*rjxvbR1YNhWVR-BWC0nlPg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*rjxvbR1YNhWVR-BWC0nlPg.png 1100w, https://miro.medium.com/v2/resize:fit:1368/1*rjxvbR1YNhWVR-BWC0nlPg.png 1368w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:684/1*rjxvbR1YNhWVR-BWC0nlPg.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">read: “n choose k”</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">For example, we have 52 cards (n=52) and want to know how many 5-card hands (k=5) we can make.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Plugging in the values we get:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*wI2iFgW8wXQtnN_IEKVZKw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*wI2iFgW8wXQtnN_IEKVZKw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*wI2iFgW8wXQtnN_IEKVZKw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*wI2iFgW8wXQtnN_IEKVZKw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*wI2iFgW8wXQtnN_IEKVZKw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*wI2iFgW8wXQtnN_IEKVZKw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*wI2iFgW8wXQtnN_IEKVZKw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*wI2iFgW8wXQtnN_IEKVZKw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*wI2iFgW8wXQtnN_IEKVZKw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*wI2iFgW8wXQtnN_IEKVZKw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*wI2iFgW8wXQtnN_IEKVZKw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*wI2iFgW8wXQtnN_IEKVZKw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*wI2iFgW8wXQtnN_IEKVZKw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*wI2iFgW8wXQtnN_IEKVZKw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*wI2iFgW8wXQtnN_IEKVZKw.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">note: (52–5)! = 47!</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Which is exactly what we found above!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Often times you’ll see this formula written in parenthesis notation, like above, but some books write it with a giant C:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*g9CqKu23N4Db7BUr5ko83A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*g9CqKu23N4Db7BUr5ko83A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*g9CqKu23N4Db7BUr5ko83A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*g9CqKu23N4Db7BUr5ko83A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*g9CqKu23N4Db7BUr5ko83A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*g9CqKu23N4Db7BUr5ko83A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*g9CqKu23N4Db7BUr5ko83A.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*g9CqKu23N4Db7BUr5ko83A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*g9CqKu23N4Db7BUr5ko83A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*g9CqKu23N4Db7BUr5ko83A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*g9CqKu23N4Db7BUr5ko83A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*g9CqKu23N4Db7BUr5ko83A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*g9CqKu23N4Db7BUr5ko83A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*g9CqKu23N4Db7BUr5ko83A.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*g9CqKu23N4Db7BUr5ko83A.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Various notations for the combinations formula</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Permutations Formula</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The formula for permutations is similar to the combinations formula, except we needn’t divide out the permutations, so we can remove k! from the denominator:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*2BBrX8ej5ZIZaKR1znXmZQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*2BBrX8ej5ZIZaKR1znXmZQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*2BBrX8ej5ZIZaKR1znXmZQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*2BBrX8ej5ZIZaKR1znXmZQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*2BBrX8ej5ZIZaKR1znXmZQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*2BBrX8ej5ZIZaKR1znXmZQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*2BBrX8ej5ZIZaKR1znXmZQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*2BBrX8ej5ZIZaKR1znXmZQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*2BBrX8ej5ZIZaKR1znXmZQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*2BBrX8ej5ZIZaKR1znXmZQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*2BBrX8ej5ZIZaKR1znXmZQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*2BBrX8ej5ZIZaKR1znXmZQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*2BBrX8ej5ZIZaKR1znXmZQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*2BBrX8ej5ZIZaKR1znXmZQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*2BBrX8ej5ZIZaKR1znXmZQ.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">read: n permutate k elements</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Alright, there you go! A quick run-down of the basics of combinatorics. Hope this helps you out :)</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:80%;"><iframe  scrolling="auto" width="854.0" height="480.0" frameborder="0" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FssoTzwA_Aug%3Ffeature%3Doembed&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DssoTzwA_Aug&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FssoTzwA_Aug%2Fhqdefault.jpg&key=a19fcc184b9711e1b4764040d3dc5c07&type=text%2Fhtml&schema=youtube" allowfullscreen=""></iframe></div><br><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7">❤ STAY CONNECTED ❤</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Stay up-to-date with everything Math Hacks is up to!</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><a href="https://www.instagram.com/mathhacksco" target="_self">Instagram</a> | <a href="https://www.facebook.com/Math-Hacks-513137915801590" target="_self">Facebook</a> | <a href="https://twitter.com/mathhacksco" target="_self">Twitter</a></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://www.youtube.com/c/mathhacks"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Math Hacks on YouTube</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Welcome to Season Two of Math Hacks! This season we'll be covering topics from Algebra and Trigonometry as well as…</h3><p>www.youtube.com</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7">More Math Stuff →</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://medium.com/i-math/top-10-secrets-of-pascals-triangle-6012ba9c5e23"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Top 10 Secrets of Pascal’s Triangle</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Binomial Theorem, Fibonacci Sequence, Sierpinski Triangle & More</h3><p>medium.com</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://medium.com/i-math/the-zero-power-rule-explained-449b4bd6934d"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">The “ Zero Power Rule” Explained</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Exponents seem pretty straightforward, right? Raise a number to the power of 1 means you have one of that number, raise…</h3><p>medium.com</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://medium.com/i-math/how-to-complete-the-square-8ca76a416972"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">How To “Complete the Square”</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">and the Trouble with Memorization</h3><p>medium.com</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://medium.com/i-math/intro-to-modular-arithmetic-34ad9d4537d1"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Intro to Modular Arithmetic</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">and Equivalence Classes</h3><p>medium.com</p></a></div></div></div></div></section><br><?php include_once 'Elemental/footer.php'; ?>