<!DOCTYPE html>
                <html>
                <head>
                    <title>Confusion Matrix, Accuracy, Precision, Recall, F1 Score</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/analytics-vidhya/confusion-matrix-accuracy-precision-recall-f1-score-ade299cf63cd"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@harikrishnannb?source=post_page-----ade299cf63cd--------------------------------">Author : Harikrishnan N B</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Confusion Matrix, Accuracy, Precision, Recall, F1 Score</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5 text-muted">Binary Classification Metric</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7"><strong>How to evaluate the performance of a machine learning model?</strong></h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Let us consider a task to classify whether a person is <strong>pregnant</strong> or <strong>not pregnant</strong>. If the test for pregnancy is positive (+ve ), then the person is pregnant. On the other hand, if the test for pregnancy is negative (-ve) then the person is not pregnant.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now consider the above classification ( pregnant or not pregnant ) carried out by a machine learning algorithm. The output of the machine learning algorithm can be mapped to one of the following categories.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;">A person who is actually pregnant (positive) and classified as pregnant (positive). This is called <strong>TRUE POSITIVE (TP).</strong></li></ol></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:40%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 309px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:618/format:webp/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 618w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 309px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:618/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg 618w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:309/1*Q6-K7WYnNNw0no2AwgQCTg.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Figure 1: True Positive.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">2. A person who is actually not pregnant (negative) and classified as not pregnant (negative). This is called <strong>TRUE NEGATIVE (TN).</strong></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:51%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 390px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 1100w, https://miro.medium.com/v2/resize:fit:780/format:webp/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 780w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 390px" srcset="https://miro.medium.com/v2/resize:fit:640/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 1100w, https://miro.medium.com/v2/resize:fit:780/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg 780w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:390/1*ptuWd5YIkY8owxVvyGL_Ug.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Figure 2: True Negative.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">3. A person who is actually not pregnant (negative) and classified as pregnant (positive). This is called <strong>FALSE POSITIVE (FP).</strong></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:53%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 401px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 1100w, https://miro.medium.com/v2/resize:fit:802/format:webp/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 802w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 401px" srcset="https://miro.medium.com/v2/resize:fit:640/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 1100w, https://miro.medium.com/v2/resize:fit:802/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg 802w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:401/1*PPVyz2ZdiHfsykqlS2Zpmw.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Figure 3: False Positive.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">4. A person who is actually pregnant (positive) and classified as not pregnant (negative). This is called <strong>FALSE NEGATIVE (FN).</strong></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:42%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 326px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*UShjXzBZQFeDMtc3d0viPw.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*UShjXzBZQFeDMtc3d0viPw.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*UShjXzBZQFeDMtc3d0viPw.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*UShjXzBZQFeDMtc3d0viPw.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*UShjXzBZQFeDMtc3d0viPw.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*UShjXzBZQFeDMtc3d0viPw.jpeg 1100w, https://miro.medium.com/v2/resize:fit:652/format:webp/1*UShjXzBZQFeDMtc3d0viPw.jpeg 652w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 326px" srcset="https://miro.medium.com/v2/resize:fit:640/1*UShjXzBZQFeDMtc3d0viPw.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*UShjXzBZQFeDMtc3d0viPw.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*UShjXzBZQFeDMtc3d0viPw.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*UShjXzBZQFeDMtc3d0viPw.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*UShjXzBZQFeDMtc3d0viPw.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*UShjXzBZQFeDMtc3d0viPw.jpeg 1100w, https://miro.medium.com/v2/resize:fit:652/1*UShjXzBZQFeDMtc3d0viPw.jpeg 652w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:326/1*UShjXzBZQFeDMtc3d0viPw.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Figure 4. False Negative.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">What we desire is <strong>TRUE POSITIVE</strong> and <strong>TRUE NEGATIVE</strong> but due to the misclassifications, we may also end up in <strong>FALSE POSITIVE</strong> and <strong>FALSE NEGATIVE. </strong>So there is a confusion in classifying whether a person is pregnant or not. This is because no machine learning algorithm is perfect. Soon we will describe this confusion in classifying the data in a matrix called confusion matrix.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now, we select 100 people which includes pregnant women, not pregnant women and men with fat belly. Let us assume out of this 100 people 40 are pregnant and the remaining 60 people include not pregnant women and men with fat belly. We now use a machine learning algorithm to predict the outcome. The predicted outcome (pregnancy +ve or -ve) using a machine learning algorithm is termed as the <strong>predicted label</strong> and the true outcome (in this case which we know from doctor’s/expert’s record) is termed as the <strong>true label</strong>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now we will introduce the <strong>confusion matrix</strong> which is required to compute the <strong>accuracy</strong> of the machine learning algorithm in classifying the data into its corresponding labels.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*UcjYCTujXzmVohL7xU1s4w.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*UcjYCTujXzmVohL7xU1s4w.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*UcjYCTujXzmVohL7xU1s4w.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*UcjYCTujXzmVohL7xU1s4w.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*UcjYCTujXzmVohL7xU1s4w.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*UcjYCTujXzmVohL7xU1s4w.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*UcjYCTujXzmVohL7xU1s4w.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*UcjYCTujXzmVohL7xU1s4w.png 640w, https://miro.medium.com/v2/resize:fit:720/1*UcjYCTujXzmVohL7xU1s4w.png 720w, https://miro.medium.com/v2/resize:fit:750/1*UcjYCTujXzmVohL7xU1s4w.png 750w, https://miro.medium.com/v2/resize:fit:786/1*UcjYCTujXzmVohL7xU1s4w.png 786w, https://miro.medium.com/v2/resize:fit:828/1*UcjYCTujXzmVohL7xU1s4w.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*UcjYCTujXzmVohL7xU1s4w.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*UcjYCTujXzmVohL7xU1s4w.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*UcjYCTujXzmVohL7xU1s4w.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:84%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 618px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*RAjgF3akuC47Le0iGfZ2_A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*RAjgF3akuC47Le0iGfZ2_A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*RAjgF3akuC47Le0iGfZ2_A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*RAjgF3akuC47Le0iGfZ2_A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*RAjgF3akuC47Le0iGfZ2_A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*RAjgF3akuC47Le0iGfZ2_A.png 1100w, https://miro.medium.com/v2/resize:fit:1236/format:webp/1*RAjgF3akuC47Le0iGfZ2_A.png 1236w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 618px" srcset="https://miro.medium.com/v2/resize:fit:640/1*RAjgF3akuC47Le0iGfZ2_A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*RAjgF3akuC47Le0iGfZ2_A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*RAjgF3akuC47Le0iGfZ2_A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*RAjgF3akuC47Le0iGfZ2_A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*RAjgF3akuC47Le0iGfZ2_A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*RAjgF3akuC47Le0iGfZ2_A.png 1100w, https://miro.medium.com/v2/resize:fit:1236/1*RAjgF3akuC47Le0iGfZ2_A.png 1236w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:618/1*RAjgF3akuC47Le0iGfZ2_A.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The following diagram illustrates the confusion matrix for a binary classification problem.</p></div></div></div></section><section data-bs-version="5.1" class="gallery3 cid-ttaWMCQCls" id="gallery3-7" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container" style="width:60%;"><div class="row mt-4">
            <div class="item features-image сol-12 col-md-6 col-lg-6">
                <div class="item-wrapper" >
                    <div class="item-img"><img src ="https://miro.medium.com/v2/resize:fit:984/format:webp/1*f5ZeXvhsNFZ4q91M4Lotgg.jpeg" style="height:auto; max-width: 100%;"></div></div></div><br>
            <div class="item features-image сol-12 col-md-6 col-lg-6">
                <div class="item-wrapper" >
                    <div class="item-img"><img src ="https://miro.medium.com/v2/resize:fit:1018/format:webp/1*5CATnJ2FyNOF9xTpJ7qA5w.jpeg" style="height:auto; max-width: 100%;"></div></div></div><br><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Figure 5: Confusion Matrix.</p><br></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We will now go back to the earlier example of classifying 100 people (which includes 40 pregnant women and the remaining 60 are not pregnant women and men with a fat belly) as pregnant or not pregnant. Out of 40 pregnant women 30 pregnant women are classified correctly and the remaining 10 pregnant women are classified as not pregnant by the machine learning algorithm. On the other hand, out of 60 people in the not pregnant category, 55 are classified as not pregnant and the remaining 5 are classified as pregnant.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In this case, <strong>TN</strong> = 55,<strong> FP</strong> = 5, <strong>FN</strong> = 10, <strong>TP</strong> = 30. The confusion matrix is as follows.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*Qn9aixzYGKIBB62QrQPfNQ.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Figure 6: Confusion matrix for the pregnant vs not pregnant classification.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7">What is the <strong>accuracy</strong> of the machine learning model for this classification task?</h4></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*gFW6rXbctrhWHxD8OXi4wg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*gFW6rXbctrhWHxD8OXi4wg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*gFW6rXbctrhWHxD8OXi4wg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*gFW6rXbctrhWHxD8OXi4wg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*gFW6rXbctrhWHxD8OXi4wg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*gFW6rXbctrhWHxD8OXi4wg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*gFW6rXbctrhWHxD8OXi4wg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*gFW6rXbctrhWHxD8OXi4wg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*gFW6rXbctrhWHxD8OXi4wg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*gFW6rXbctrhWHxD8OXi4wg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*gFW6rXbctrhWHxD8OXi4wg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*gFW6rXbctrhWHxD8OXi4wg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*gFW6rXbctrhWHxD8OXi4wg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*gFW6rXbctrhWHxD8OXi4wg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*gFW6rXbctrhWHxD8OXi4wg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Accuracy represents the number of correctly classified data instances over the total number of data instances.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In this example, Accuracy = (55 + 30)/(55 + 5 + 30 + 10 ) = 0.85 and in percentage the accuracy will be 85%.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7">Is accuracy the best measure?</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Accuracy may not be a good measure if the dataset is not balanced (both negative and positive classes have different number of data instances). We will explain this with an example.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Consider the following scenario: There are 90 people who are healthy (negative) and 10 people who have some disease (positive). Now let’s say our machine learning model perfectly classified the 90 people as healthy but it also classified the unhealthy people as healthy. What will happen in this scenario? Let us see the confusion matrix and find out the accuracy?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In this example, <strong>TN</strong> = 90, <strong>FP</strong> = 0, <strong>FN </strong>= 10 and <strong>TP</strong> = 0. The confusion matrix is as follows.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*1cFV9vNv1RgW7m211Nv1yQ.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Figure 7: Confusion matrix for healthy vs unhealthy people classification task.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Accuracy in this case will be (90 + 0)/(100) = 0.9 and in percentage the accuracy is 90 %.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7">Is there anything fishy?</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The accuracy, in this case, is 90 % but this model is very poor because all the 10 people who are unhealthy are classified as healthy. By this example what we are trying to say is that <mark>accuracy is not a good metric when the data set is unbalanced</mark>. Using accuracy in such scenarios can result in misleading interpretation of results.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So now we move further to find out another metric for classification. Again we go back to the pregnancy classification example.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now we will find the <strong>precision (positive predictive value)</strong> in classifying the data instances. Precision is defined as follows:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:76%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 561px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*VXnUvOEdf3IiYVCD6Wd2vg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*VXnUvOEdf3IiYVCD6Wd2vg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*VXnUvOEdf3IiYVCD6Wd2vg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*VXnUvOEdf3IiYVCD6Wd2vg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*VXnUvOEdf3IiYVCD6Wd2vg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*VXnUvOEdf3IiYVCD6Wd2vg.png 1100w, https://miro.medium.com/v2/resize:fit:1122/format:webp/1*VXnUvOEdf3IiYVCD6Wd2vg.png 1122w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 561px" srcset="https://miro.medium.com/v2/resize:fit:640/1*VXnUvOEdf3IiYVCD6Wd2vg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*VXnUvOEdf3IiYVCD6Wd2vg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*VXnUvOEdf3IiYVCD6Wd2vg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*VXnUvOEdf3IiYVCD6Wd2vg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*VXnUvOEdf3IiYVCD6Wd2vg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*VXnUvOEdf3IiYVCD6Wd2vg.png 1100w, https://miro.medium.com/v2/resize:fit:1122/1*VXnUvOEdf3IiYVCD6Wd2vg.png 1122w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:561/1*VXnUvOEdf3IiYVCD6Wd2vg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7">What does precision mean?</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Precision</strong> should ideally be 1 (high) for a good classifier. <strong>Precision</strong> becomes 1 only when the numerator and denominator are equal i.e <strong>TP = TP +FP</strong>, this also means <strong>FP</strong> is zero. As <strong>FP</strong> increases the value of denominator becomes greater than the numerator and <strong>precision</strong> value decreases (which we don’t want).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So in the pregnancy example, <strong>precision</strong> = 30/(30+ 5) = 0.857</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now we will introduce another important metric called <strong>recall</strong>. <strong>Recall</strong> is also known as <strong>sensitivity </strong>or <strong>true positive rate</strong> and is defined as follows:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:64%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 480px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Aj3aYW4vwYAoJqyL36PVtQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Aj3aYW4vwYAoJqyL36PVtQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Aj3aYW4vwYAoJqyL36PVtQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Aj3aYW4vwYAoJqyL36PVtQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Aj3aYW4vwYAoJqyL36PVtQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Aj3aYW4vwYAoJqyL36PVtQ.png 1100w, https://miro.medium.com/v2/resize:fit:960/format:webp/1*Aj3aYW4vwYAoJqyL36PVtQ.png 960w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 480px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Aj3aYW4vwYAoJqyL36PVtQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Aj3aYW4vwYAoJqyL36PVtQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Aj3aYW4vwYAoJqyL36PVtQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Aj3aYW4vwYAoJqyL36PVtQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Aj3aYW4vwYAoJqyL36PVtQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Aj3aYW4vwYAoJqyL36PVtQ.png 1100w, https://miro.medium.com/v2/resize:fit:960/1*Aj3aYW4vwYAoJqyL36PVtQ.png 960w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:480/1*Aj3aYW4vwYAoJqyL36PVtQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Recall</strong> should ideally be 1 (high) for a good classifier. <strong>Recall</strong> becomes 1 only when the numerator and denominator are equal i.e <strong>TP = TP +FN</strong>, this also means <strong>FN</strong> is zero. As <strong>FN</strong> increases the value of denominator becomes greater than the numerator and <strong>recall</strong> value decreases (which we don’t want).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So in the pregnancy example let us see what will be the recall.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Recall </strong>= 30/(30+ 10) = 0.75</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So ideally in a good classifier, we want both <strong>precision</strong> and <strong>recall</strong> to be one which also means <strong>FP</strong> and <strong>FN</strong> are zero. Therefore we need a metric that takes into account both <strong>precision</strong> and <strong>recall</strong>. <strong>F1-score</strong> is a metric which takes into account both <strong>precision</strong> and <strong>recall</strong> and is defined as follows:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*9uo7HN1pdMlMwTbNSdyO3A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*9uo7HN1pdMlMwTbNSdyO3A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*9uo7HN1pdMlMwTbNSdyO3A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*9uo7HN1pdMlMwTbNSdyO3A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*9uo7HN1pdMlMwTbNSdyO3A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*9uo7HN1pdMlMwTbNSdyO3A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*9uo7HN1pdMlMwTbNSdyO3A.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*9uo7HN1pdMlMwTbNSdyO3A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*9uo7HN1pdMlMwTbNSdyO3A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*9uo7HN1pdMlMwTbNSdyO3A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*9uo7HN1pdMlMwTbNSdyO3A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*9uo7HN1pdMlMwTbNSdyO3A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*9uo7HN1pdMlMwTbNSdyO3A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*9uo7HN1pdMlMwTbNSdyO3A.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*9uo7HN1pdMlMwTbNSdyO3A.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>F1 Score</strong> becomes 1 only when <strong>precision</strong> and <strong>recall </strong>are both 1. <strong>F1 score </strong>becomes high only when both <strong>precision</strong> and<strong> recall</strong> are high. <strong>F1 score</strong> is the harmonic mean of <strong>precision</strong> and <strong>recall</strong> and is a better measure than <strong>accuracy</strong>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In the pregnancy example, <strong>F1 Score</strong> = 2* ( 0.857 * 0.75)/(0.857 + 0.75) = 0.799.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-7">Reading List</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The following is an interesting article on the common binary classification metric by neptune.ai. The link to the article is available here: <a href="https://neptune.ai/blog/f1-score-accuracy-roc-auc-pr-auc)" target="_self">https://neptune.ai/blog/f1-score-accuracy-roc-auc-pr-auc</a></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>