<!DOCTYPE html>
                <html>
                <head>
                    <title>Creativity is Productivity</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/mind-cafe/creativity-is-productivity-459fa71134d4"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@scotthyoung?source=post_page-----459fa71134d4--------------------------------">Author : Scott H. Young</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Creativity is Productivity</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Scientists receive fewer citations as they get older. Matt Clancy <a href="https://mattsclancy.substack.com/p/age-and-the-impact-of-innovations" target="_self">explains</a>:</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4"><em>Pick any author at random, and on average the papers they publish earlier in their career, whether as first author or last author, will be more highly cited and cited by a more diverse group of fields, than a paper they publish later in their career.</em><em>…</em><em>And the magnitudes involved here are quite large. In Yu et al. (2022), the papers published when you begin a career earn 50–65% more citations than those published at the end of a career. The effects are even larger for the citations received by patentees.</em></p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Does the spark of youthful genius burn out quickly, explaining the mediocrity of researchers in their later years? Interestingly, the answer is no:</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4"><em>The results of the previous section suggest [the chance of producing your most-cited paper] should fall pretty rapidly. At each career stage, your average citations are lower, and it would be natural to assume the best work you can produce will also tend to be lower impact, on average, than it was in earlier career stages.</em></p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">But this is not what Liu and coauthors find! Instead, they find that any paper written, at any stage in your career, has about an equal probability of being your top cited paper!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This is not a new research finding. Nearly two centuries ago, the Belgian sociologist <a href="https://en.wikipedia.org/wiki/Adolphe_Quetelet" target="_self">Adolphe Quetelet</a> observed the impressively tight link between personal productivity and creative success.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">More recently, <a href="https://www.amazon.ca/Greatness-Who-Makes-History-Why/dp/0898622018" target="_self">Dean Simonton</a> has analyzed the creative output of individuals across many domains and suggests an “equal-odds” rule best describes it: once a creative individual starts publishing in a field, each piece of work they produce has roughly equal odds of world-breaking impact.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">The Surprising Equipotential of Creative Success</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">When I first encountered this research literature, it surprised me! Consider, for a moment, what this theory rejects:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;"><strong>Accumulating expertise.</strong> We might expect steadily improving skills through deliberate practice and a widening knowledge base would lead to increased creative success. Except, this is not what we see outside of the initial preparatory training to enter a career.</li><li class="ff3" style="font-size:22px;"><strong>Youthful genius.</strong> Alternatively, we might expect creativity to decline as thinkers become burdened by old ways of doing things. Were this true, we would predict a reduced rate of creative success over time. But this wasn’t observed in Simonton’s research.</li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Instead, it looks like the most important determinant of creative success is simply how much work you produce.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Creative Success as Randomness</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A simple model might capture the essential details of this trend:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ul><li class="ff3" style="font-size:22px;"><strong>Be at a knowledge frontier. </strong>You can’t contribute anything new if you’re not at the boundary of knowledge for a discipline. In academia, this usually prevents undergraduates from publishing many papers; in technology, this prevents unskilled inventors from obtaining new patents. <a href="https://link.springer.com/chapter/10.1007/978-1-4757-5356-1_7#citeas" target="_self">Other work</a> suggests painters and composers have similar ramp-up periods where their work is initially unremarkable. Getting to this threshold is non-trivial and takes considerable time and training.</li><li class="ff3" style="font-size:22px;"><strong>Idea generation and public reception are stochastic processes.</strong> Once you reach the threshold, further advances have a significant random component. This might be due to the trial-and-error process of finding new advances. Or it might come from the unpredictability of public taste as to what work receives acclaim.</li></ul></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The randomness of creative success favors those who are the most prolific. <a href="https://en.wikipedia.org/wiki/Derek_J._de_Solla_Price#Scientific_contributions" target="_self">Price’s Law</a> captures this relationship in scientific output, estimating that half of the research of a given discipline will be produced by the square root of the number of researchers.<a href="https://www.scotthyoung.com/blog/2023/02/28/creativity-is-productivity/#easy-footnote-bottom-1-14953" target="_self">1</a> So in a field with 100 contributors, ten will produce half of the published output. If every paper in the field has a roughly equal probability of being cited, these ten highly prolific authors will capture approximately half of all citations in their field.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">To Produce Better Work, Increase Your Output</h4></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*3ip95bENt2kB9CQS 640w, https://miro.medium.com/v2/resize:fit:720/0*3ip95bENt2kB9CQS 720w, https://miro.medium.com/v2/resize:fit:750/0*3ip95bENt2kB9CQS 750w, https://miro.medium.com/v2/resize:fit:786/0*3ip95bENt2kB9CQS 786w, https://miro.medium.com/v2/resize:fit:828/0*3ip95bENt2kB9CQS 828w, https://miro.medium.com/v2/resize:fit:1100/0*3ip95bENt2kB9CQS 1100w, https://miro.medium.com/v2/resize:fit:1400/0*3ip95bENt2kB9CQS 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*3ip95bENt2kB9CQS 640w, https://miro.medium.com/v2/resize:fit:720/0*3ip95bENt2kB9CQS 720w, https://miro.medium.com/v2/resize:fit:750/0*3ip95bENt2kB9CQS 750w, https://miro.medium.com/v2/resize:fit:786/0*3ip95bENt2kB9CQS 786w, https://miro.medium.com/v2/resize:fit:828/0*3ip95bENt2kB9CQS 828w, https://miro.medium.com/v2/resize:fit:1100/0*3ip95bENt2kB9CQS 1100w, https://miro.medium.com/v2/resize:fit:1400/0*3ip95bENt2kB9CQS 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/0*3ip95bENt2kB9CQS"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Photo by <a href="https://unsplash.com/es/@avirichards?utm_source=medium&utm_medium=referral" target="_self">Avi Richards</a> on <a href="https://unsplash.com?utm_source=medium&utm_medium=referral" target="_self">Unsplash</a></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Intuitively, it feels like there ought to be a strong quality-quantity tradeoff in one’s work. You can make a few excellent things, or you can produce a lot of mediocre work. Certainly there are lots of things that increase productivity at the expense of quality. Typing random words on a page and hitting publish would increase my essay count at the cost of my writing quality dropping to zero. However, it’s interesting to note that my most-viewed articles have tended to come from my more prolific writing periods.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We prefer to attach creative success to a combination of innate talent, acquired ability and passionate commitment. Placing such significance on chance appears to cheapen the achievements of great artists, inventors and scientists.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Yet perhaps it’s because we’re so uncomfortable likening creativity to a lottery that this perspective is undervalued. <mark>Over a surprisingly wide range of pursuits, creativity </mark><mark>is</mark><mark> productivity, and we will have more hits if we take more swings.</mark></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>_ _ _</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Join my weekly newsletter and </em><a href="https://www.scotthyoung.com/blog/newsletter-mm/" target="_self">get 5 of my books</a><em>.</em></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>