<!DOCTYPE html>
                <html>
                <head>
                    <title>Martian Potato Paradox Solution</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/i-math/matt-damon-s-martian-potatoes-1bcde7c6f77d"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@brettelizabethberry?source=post_page-----1bcde7c6f77d--------------------------------">Author : Brett Berry</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Martian Potato Paradox Solution</h3></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">Matt Damon has<strong> 100 pounds</strong> of Martian potatoes, which are <strong>99% water</strong> by weight. For complex scientific purposes, he needs to dehydrate them until they are <strong>98% water</strong>. After he completes this task, how much do the Martian potatoes weigh now?</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">How’d it go?<em> </em>We’re you able to solve the paradox? Did you use the hint and help from the <a href="https://medium.com/i-math/the-martian-potato-paradox-f4517c40a68e#.rfpp45hbu" target="_self">last lesson</a>?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I have two possible solutions for you. The first solution requires only basic math with the option of using pre-algebra. The second solution uses algebra. Pick whichever suits your fancy!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Basic Math Solution</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The potatoes are 99% water, so begin by finding 99% of 100 pounds to determine the weight of water beforehand.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">99% of 100 is 99, so the potatoes are <strong>99 pounds water</strong> and <strong>1 pound potato matter</strong>.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*3ntp52yeR4K9qDRV6shK6A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*3ntp52yeR4K9qDRV6shK6A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*3ntp52yeR4K9qDRV6shK6A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*3ntp52yeR4K9qDRV6shK6A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*3ntp52yeR4K9qDRV6shK6A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*3ntp52yeR4K9qDRV6shK6A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*3ntp52yeR4K9qDRV6shK6A.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*3ntp52yeR4K9qDRV6shK6A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*3ntp52yeR4K9qDRV6shK6A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*3ntp52yeR4K9qDRV6shK6A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*3ntp52yeR4K9qDRV6shK6A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*3ntp52yeR4K9qDRV6shK6A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*3ntp52yeR4K9qDRV6shK6A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*3ntp52yeR4K9qDRV6shK6A.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*3ntp52yeR4K9qDRV6shK6A.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We need to determine how much the potatoes will weigh after dehydrating them to 98 percent water. The potato matter won’t change when we dehydrate them, so keep the potato matter equal to 1 pound.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If the potatoes are 98% water, then<strong> </strong>2% is potato matter. Therefore 2% of the total weight must equal 1 pound of potato matter.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*JqG2U7JWABVHIqS37TpwfQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*JqG2U7JWABVHIqS37TpwfQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*JqG2U7JWABVHIqS37TpwfQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*JqG2U7JWABVHIqS37TpwfQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*JqG2U7JWABVHIqS37TpwfQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*JqG2U7JWABVHIqS37TpwfQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*JqG2U7JWABVHIqS37TpwfQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*JqG2U7JWABVHIqS37TpwfQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*JqG2U7JWABVHIqS37TpwfQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*JqG2U7JWABVHIqS37TpwfQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*JqG2U7JWABVHIqS37TpwfQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*JqG2U7JWABVHIqS37TpwfQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*JqG2U7JWABVHIqS37TpwfQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*JqG2U7JWABVHIqS37TpwfQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*JqG2U7JWABVHIqS37TpwfQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Our question is then: <strong>2% of what equals 1 pound?</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">(<em>Note</em>: <em>if you know pre-algebra, you can skip to the </em><strong>alternative ending</strong>)</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Let’s think about this visually.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Suppose I had 10 pounds of potatoes composed of 1 pound potato matter and 9 pounds water.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 640w, https://miro.medium.com/v2/resize:fit:720/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 720w, https://miro.medium.com/v2/resize:fit:750/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 750w, https://miro.medium.com/v2/resize:fit:786/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 786w, https://miro.medium.com/v2/resize:fit:828/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*zeOHwkgdK1cJdsbxqJ0Y5w.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*zeOHwkgdK1cJdsbxqJ0Y5w.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The shaded portion is 10% of the bar. This can be calculated by multiplying 1/10 by 10/10 to yield 10 per 100 = 10 percent<em>.</em></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:47%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 361px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*6_As8jkdsAJHgaBv5Ickgw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*6_As8jkdsAJHgaBv5Ickgw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*6_As8jkdsAJHgaBv5Ickgw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*6_As8jkdsAJHgaBv5Ickgw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*6_As8jkdsAJHgaBv5Ickgw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*6_As8jkdsAJHgaBv5Ickgw.png 1100w, https://miro.medium.com/v2/resize:fit:722/format:webp/1*6_As8jkdsAJHgaBv5Ickgw.png 722w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 361px" srcset="https://miro.medium.com/v2/resize:fit:640/1*6_As8jkdsAJHgaBv5Ickgw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*6_As8jkdsAJHgaBv5Ickgw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*6_As8jkdsAJHgaBv5Ickgw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*6_As8jkdsAJHgaBv5Ickgw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*6_As8jkdsAJHgaBv5Ickgw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*6_As8jkdsAJHgaBv5Ickgw.png 1100w, https://miro.medium.com/v2/resize:fit:722/1*6_As8jkdsAJHgaBv5Ickgw.png 722w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:361/1*6_As8jkdsAJHgaBv5Ickgw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">10% is too large. Remember we are looking for a portion makes 1 pound equal to <strong>2% of the total weight</strong>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Let’s make the diagram 5 times larger. Fill in 1 square to represent 1 pound of potato matter.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*ZbPdSKIQ3RShPXo1UM2QpA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*ZbPdSKIQ3RShPXo1UM2QpA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*ZbPdSKIQ3RShPXo1UM2QpA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*ZbPdSKIQ3RShPXo1UM2QpA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*ZbPdSKIQ3RShPXo1UM2QpA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ZbPdSKIQ3RShPXo1UM2QpA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*ZbPdSKIQ3RShPXo1UM2QpA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*ZbPdSKIQ3RShPXo1UM2QpA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*ZbPdSKIQ3RShPXo1UM2QpA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*ZbPdSKIQ3RShPXo1UM2QpA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*ZbPdSKIQ3RShPXo1UM2QpA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*ZbPdSKIQ3RShPXo1UM2QpA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*ZbPdSKIQ3RShPXo1UM2QpA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*ZbPdSKIQ3RShPXo1UM2QpA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*ZbPdSKIQ3RShPXo1UM2QpA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">To find out how much this would be per one hundred, multiply 1/50 by 2/2.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:65%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 486px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*ZEhoCi5c4CGimp0Dz0kijA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*ZEhoCi5c4CGimp0Dz0kijA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*ZEhoCi5c4CGimp0Dz0kijA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*ZEhoCi5c4CGimp0Dz0kijA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*ZEhoCi5c4CGimp0Dz0kijA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ZEhoCi5c4CGimp0Dz0kijA.png 1100w, https://miro.medium.com/v2/resize:fit:972/format:webp/1*ZEhoCi5c4CGimp0Dz0kijA.png 972w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 486px" srcset="https://miro.medium.com/v2/resize:fit:640/1*ZEhoCi5c4CGimp0Dz0kijA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*ZEhoCi5c4CGimp0Dz0kijA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*ZEhoCi5c4CGimp0Dz0kijA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*ZEhoCi5c4CGimp0Dz0kijA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*ZEhoCi5c4CGimp0Dz0kijA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*ZEhoCi5c4CGimp0Dz0kijA.png 1100w, https://miro.medium.com/v2/resize:fit:972/1*ZEhoCi5c4CGimp0Dz0kijA.png 972w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:486/1*ZEhoCi5c4CGimp0Dz0kijA.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">2/100 is equivalent to 2 percent!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">After dehydrating, we will have 50 pounds of potatoes that are 1 pound potato matter and 49 pounds water.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*xgi3D9dJHzfx-V1k9gomVw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*xgi3D9dJHzfx-V1k9gomVw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*xgi3D9dJHzfx-V1k9gomVw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*xgi3D9dJHzfx-V1k9gomVw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*xgi3D9dJHzfx-V1k9gomVw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*xgi3D9dJHzfx-V1k9gomVw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*xgi3D9dJHzfx-V1k9gomVw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*xgi3D9dJHzfx-V1k9gomVw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*xgi3D9dJHzfx-V1k9gomVw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*xgi3D9dJHzfx-V1k9gomVw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*xgi3D9dJHzfx-V1k9gomVw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*xgi3D9dJHzfx-V1k9gomVw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*xgi3D9dJHzfx-V1k9gomVw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*xgi3D9dJHzfx-V1k9gomVw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*xgi3D9dJHzfx-V1k9gomVw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This equates to 2% potato matter and 98% water as expected. Therefore, we need to<strong> dehydrate the potatoes by 50 pounds</strong> in order to obtain 98 percent water!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">And that’s why it’s called a <em>paradox</em>. It seems like in order to reduce the weight by 1 percent we wouldn’t have to dehydrate them much at all. But in fact we have to <strong>reduce the weight by half of the original!</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Alternative Ending using Pre-algebra</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Using pre-algebra you can take a shorter path. Remember when we deduced that what we were really trying to solve was: <strong>2% of what is 1 pound?</strong></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Translate the statement into an equation using the following keywords:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ul><li class="ff3" style="font-size:22px;">2% =&gt; 2/100</li><li class="ff3" style="font-size:22px;"><em>of</em> =&gt; •</li><li class="ff3" style="font-size:22px;"><em>what</em> =&gt; <em>x</em></li></ul></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We then obtain:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:43%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 329px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*Z0lZKb4EY817sTd41UBNOg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*Z0lZKb4EY817sTd41UBNOg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*Z0lZKb4EY817sTd41UBNOg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*Z0lZKb4EY817sTd41UBNOg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*Z0lZKb4EY817sTd41UBNOg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Z0lZKb4EY817sTd41UBNOg.png 1100w, https://miro.medium.com/v2/resize:fit:658/format:webp/1*Z0lZKb4EY817sTd41UBNOg.png 658w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 329px" srcset="https://miro.medium.com/v2/resize:fit:640/1*Z0lZKb4EY817sTd41UBNOg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*Z0lZKb4EY817sTd41UBNOg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*Z0lZKb4EY817sTd41UBNOg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*Z0lZKb4EY817sTd41UBNOg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*Z0lZKb4EY817sTd41UBNOg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*Z0lZKb4EY817sTd41UBNOg.png 1100w, https://miro.medium.com/v2/resize:fit:658/1*Z0lZKb4EY817sTd41UBNOg.png 658w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:329/1*Z0lZKb4EY817sTd41UBNOg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Multiply both sides by 100 to undo the division by 100.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:50%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 381px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*bOl-zgQD5FX7uyEDJnZR7g.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*bOl-zgQD5FX7uyEDJnZR7g.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*bOl-zgQD5FX7uyEDJnZR7g.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*bOl-zgQD5FX7uyEDJnZR7g.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*bOl-zgQD5FX7uyEDJnZR7g.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*bOl-zgQD5FX7uyEDJnZR7g.png 1100w, https://miro.medium.com/v2/resize:fit:762/format:webp/1*bOl-zgQD5FX7uyEDJnZR7g.png 762w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 381px" srcset="https://miro.medium.com/v2/resize:fit:640/1*bOl-zgQD5FX7uyEDJnZR7g.png 640w, https://miro.medium.com/v2/resize:fit:720/1*bOl-zgQD5FX7uyEDJnZR7g.png 720w, https://miro.medium.com/v2/resize:fit:750/1*bOl-zgQD5FX7uyEDJnZR7g.png 750w, https://miro.medium.com/v2/resize:fit:786/1*bOl-zgQD5FX7uyEDJnZR7g.png 786w, https://miro.medium.com/v2/resize:fit:828/1*bOl-zgQD5FX7uyEDJnZR7g.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*bOl-zgQD5FX7uyEDJnZR7g.png 1100w, https://miro.medium.com/v2/resize:fit:762/1*bOl-zgQD5FX7uyEDJnZR7g.png 762w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:381/1*bOl-zgQD5FX7uyEDJnZR7g.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Divide both sides by 2 to undo the multiplication by 2.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:29%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 234px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*sdR1d46FiJqTa3fW4dl7Fg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*sdR1d46FiJqTa3fW4dl7Fg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*sdR1d46FiJqTa3fW4dl7Fg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*sdR1d46FiJqTa3fW4dl7Fg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*sdR1d46FiJqTa3fW4dl7Fg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sdR1d46FiJqTa3fW4dl7Fg.png 1100w, https://miro.medium.com/v2/resize:fit:468/format:webp/1*sdR1d46FiJqTa3fW4dl7Fg.png 468w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 234px" srcset="https://miro.medium.com/v2/resize:fit:640/1*sdR1d46FiJqTa3fW4dl7Fg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*sdR1d46FiJqTa3fW4dl7Fg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*sdR1d46FiJqTa3fW4dl7Fg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*sdR1d46FiJqTa3fW4dl7Fg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*sdR1d46FiJqTa3fW4dl7Fg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*sdR1d46FiJqTa3fW4dl7Fg.png 1100w, https://miro.medium.com/v2/resize:fit:468/1*sdR1d46FiJqTa3fW4dl7Fg.png 468w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:234/1*sdR1d46FiJqTa3fW4dl7Fg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">After dehydration we have 50 pounds of potatoes left which are 1 pound potato matter and 49 pounds water.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">The Algebraic Solution</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">For those of you who like variables and equations, this is the solution for you! We need to calculate the amount of water lost during dehydration.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We’ll begin with a simple objective:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*cYVhCKk8iSoJOdXmNPF05A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*cYVhCKk8iSoJOdXmNPF05A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*cYVhCKk8iSoJOdXmNPF05A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*cYVhCKk8iSoJOdXmNPF05A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*cYVhCKk8iSoJOdXmNPF05A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*cYVhCKk8iSoJOdXmNPF05A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*cYVhCKk8iSoJOdXmNPF05A.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*cYVhCKk8iSoJOdXmNPF05A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*cYVhCKk8iSoJOdXmNPF05A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*cYVhCKk8iSoJOdXmNPF05A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*cYVhCKk8iSoJOdXmNPF05A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*cYVhCKk8iSoJOdXmNPF05A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*cYVhCKk8iSoJOdXmNPF05A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*cYVhCKk8iSoJOdXmNPF05A.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*cYVhCKk8iSoJOdXmNPF05A.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The water weight before is <strong>99% of 100 pounds</strong>. The water weight after will be <strong>98% of the total weight</strong>. The <em>total weight</em> will be 100 pounds minus the amount lost from dehydration, call this unknown amount <em>x.</em></p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*8RhIP9Sax0sMv9UZu-mUhg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*8RhIP9Sax0sMv9UZu-mUhg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*8RhIP9Sax0sMv9UZu-mUhg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*8RhIP9Sax0sMv9UZu-mUhg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*8RhIP9Sax0sMv9UZu-mUhg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*8RhIP9Sax0sMv9UZu-mUhg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*8RhIP9Sax0sMv9UZu-mUhg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*8RhIP9Sax0sMv9UZu-mUhg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*8RhIP9Sax0sMv9UZu-mUhg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*8RhIP9Sax0sMv9UZu-mUhg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*8RhIP9Sax0sMv9UZu-mUhg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*8RhIP9Sax0sMv9UZu-mUhg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*8RhIP9Sax0sMv9UZu-mUhg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*8RhIP9Sax0sMv9UZu-mUhg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*8RhIP9Sax0sMv9UZu-mUhg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">To solve the equation, begin by distributing the .99 and .98 through.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:68%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 509px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*tP5QbGQ8pRZBAEGnzmWvAA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*tP5QbGQ8pRZBAEGnzmWvAA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*tP5QbGQ8pRZBAEGnzmWvAA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*tP5QbGQ8pRZBAEGnzmWvAA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*tP5QbGQ8pRZBAEGnzmWvAA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*tP5QbGQ8pRZBAEGnzmWvAA.png 1100w, https://miro.medium.com/v2/resize:fit:1018/format:webp/1*tP5QbGQ8pRZBAEGnzmWvAA.png 1018w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 509px" srcset="https://miro.medium.com/v2/resize:fit:640/1*tP5QbGQ8pRZBAEGnzmWvAA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*tP5QbGQ8pRZBAEGnzmWvAA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*tP5QbGQ8pRZBAEGnzmWvAA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*tP5QbGQ8pRZBAEGnzmWvAA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*tP5QbGQ8pRZBAEGnzmWvAA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*tP5QbGQ8pRZBAEGnzmWvAA.png 1100w, https://miro.medium.com/v2/resize:fit:1018/1*tP5QbGQ8pRZBAEGnzmWvAA.png 1018w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:509/1*tP5QbGQ8pRZBAEGnzmWvAA.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Note negative .98 times negative x results in positive .98x</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Subtract 98 from 99.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:46%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 356px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*rRYODlbkBNqBYz7WzZoaMQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*rRYODlbkBNqBYz7WzZoaMQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*rRYODlbkBNqBYz7WzZoaMQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*rRYODlbkBNqBYz7WzZoaMQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*rRYODlbkBNqBYz7WzZoaMQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*rRYODlbkBNqBYz7WzZoaMQ.png 1100w, https://miro.medium.com/v2/resize:fit:712/format:webp/1*rRYODlbkBNqBYz7WzZoaMQ.png 712w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 356px" srcset="https://miro.medium.com/v2/resize:fit:640/1*rRYODlbkBNqBYz7WzZoaMQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*rRYODlbkBNqBYz7WzZoaMQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*rRYODlbkBNqBYz7WzZoaMQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*rRYODlbkBNqBYz7WzZoaMQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*rRYODlbkBNqBYz7WzZoaMQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*rRYODlbkBNqBYz7WzZoaMQ.png 1100w, https://miro.medium.com/v2/resize:fit:712/1*rRYODlbkBNqBYz7WzZoaMQ.png 712w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:356/1*rRYODlbkBNqBYz7WzZoaMQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Subtract .98<em>x</em> from both sides.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:44%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 340px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*yPTGdfvKrnAAFFBAt7K8WQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*yPTGdfvKrnAAFFBAt7K8WQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*yPTGdfvKrnAAFFBAt7K8WQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*yPTGdfvKrnAAFFBAt7K8WQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*yPTGdfvKrnAAFFBAt7K8WQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*yPTGdfvKrnAAFFBAt7K8WQ.png 1100w, https://miro.medium.com/v2/resize:fit:680/format:webp/1*yPTGdfvKrnAAFFBAt7K8WQ.png 680w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 340px" srcset="https://miro.medium.com/v2/resize:fit:640/1*yPTGdfvKrnAAFFBAt7K8WQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*yPTGdfvKrnAAFFBAt7K8WQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*yPTGdfvKrnAAFFBAt7K8WQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*yPTGdfvKrnAAFFBAt7K8WQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*yPTGdfvKrnAAFFBAt7K8WQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*yPTGdfvKrnAAFFBAt7K8WQ.png 1100w, https://miro.medium.com/v2/resize:fit:680/1*yPTGdfvKrnAAFFBAt7K8WQ.png 680w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:340/1*yPTGdfvKrnAAFFBAt7K8WQ.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Rewrite x as 1x</p><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:35%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 274px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*1jJSn6X7Gw19fD1broSCIw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*1jJSn6X7Gw19fD1broSCIw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*1jJSn6X7Gw19fD1broSCIw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*1jJSn6X7Gw19fD1broSCIw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*1jJSn6X7Gw19fD1broSCIw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*1jJSn6X7Gw19fD1broSCIw.png 1100w, https://miro.medium.com/v2/resize:fit:548/format:webp/1*1jJSn6X7Gw19fD1broSCIw.png 548w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 274px" srcset="https://miro.medium.com/v2/resize:fit:640/1*1jJSn6X7Gw19fD1broSCIw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*1jJSn6X7Gw19fD1broSCIw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*1jJSn6X7Gw19fD1broSCIw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*1jJSn6X7Gw19fD1broSCIw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*1jJSn6X7Gw19fD1broSCIw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*1jJSn6X7Gw19fD1broSCIw.png 1100w, https://miro.medium.com/v2/resize:fit:548/1*1jJSn6X7Gw19fD1broSCIw.png 548w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:274/1*1jJSn6X7Gw19fD1broSCIw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Divide both sides by 0.02.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:23%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 189px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*rGKSv95e72xPgsoiEx1R7Q.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*rGKSv95e72xPgsoiEx1R7Q.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*rGKSv95e72xPgsoiEx1R7Q.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*rGKSv95e72xPgsoiEx1R7Q.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*rGKSv95e72xPgsoiEx1R7Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*rGKSv95e72xPgsoiEx1R7Q.png 1100w, https://miro.medium.com/v2/resize:fit:378/format:webp/1*rGKSv95e72xPgsoiEx1R7Q.png 378w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 189px" srcset="https://miro.medium.com/v2/resize:fit:640/1*rGKSv95e72xPgsoiEx1R7Q.png 640w, https://miro.medium.com/v2/resize:fit:720/1*rGKSv95e72xPgsoiEx1R7Q.png 720w, https://miro.medium.com/v2/resize:fit:750/1*rGKSv95e72xPgsoiEx1R7Q.png 750w, https://miro.medium.com/v2/resize:fit:786/1*rGKSv95e72xPgsoiEx1R7Q.png 786w, https://miro.medium.com/v2/resize:fit:828/1*rGKSv95e72xPgsoiEx1R7Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*rGKSv95e72xPgsoiEx1R7Q.png 1100w, https://miro.medium.com/v2/resize:fit:378/1*rGKSv95e72xPgsoiEx1R7Q.png 378w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:189/1*rGKSv95e72xPgsoiEx1R7Q.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Therefore the weight in water to be removed is <strong>50 pounds</strong>. Since the original weight was 100 pounds, the remaining weight after dehydration will be 50 pounds as well. Because 1 pound is potato matter, there will be 49 pounds of water in the dehydrated potatoes.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">You can check the answer by dividing 49 by 50 to ensure the potatoes are 98% water.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:68%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 507px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*mXcDBfPUCy_2210qUNpXcA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*mXcDBfPUCy_2210qUNpXcA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*mXcDBfPUCy_2210qUNpXcA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*mXcDBfPUCy_2210qUNpXcA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*mXcDBfPUCy_2210qUNpXcA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*mXcDBfPUCy_2210qUNpXcA.png 1100w, https://miro.medium.com/v2/resize:fit:1014/format:webp/1*mXcDBfPUCy_2210qUNpXcA.png 1014w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 507px" srcset="https://miro.medium.com/v2/resize:fit:640/1*mXcDBfPUCy_2210qUNpXcA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*mXcDBfPUCy_2210qUNpXcA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*mXcDBfPUCy_2210qUNpXcA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*mXcDBfPUCy_2210qUNpXcA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*mXcDBfPUCy_2210qUNpXcA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*mXcDBfPUCy_2210qUNpXcA.png 1100w, https://miro.medium.com/v2/resize:fit:1014/1*mXcDBfPUCy_2210qUNpXcA.png 1014w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:507/1*mXcDBfPUCy_2210qUNpXcA.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Multiply the decimal value by 100 to yield the percentage.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Strange isn’t it? Reducing the water by 1 percent requires us to cut the total weight of the potatoes in half! <em>That’s the paradox.</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Next Lesson: </em><a href="https://medium.com/i-math/understanding-logarithms-and-roots-2fee92c3317f#.ujrmmxt21" target="_self">Understanding Logarithms and Roots</a></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Thanks for reading!</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>Please click the ❤ to let me know you learned something new!</em></p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>