<!DOCTYPE html>
                <html>
                <head>
                    <title>Microsoft’s Museformer: AI music is the new frontier</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/mlearning-ai/microsofts-museformer-ai-music-is-the-new-frontier-8dc5cb24459c"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@salvatore-raieli?source=post_page-----8dc5cb24459c--------------------------------">Author : Salvatore Raieli</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Microsoft’s Museformer: AI music is the new frontier</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">AI art is exploding, music can be next.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*lj0lgtTu87FVDAT_Rj4KqA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*lj0lgtTu87FVDAT_Rj4KqA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*lj0lgtTu87FVDAT_Rj4KqA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*lj0lgtTu87FVDAT_Rj4KqA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*lj0lgtTu87FVDAT_Rj4KqA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*lj0lgtTu87FVDAT_Rj4KqA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*lj0lgtTu87FVDAT_Rj4KqA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*lj0lgtTu87FVDAT_Rj4KqA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*lj0lgtTu87FVDAT_Rj4KqA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*lj0lgtTu87FVDAT_Rj4KqA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*lj0lgtTu87FVDAT_Rj4KqA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*lj0lgtTu87FVDAT_Rj4KqA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*lj0lgtTu87FVDAT_Rj4KqA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*lj0lgtTu87FVDAT_Rj4KqA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*lj0lgtTu87FVDAT_Rj4KqA.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Image generated with <a href="https://openai.com/dall-e-2/" target="_self">OpenAI Dall-E 2</a></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Transformers have revolutionized natural language processing. In recent months, however, we have seen how AI has been applied to art and image generation. A few days ago, <a href="https://arxiv.org/pdf/2210.10349.pdf" target="_self">Microsoft announced Museformer</a>, a model for music generation.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Music can be represented as an organized and discrete sequence of tokens (after all, music consists of a series of sounds in sequence). Transformers have been shown to be efficient in text generation, and in other words, transformers can be said to do nothing more than generate a sequence of text. The success of the <a href="https://en.wikipedia.org/wiki/Transformer_(machine_learning_model)" target="_self">Transformer</a> lies in the fact that the <a href="https://en.wikipedia.org/wiki/Attention_(machine_learning)" target="_self">self-attention</a> mechanism allows long dependencies to be captured in a text. To model music, we need to be able to capture long dependencies and the correlation between various parts of the musical sequence. This lays the foundation for using a transformer to generate music.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*L1jeS878b_nK6boI6CvBtw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*L1jeS878b_nK6boI6CvBtw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*L1jeS878b_nK6boI6CvBtw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*L1jeS878b_nK6boI6CvBtw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*L1jeS878b_nK6boI6CvBtw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*L1jeS878b_nK6boI6CvBtw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*L1jeS878b_nK6boI6CvBtw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*L1jeS878b_nK6boI6CvBtw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*L1jeS878b_nK6boI6CvBtw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*L1jeS878b_nK6boI6CvBtw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*L1jeS878b_nK6boI6CvBtw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*L1jeS878b_nK6boI6CvBtw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*L1jeS878b_nK6boI6CvBtw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*L1jeS878b_nK6boI6CvBtw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*L1jeS878b_nK6boI6CvBtw.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">The music score of Twinkle, Twinkle, Little Star, and its corresponding token representation. from the original article (<a href="https://arxiv.org/pdf/2210.10349.pdf" target="_self">here</a>)</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Of course, it is not that easy:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ul><li class="ff3" style="font-size:22px;"><strong>Long sequence modeling</strong>: musical sequences are very long (especially when there are several instruments). This is a problem because the attention mechanism has quadratic complexity and thus the computational cost becomes exponentially higher.</li><li class="ff3" style="font-size:22px;"><strong>Music structure modeling:</strong> music has its own unique structure, there are definite patterns that are repeated and can have variations. These patterns recur sometimes long distances in the sequence, making it more complicated.</li></ul></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This is not the first time that attempts have been made to handle long sequences with transformers. There are two approaches that have been used primarily:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ul><li class="ff3" style="font-size:22px;"><strong>Local focusing</strong>, as in the case of <a href="https://arxiv.org/abs/1901.02860" target="_self">Transformer XL</a> and <a href="https://arxiv.org/abs/2004.05150" target="_self">Longformer</a>, where basically the focus is only on part of the input sequence and the rest is dropped. In the case, of music, the retained sequence may not contain the important part of the musical structure.</li><li class="ff3" style="font-size:22px;"><strong>global approximation</strong>, used by <a href="https://arxiv.org/abs/2006.16236" target="_self">Linear Transformer</a> where there is a sequence compression, although this compression reduces complexity, it does not capture the correlation between the various parts of a musical sequence.</li></ul></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The insight of this paper, and that although these two approaches are inadequate one can take the best of the two. Indeed, not all parts of a musical sequence are important (and this information is not evenly distributed). So we need to safeguard and focus on these parts, and when generating music we focus on the important repetitions. The rest, those less important passages can be approximated. So the idea, in summary, is to focus on the important parts but reduce the complexity and computational computation.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This mechanism is put into practice by a mechanism called fine and coarse-grained attention (FC-Attention) that replaces the classical self-attention module:</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">The general idea is that we do not need to focus on the whole sequence with the same importance level given that the complexity of pair-wise full attention is unacceptably high, but instead we combine two different attention schemes — fine-grained attention for the structure-related bars, and coarse-grained attention for the other bars.</p></blockquote></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*BrDcx3RhU3HNDfH3a-MI8Q.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*BrDcx3RhU3HNDfH3a-MI8Q.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*BrDcx3RhU3HNDfH3a-MI8Q.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*BrDcx3RhU3HNDfH3a-MI8Q.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*BrDcx3RhU3HNDfH3a-MI8Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*BrDcx3RhU3HNDfH3a-MI8Q.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*BrDcx3RhU3HNDfH3a-MI8Q.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*BrDcx3RhU3HNDfH3a-MI8Q.png 640w, https://miro.medium.com/v2/resize:fit:720/1*BrDcx3RhU3HNDfH3a-MI8Q.png 720w, https://miro.medium.com/v2/resize:fit:750/1*BrDcx3RhU3HNDfH3a-MI8Q.png 750w, https://miro.medium.com/v2/resize:fit:786/1*BrDcx3RhU3HNDfH3a-MI8Q.png 786w, https://miro.medium.com/v2/resize:fit:828/1*BrDcx3RhU3HNDfH3a-MI8Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*BrDcx3RhU3HNDfH3a-MI8Q.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*BrDcx3RhU3HNDfH3a-MI8Q.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*BrDcx3RhU3HNDfH3a-MI8Q.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">The fine- and coarse-grained attention. from the original article (<a href="https://arxiv.org/pdf/2210.10349.pdf" target="_self">here</a>)</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In other words, there are two steps: summarization, and aggregation. The first step reduces the complexity and creates a kind of “summary token” for part of the sequence, and then the information is subsequently aggregated (as in classical attention this allows contextualization of the information):</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">The basic idea of FC-Attention is that, instead of directly attending to all the tokens which causes the quadratic complexity, a token of a specific bar only directly attends to the structure-related bars that are essential for generating structured music (fine-grained attention), and for the other bars, the token only attends to their summary tokens to obtain concentrated information (coarse-grained attention). To achieve this, we first summarize the local information of each bar through the summarization step, and then aggregate the fine-grained and coarse-grained information through the aggregation step.</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">These bars simply represent part of the sequence. The last important step is to figure out which ones represent the important information and are likely to be repeated in the musical sequence. For this, the authors used simple summary statistics by calculating the similarity between two different bars along the entire sequence.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">They applied the same approach to analyze different styles, finding that some patterns are repeated across different genres and styles:</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">We further conduct the similarity statistics on different datasets involving music of various genres and styles. The results shown in Appendix A interestingly indicate that this pattern is universally applicable to the music of the great diversity. We believe that it can be regarded as a general rule applicable to most music in our daily life.</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The authors state that this structure allows the model to comply with music characteristics and cover the structure-related information (both short-term and long-term). In addition, the model preserves information as opposed to models that use sparse attention to reduce complexity (this leads to losing a large amount of information).</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*JkLskKyDSE6Tu2r_dO1i0Q.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*JkLskKyDSE6Tu2r_dO1i0Q.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*JkLskKyDSE6Tu2r_dO1i0Q.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*JkLskKyDSE6Tu2r_dO1i0Q.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*JkLskKyDSE6Tu2r_dO1i0Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*JkLskKyDSE6Tu2r_dO1i0Q.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*JkLskKyDSE6Tu2r_dO1i0Q.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*JkLskKyDSE6Tu2r_dO1i0Q.png 640w, https://miro.medium.com/v2/resize:fit:720/1*JkLskKyDSE6Tu2r_dO1i0Q.png 720w, https://miro.medium.com/v2/resize:fit:750/1*JkLskKyDSE6Tu2r_dO1i0Q.png 750w, https://miro.medium.com/v2/resize:fit:786/1*JkLskKyDSE6Tu2r_dO1i0Q.png 786w, https://miro.medium.com/v2/resize:fit:828/1*JkLskKyDSE6Tu2r_dO1i0Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*JkLskKyDSE6Tu2r_dO1i0Q.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*JkLskKyDSE6Tu2r_dO1i0Q.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*JkLskKyDSE6Tu2r_dO1i0Q.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">A snippet of a generated song. from the original article (<a href="https://arxiv.org/pdf/2210.10349.pdf" target="_self">here</a>)</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The authors used to train the model the <a href="https://colinraffel.com/projects/lmd/" target="_self">Lakh MIDI (LMD) dataset</a>, which contains multi-instrument music in the format of <a href="https://en.wikipedia.org/wiki/MIDI" target="_self">MIDI</a> (in total they used nearly thirty thousand songs or 1,700 hours of songs, which contain several instruments).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The model includes 4 layers with hidden size 512, 8 attention heads, and a feed-forward layer of size 2,048. To evaluate it in addition to using perplexity and similarity error, they invited 10 people (including seven with musical backgrounds) to evaluate 100 randomly generated music pieces. People had to evaluate according to several criteria: musicality (whether the piece was pleasant and interesting), Short-term structure, Long-term structure, and overall.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">They also compared their model with other previous models showing that their model was superior:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*48pLqyGVJ4xyuUSiUuWPZQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*48pLqyGVJ4xyuUSiUuWPZQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*48pLqyGVJ4xyuUSiUuWPZQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*48pLqyGVJ4xyuUSiUuWPZQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*48pLqyGVJ4xyuUSiUuWPZQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*48pLqyGVJ4xyuUSiUuWPZQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*48pLqyGVJ4xyuUSiUuWPZQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*48pLqyGVJ4xyuUSiUuWPZQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*48pLqyGVJ4xyuUSiUuWPZQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*48pLqyGVJ4xyuUSiUuWPZQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*48pLqyGVJ4xyuUSiUuWPZQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*48pLqyGVJ4xyuUSiUuWPZQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*48pLqyGVJ4xyuUSiUuWPZQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*48pLqyGVJ4xyuUSiUuWPZQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*48pLqyGVJ4xyuUSiUuWPZQ.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">from the original article (<a href="https://arxiv.org/pdf/2210.10349.pdf" target="_self">here</a>)</p><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*CI6D4lYVa1TVaMsvYdg1rw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*CI6D4lYVa1TVaMsvYdg1rw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*CI6D4lYVa1TVaMsvYdg1rw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*CI6D4lYVa1TVaMsvYdg1rw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*CI6D4lYVa1TVaMsvYdg1rw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*CI6D4lYVa1TVaMsvYdg1rw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*CI6D4lYVa1TVaMsvYdg1rw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*CI6D4lYVa1TVaMsvYdg1rw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*CI6D4lYVa1TVaMsvYdg1rw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*CI6D4lYVa1TVaMsvYdg1rw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*CI6D4lYVa1TVaMsvYdg1rw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*CI6D4lYVa1TVaMsvYdg1rw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*CI6D4lYVa1TVaMsvYdg1rw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*CI6D4lYVa1TVaMsvYdg1rw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*CI6D4lYVa1TVaMsvYdg1rw.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">from the original article (<a href="https://arxiv.org/pdf/2210.10349.pdf" target="_self">here</a>)</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Although the model manages to generate music with good quality and structure, it is still far from perfect.</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">First, since Museformer takes random samplings during inference and does not receive manual control, it can hardly ensure that every generated music piece is well-structured in an expected way. Techniques to enhance its reliability and controllability can be further explored. Furthermore, the musicality and creativity of the generated music are still far behind that of human-made music, which remains a problem for all the existing music generation models.</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Here you can listen to some of the musical examples that have been created:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://ai-muzic.github.io/museformer/"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Museformer: Transformer with Fine- and Coarse-Grained Attention for Music Generation</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Corresponding author. Symbolic music generation aims to generate music scores automatically. A recent trend is to use…</h3><p>ai-muzic.github.io</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In addition, Museformer is part of a larger project by Microsoft. the project called Muzic (<a href="https://github.com/microsoft/muzic" target="_self">GitHub repository here</a>).</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*hjcrCBTw9n7Yd9Mp.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*hjcrCBTw9n7Yd9Mp.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*hjcrCBTw9n7Yd9Mp.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*hjcrCBTw9n7Yd9Mp.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*hjcrCBTw9n7Yd9Mp.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*hjcrCBTw9n7Yd9Mp.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*hjcrCBTw9n7Yd9Mp.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*hjcrCBTw9n7Yd9Mp.png 640w, https://miro.medium.com/v2/resize:fit:720/0*hjcrCBTw9n7Yd9Mp.png 720w, https://miro.medium.com/v2/resize:fit:750/0*hjcrCBTw9n7Yd9Mp.png 750w, https://miro.medium.com/v2/resize:fit:786/0*hjcrCBTw9n7Yd9Mp.png 786w, https://miro.medium.com/v2/resize:fit:828/0*hjcrCBTw9n7Yd9Mp.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*hjcrCBTw9n7Yd9Mp.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*hjcrCBTw9n7Yd9Mp.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/0*hjcrCBTw9n7Yd9Mp.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">image source: <a href="https://github.com/microsoft/muzic" target="_self">official repository</a></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The project aims to understand music (recognize, find, transcribe) and then at a later time generate it. There are already several projects in the repository that can also be tested.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/0*YBFyBq9nyPykIbm5.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/0*YBFyBq9nyPykIbm5.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/0*YBFyBq9nyPykIbm5.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/0*YBFyBq9nyPykIbm5.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/0*YBFyBq9nyPykIbm5.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/0*YBFyBq9nyPykIbm5.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/0*YBFyBq9nyPykIbm5.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/0*YBFyBq9nyPykIbm5.png 640w, https://miro.medium.com/v2/resize:fit:720/0*YBFyBq9nyPykIbm5.png 720w, https://miro.medium.com/v2/resize:fit:750/0*YBFyBq9nyPykIbm5.png 750w, https://miro.medium.com/v2/resize:fit:786/0*YBFyBq9nyPykIbm5.png 786w, https://miro.medium.com/v2/resize:fit:828/0*YBFyBq9nyPykIbm5.png 828w, https://miro.medium.com/v2/resize:fit:1100/0*YBFyBq9nyPykIbm5.png 1100w, https://miro.medium.com/v2/resize:fit:1400/0*YBFyBq9nyPykIbm5.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/0*YBFyBq9nyPykIbm5.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">image source: <a href="https://github.com/microsoft/muzic" target="_self">official repository</a></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Microsoft is not the only one engaging in projects dedicated to music. In fact, a few days ago Google also produced its own model that can continue a song or speech between people. Will what happened with AI art happen with music? what do you think?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">If you have found it interesting:</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">You can look for my other articles, you can also <a href="https://salvatore-raieli.medium.com/subscribe" target="_self">subscribe</a> to get notified when I publish articles, and you can also connect or reach me on<strong> </strong><a href="https://www.linkedin.com/in/salvatore-raieli/" target="_self">LinkedIn</a><strong>. </strong>Thanks for your support!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Here is the link to my GitHub repository, where I am planning to collect code and many resources related to machine learning, artificial intelligence, and more.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://github.com/SalvatoreRa/tutorial"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">GitHub - SalvatoreRa/tutorial: Tutorials on machine learning, artificial intelligence, data science…</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Tutorials on machine learning, artificial intelligence, data science with math explanation and reusable code (in python…</h3><p>github.com</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Or feel free to check out some of my other articles on Medium:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://medium.com/mlearning-ai/ai-reimagines-the-worlds-20-most-beautiful-words-cd07090ea59b"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">AI reimagines the world’s 20 most beautiful words</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">How to translate words that cannot be translated?</h3><p>medium.com</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://towardsdatascience.com/how-ai-could-help-preserve-art-f40c8376781d"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">How AI Could Help Preserve Art</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Art masterpieces are a risk at any time; AI and new technologies can give a hand</h3><p>towardsdatascience.com</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://towardsdatascience.com/how-artificial-intelligence-could-save-the-amazon-rainforest-688fa505c455"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">How artificial intelligence could save the Amazon rainforest</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">Amazonia is at risk and AI could help preserve it</h3><p>towardsdatascience.com</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://medium.com/mlearning-ai/nobel-prize-cyberpunk-e1803aa0e087"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Nobel prize Cyberpunk</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">A computational view of the most important prize and perspective on AI in scientific discovery</h3><p>medium.com</p></a></div></div></div></div></section><br><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://medium.com/mlearning-ai/mlearning-ai-submission-suggestions-b51e2b130bfb"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Mlearning.ai Submission Suggestions</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">How to become a writer on Mlearning.ai</h3><p>medium.com</p></a></div></div></div></div></section><br><?php include_once 'Elemental/footer.php'; ?>