<!DOCTYPE html>
                <html>
                <head>
                    <title>One of the World’s Hardest Math Problems is Surprisingly Simple</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/@pdstjf/one-of-the-worlds-hardest-math-problems-is-surprisingly-simple-b7b1eb490637"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@pdstjf?source=post_page-----b7b1eb490637--------------------------------">Author : Logan Good</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>One of the World’s Hardest Math Problems is Surprisingly Simple</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Understanding one of the hardest problems in math isn’t the hard part, it’s actually proving it.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:69%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 512px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*cSJsFj813y-pSwuGDX9Qyg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*cSJsFj813y-pSwuGDX9Qyg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*cSJsFj813y-pSwuGDX9Qyg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*cSJsFj813y-pSwuGDX9Qyg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*cSJsFj813y-pSwuGDX9Qyg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*cSJsFj813y-pSwuGDX9Qyg.png 1100w, https://miro.medium.com/v2/resize:fit:1024/format:webp/1*cSJsFj813y-pSwuGDX9Qyg.png 1024w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 512px" srcset="https://miro.medium.com/v2/resize:fit:640/1*cSJsFj813y-pSwuGDX9Qyg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*cSJsFj813y-pSwuGDX9Qyg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*cSJsFj813y-pSwuGDX9Qyg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*cSJsFj813y-pSwuGDX9Qyg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*cSJsFj813y-pSwuGDX9Qyg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*cSJsFj813y-pSwuGDX9Qyg.png 1100w, https://miro.medium.com/v2/resize:fit:1024/1*cSJsFj813y-pSwuGDX9Qyg.png 1024w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:512/1*cSJsFj813y-pSwuGDX9Qyg.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">A possible rendering of a Collatz tree using Python, created by Roy John.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The 3x+1 problem is an infamous problem that the world’s best mathematicians have had trouble proving. It acts almost like a game, and it’s pretty easy to understand.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The Collatz conjecture was created in 1937 by Lothar Collatz, a German mathematician. It goes by many other names, such as the 3x+1 (3n+1) problem, the Syracuse problem, Hasse’s Algorithm, and many more. Here’s how it works:</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Step 1: Pick any number.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Step 2: If it is even, divide it in half. If it is odd, multiply it by three and add one to that number.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Step 3: Repeat Step 2.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Step 4: Stop when you get to the number 1.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The idea is that no matter what number you pick, you eventually end up with 1. More specifically, and loop of 4, 2, and back to 1.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">For example, say you pick 7. 7 is odd, so multiply it by three (7x3=21) and add one (21+1=22). 22 is even, so divide it in half. 22/2=11. 11 is odd, so multiplying by three and adding one gets you 34. Half of 34 is 17. Then you get 52. 52 goes to 26. Then to 13. Then 40. Then 20. Then 10. Then 5. Then 16. Then 8. Then 4. Then 2. Then 1. Back to 4. Then 2. Back to 1. The cycle repeats.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Say you pick 64. 64/2=32. 32 goes to 16. Then 8, 4, 2, and 1. You’re back to the 4, 2, 1 cycle. Even small numbers like 15 can take a long time to get back to one, but it eventually does. Mathematicians have checked every number all the way up to 2⁶⁸, and every single one goes back to 4, 2, 1. So if you want to disprove the conjecture and have a calculator powerful enough, start a little over 2⁶⁸, or around 300 quintillion.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Scientists have made programs to show the different paths the numbers take to get to one. They use different methods, though. Some researchers made the path curve a few degrees right if the next number is even, and left a few degrees if it’s odd. Others have used a 3D approach, turning the path slightly with the same general idea. If you type “Collatz Tree” or “Collatz Tree visualized” in a search engine, you can see the different approaches people took on the paths of numbers. These shapes can turn out to be very pretty and organic-looking. Some look like feathers or pieces of sea coral.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Mathematicians have tried using these visualizations to see if there is any branch that never goes back to 1. So far, they haven’t found any. They have tried using many different graphical methods and non-graphical methods, like using tables to chart the numbers. One unorthodox idea is that there are loops of numbers that repeat, like the 4, 2, 1 cycle. This loop would have no connection to the “main” tree. What this also means is there could be a group of numbers that you can’t find anywhere on the main tree; they would be their own separate entity.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Some scientists and mathematicians are arguing that this problem should be added to the Millenium Problems, which is a list of some of the hardest math-related problems no one can currently solve. Only one Millenium Problem has ever been solved, and that distinction belongs to Grigori Perelman for solving the Poincare conjecture. The prize for solving one of the problems is $1,000,000, but Perelman turned it down. So, if someone reading this article wants a challenge (and maybe a million dollars), go try and solve one. Unfortunately, there is no Millenium Prize for proving the Collatz conjecture, but you will certainly get some sort of reward. So stop reading and go try it out for youself.</p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>