<!DOCTYPE html>
                <html>
                <head>
                    <title>The Riemann Sphere</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://www.cantorsparadise.com/the-riemann-sphere-76fe78ebe0d3"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://kaspermuller.medium.com/?source=post_page-----76fe78ebe0d3--------------------------------">Author : Kasper Müller</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>The Riemann Sphere</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5 text-muted">A world where you can divide by zero</h4></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*IYAmHJ8b51r7qdCr5EMxaw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*IYAmHJ8b51r7qdCr5EMxaw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*IYAmHJ8b51r7qdCr5EMxaw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*IYAmHJ8b51r7qdCr5EMxaw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*IYAmHJ8b51r7qdCr5EMxaw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*IYAmHJ8b51r7qdCr5EMxaw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*IYAmHJ8b51r7qdCr5EMxaw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*IYAmHJ8b51r7qdCr5EMxaw.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Stereographic projection of f(x) = 1/x — Image by author</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Something is going on with infinity that we don’t fully understand.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Physicists have long been assigning finite values to infinite divergent series (infinite sums if you wish) such as 1 + 4 + 9 + 16 + ⋅⋅⋅ ≃ 0 and 1 + 2 + 3 + ⋅⋅⋅ ≃ -1/12 (you know, the one that almost broke the internet).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">These infinite series are very rigidly structured and are associated with a (complex analytic) function that makes these values the only sensible choices in a very strict way which we won’t go into in this article.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Of course, the true evaluations of these series (when we define them as limits) are “infinity”. That they evaluate to the same value or concept however doesn’t seem right as they are clearly very different beasts. And indeed they <em>are</em> different from an asymptotical viewpoint. Still, they diverge towards infinity!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">But somehow when physicists replace infinities in their theories with these values, the finite results they get as an output match experiments to an astounding numerical precision.</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">Philosofically speaking, it is almost like these sums go to infinity so fast that they “overshoot” and go beyond and back on the number line. It is like the number line itself is circle-like (topologically speaking) or more generally if the complex plane is a sphere.</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In the real world, physicists are speculating if our 3D space is really a projection from some distant two-dimensional surface. This is called the h<em>olographic principle</em>. Yes, I know how it sounds, but they have their reasons to consider this which is a very long (but interesting) story…</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In the same manner, one could construct a parallel world to that of the complex plane (or the usual cartesian coordinate system) using this (stereographic) projection.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We can think of a point in the plane <em>(x, y)</em>, or equivalently <em>x + yi</em> for those of you who know about complex numbers, as having a twin lying on the sphere with center <em>0</em> and radius <em>1</em> in <em>3D</em> space so that there is a one-to-one correspondence between points on the plane and points on the sphere except for <em>one</em> point on the sphere which we will come back to.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Resolving problems with infinity by spherifying</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Before we consider the so-called Riemann sphere, let’s start this section by asking a seemingly simple question that children ask their teachers each day around the world, namely</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">“Why are we not allowed to divide by zero?”</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The poor teacher comes up with crazy answers like “because you can’t divide your pizza into 0 evenly sized pieces” or worse. The truth is that there are actually several reasons why we can’t divide by zero in a consistent way.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Suppose we defined a real number x = 3/0. Then by multiplying on both sides by 0, we would obtain 0 = 3 which is of course false. Okay, so if we were allowed to divide by zero, the result could not be a real number. Fine, let’s define it to be infinity and include <em>infinity</em> and <em>negative infinity</em> as numbers attached to the real line (this is called the extended real line which actually is a thing).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Well, sorry to disappoint you, but there are problems here as well. In particular, the operation of division would not be a continuous operation anymore since 0 is the limit between the negative and positive real numbers, approaching 0 from the left (in the denominator) would yield <em>negative infinity</em>, and approaching 0 from the right would yield <em>positive infinity</em>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The only way we could fix this is if we defined negative infinity and positive infinity to be equal. In that case, we would only have <em>one</em> infinity and our number space would not be a line anymore, but rather a circle. This solves the continuity problem and we can actually make sense of division by zero by defining x / 0 = ∞ for all real numbers <em>x</em>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This approach can also be carried out on a plane but instead of gluing two ends of an infinite line together, we need to take the whole infinite “horizon” of the plane and tie it up into a point a little like tightening the rim of a bag. We call that point “the point at infinity”. In this way, we get a sphere with a special point at infinity.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The way we explicitly construct this is by a function <em>P</em> from the plane to the unit sphere.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Imagine a number plane such as the complex numbers ℂ or the usual coordinate system (or 2-dimensional real vector space) ℝ² together with a sphere centered at the origin of the plane with radius 1. For each point <em>A</em> on the plane, draw the line going through the north pole <em>N</em> of the sphere and <em>A</em>. This line will then intersect the sphere in a second (unique) point <em>α = P(A)</em> and that is the point that we associate <em>A</em> with.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*ndN4-6ka9UT94zWMlwtE1g.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*ndN4-6ka9UT94zWMlwtE1g.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Conformal mapping from the plane to the unit sphere — image by <a href="http://en.wikipedia.org/wiki/File:Riemann_sphere1.jpg" target="_self">Jean-Christophe Benoist.</a></p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">It is clear from this construction that points z on the plane with |z| &gt; 1 are mapped to the northern hemisphere and points with |z| &lt; 1 are mapped to the southern hemisphere. Points on the unit circle in the plane stay where they are.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Note also that as we move further and further away from the center of the plane in any direction, the corresponding point on the sphere gets closer and closer to <em>N</em>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">While there is no point on the plane that maps to <em>N</em>, we can hit it in the limit where we go to infinity on the plane. So we say that all these limits (independent of direction) map to the north pole <em>N</em> — the point at infinity.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">For the interested reader, we have an explicit formula for P: ℝ² → ℝ³ here:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*PoQjQNK8gKV7aJP0g1BXzw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*PoQjQNK8gKV7aJP0g1BXzw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*PoQjQNK8gKV7aJP0g1BXzw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*PoQjQNK8gKV7aJP0g1BXzw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*PoQjQNK8gKV7aJP0g1BXzw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*PoQjQNK8gKV7aJP0g1BXzw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*PoQjQNK8gKV7aJP0g1BXzw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*PoQjQNK8gKV7aJP0g1BXzw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*PoQjQNK8gKV7aJP0g1BXzw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*PoQjQNK8gKV7aJP0g1BXzw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*PoQjQNK8gKV7aJP0g1BXzw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*PoQjQNK8gKV7aJP0g1BXzw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*PoQjQNK8gKV7aJP0g1BXzw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*PoQjQNK8gKV7aJP0g1BXzw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*PoQjQNK8gKV7aJP0g1BXzw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In case the given plane is the complex plane, the corresponding sphere is called the Riemann sphere or sometimes the extended complex plane because it is seen as the set ℂ ∪ {∞}.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The mapping <em>P</em> carries with it the complex structure from the complex plane onto the sphere (in fact, it is a homeomorphism) and because poles are allowed on the sphere since infinity is included, we can view meromorphic functions as holomorphic functions on the Riemann sphere!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The map P^(-1) from the sphere without the north pole to the plane is usually called <em>stereographic projection</em>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So in this space, we are allowed to divide by zero because the north pole is a part of the sphere, and functions such as <em>f(x) = 1/x</em> are continuous at <em>x = 0</em>. To see this more clearly, we will in the next section consider plots of famous functions mapped by P to the unit sphere.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Real functions on the sphere</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Let us start with the most famous function of all: the natural exponential function <em>f(x) = e^x</em>. We have the following plot</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*MQu_KKJAH6A9yluZjz7r5A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*MQu_KKJAH6A9yluZjz7r5A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*MQu_KKJAH6A9yluZjz7r5A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*MQu_KKJAH6A9yluZjz7r5A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*MQu_KKJAH6A9yluZjz7r5A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*MQu_KKJAH6A9yluZjz7r5A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*MQu_KKJAH6A9yluZjz7r5A.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*MQu_KKJAH6A9yluZjz7r5A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*MQu_KKJAH6A9yluZjz7r5A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*MQu_KKJAH6A9yluZjz7r5A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*MQu_KKJAH6A9yluZjz7r5A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*MQu_KKJAH6A9yluZjz7r5A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*MQu_KKJAH6A9yluZjz7r5A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*MQu_KKJAH6A9yluZjz7r5A.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*MQu_KKJAH6A9yluZjz7r5A.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Image by author</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Look how beautifully it ties itself up in a loop because both ends of the graph hit infinity. Here the red axis is the x-axis and the green axis is the f-axis.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">By looking at it directly from above, we can get a clear understanding of the shape and at the same time see the familiar plot!</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*J78J_RLOJKGjT-ZQGQVN9w.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*J78J_RLOJKGjT-ZQGQVN9w.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*J78J_RLOJKGjT-ZQGQVN9w.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*J78J_RLOJKGjT-ZQGQVN9w.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*J78J_RLOJKGjT-ZQGQVN9w.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*J78J_RLOJKGjT-ZQGQVN9w.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*J78J_RLOJKGjT-ZQGQVN9w.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*J78J_RLOJKGjT-ZQGQVN9w.png 640w, https://miro.medium.com/v2/resize:fit:720/1*J78J_RLOJKGjT-ZQGQVN9w.png 720w, https://miro.medium.com/v2/resize:fit:750/1*J78J_RLOJKGjT-ZQGQVN9w.png 750w, https://miro.medium.com/v2/resize:fit:786/1*J78J_RLOJKGjT-ZQGQVN9w.png 786w, https://miro.medium.com/v2/resize:fit:828/1*J78J_RLOJKGjT-ZQGQVN9w.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*J78J_RLOJKGjT-ZQGQVN9w.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*J78J_RLOJKGjT-ZQGQVN9w.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*J78J_RLOJKGjT-ZQGQVN9w.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">f(x) = e^x — Image by author</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Let’s take a look at the troublemaker <em>f(x) = 1/x </em>which is discontinuous at 0 when defining it as a real function, that is as a function f: ℝ\{0} → ℝ. This too has a beautifully closed curve on the sphere.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*IYAmHJ8b51r7qdCr5EMxaw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*IYAmHJ8b51r7qdCr5EMxaw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*IYAmHJ8b51r7qdCr5EMxaw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*IYAmHJ8b51r7qdCr5EMxaw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*IYAmHJ8b51r7qdCr5EMxaw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*IYAmHJ8b51r7qdCr5EMxaw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*IYAmHJ8b51r7qdCr5EMxaw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*IYAmHJ8b51r7qdCr5EMxaw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*IYAmHJ8b51r7qdCr5EMxaw.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">f(x) = 1/x — Image by author</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This function is not well-defined at 0 because of the problems with infinity but on the sphere, it is perfectly well-defined at x = 0. Poetically, it forms an infinity sign which is the icing on the mathematical cake.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">How about a constant function?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The function <em>f(x) = 2</em> is plotted here:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*4hQj9Ar3jvVN19ylJRqX8g.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*4hQj9Ar3jvVN19ylJRqX8g.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*4hQj9Ar3jvVN19ylJRqX8g.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*4hQj9Ar3jvVN19ylJRqX8g.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*4hQj9Ar3jvVN19ylJRqX8g.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*4hQj9Ar3jvVN19ylJRqX8g.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*4hQj9Ar3jvVN19ylJRqX8g.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*4hQj9Ar3jvVN19ylJRqX8g.png 640w, https://miro.medium.com/v2/resize:fit:720/1*4hQj9Ar3jvVN19ylJRqX8g.png 720w, https://miro.medium.com/v2/resize:fit:750/1*4hQj9Ar3jvVN19ylJRqX8g.png 750w, https://miro.medium.com/v2/resize:fit:786/1*4hQj9Ar3jvVN19ylJRqX8g.png 786w, https://miro.medium.com/v2/resize:fit:828/1*4hQj9Ar3jvVN19ylJRqX8g.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*4hQj9Ar3jvVN19ylJRqX8g.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*4hQj9Ar3jvVN19ylJRqX8g.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*4hQj9Ar3jvVN19ylJRqX8g.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">f(x) = 2 — Image by author</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The constant functions are just circles on the sphere meeting at infinity. How about the logarithm? Well, not surprisingly the natural log has the same shape as the exponential function on the sphere.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*jtf4efz7E3LZXa_DoNvkpQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*jtf4efz7E3LZXa_DoNvkpQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*jtf4efz7E3LZXa_DoNvkpQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*jtf4efz7E3LZXa_DoNvkpQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*jtf4efz7E3LZXa_DoNvkpQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*jtf4efz7E3LZXa_DoNvkpQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*jtf4efz7E3LZXa_DoNvkpQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*jtf4efz7E3LZXa_DoNvkpQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*jtf4efz7E3LZXa_DoNvkpQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*jtf4efz7E3LZXa_DoNvkpQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*jtf4efz7E3LZXa_DoNvkpQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*jtf4efz7E3LZXa_DoNvkpQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*jtf4efz7E3LZXa_DoNvkpQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*jtf4efz7E3LZXa_DoNvkpQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*jtf4efz7E3LZXa_DoNvkpQ.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">The natural logarithm — Image by author</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We also have more special functions plots such as the gamma function Γ for example:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*oOi3RVPLOiy7SFtaGF1G1g.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*oOi3RVPLOiy7SFtaGF1G1g.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*oOi3RVPLOiy7SFtaGF1G1g.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*oOi3RVPLOiy7SFtaGF1G1g.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*oOi3RVPLOiy7SFtaGF1G1g.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*oOi3RVPLOiy7SFtaGF1G1g.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*oOi3RVPLOiy7SFtaGF1G1g.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*oOi3RVPLOiy7SFtaGF1G1g.png 640w, https://miro.medium.com/v2/resize:fit:720/1*oOi3RVPLOiy7SFtaGF1G1g.png 720w, https://miro.medium.com/v2/resize:fit:750/1*oOi3RVPLOiy7SFtaGF1G1g.png 750w, https://miro.medium.com/v2/resize:fit:786/1*oOi3RVPLOiy7SFtaGF1G1g.png 786w, https://miro.medium.com/v2/resize:fit:828/1*oOi3RVPLOiy7SFtaGF1G1g.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*oOi3RVPLOiy7SFtaGF1G1g.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*oOi3RVPLOiy7SFtaGF1G1g.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*oOi3RVPLOiy7SFtaGF1G1g.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In this article, we explored the beautiful worlds of stereographic projection and the Riemann sphere. There is a much more general topic of Riemann surfaces where we consider more general shapes than spheres known as manifolds. It is a beautiful and rich theory in itself.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">If you want to play around with how different functions look on the sphere, I have created the following Geogebra sheet available <a href="https://www.geogebra.org/calculator/nhnnpuqf" target="_self">here</a>. You might need to fiddle a bit with the axes' lengths and the zoom to make it just right. To try a new function you can just change the definition of f(x). Try for example f(x) = zeta(x).</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Enjoy!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><em>If you like to read articles like this one on Medium, you can get a membership for full access: simply click </em><a href="https://kaspermuller.medium.com/membership" target="_self">here</a><em>.</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Thanks for reading.</p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>