<!DOCTYPE html>
                <html>
                <head>
                    <title>Types of Mathematical Proofs</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/@nissim.lavy/types-of-proofs-c43ffacc8ada"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@nissim.lavy?source=post_page-----c43ffacc8ada--------------------------------">Author : Nissim Lavy</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Types of Mathematical Proofs</h3></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:46%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 350px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:700/format:webp/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 700w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 350px" srcset="https://miro.medium.com/v2/resize:fit:640/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 1100w, https://miro.medium.com/v2/resize:fit:700/1*PzWFzIp-lVCCMv96aWWqcA.jpeg 700w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:350/1*PzWFzIp-lVCCMv96aWWqcA.jpeg"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">A typical math proof</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">What is a proof?</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A proof is a logical argument that tries to show that a statement is true. In math, and computer science, a proof has to be well thought out and tested before being accepted. But even then, a proof can be <a href="https://mathoverflow.net/questions/35468/widely-accepted-mathematical-results-that-were-later-shown-wrong" target="_self">discovered to have been wrong</a>. There are many different ways to go about proving something, we’ll discuss 3 methods: direct proof, proof by contradiction, proof by induction. We’ll talk about what each of these proofs are, when and how they’re used.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Before diving in, we’ll need to explain some terminology.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A <strong>theorem</strong> is a mathematical statement which is proven to be true.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><mark>A statement that has been proven true in order to further help in proving another statement is called a </mark><mark>lemma</mark><mark>.</mark></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Now that we’ve gotten that out of the way, let’s job into some types of proofs!</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
            <br>
                <hr class="hr5">
            <br>
            </div>
        </div>
    </div>
</section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Direct Proof (Proof by Construction)</h4></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*C-4WKg-wUWZFxtmKqp9Rpg.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Many theorems state that a specific type or occurrence of an object exists. One method for proving the existence of such an object is to prove that P ⇒ Q (P implies Q). In other words, we would demonstrate how we would build that object to show that it can exist. A proof by construction is just that, we want to prove something by showing how it can come to be. There are only two steps to a direct proof :</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">1. Assume that P is true.2. Use P to show that Q must be true.</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Let’s take a look at an example.</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">Theorem: If <em>a</em> and <em>b </em>are consecutive integers, the sum of <em>a + b </em>must be an odd number.</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Following the steps we laid out before, we first assume that our theorem is true. We then can say that since <em>a </em>and <em>b</em> are consecutive integers, <em>b</em> is equal to <em>a + 1</em>. In that case, <em>a + b</em> can be rewritten as <em>a + a + 1 </em>or <em>2a + 1</em>. Therefore, we can say that <em>a + b = 2k + 1.</em> We know that any number multiplied by an even number must be even. We also know that if we add 1 to any even number, it becomes odd. Given these, we can say: <em>a + b = 2k + 1 </em>shows that <em>a + b </em>is odd.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Proof by Contradiction</h4></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:81%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 600px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*9L53jFilwjDIP4DohXifVQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*9L53jFilwjDIP4DohXifVQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*9L53jFilwjDIP4DohXifVQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*9L53jFilwjDIP4DohXifVQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*9L53jFilwjDIP4DohXifVQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*9L53jFilwjDIP4DohXifVQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1200/format:webp/1*9L53jFilwjDIP4DohXifVQ.jpeg 1200w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 600px" srcset="https://miro.medium.com/v2/resize:fit:640/1*9L53jFilwjDIP4DohXifVQ.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*9L53jFilwjDIP4DohXifVQ.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*9L53jFilwjDIP4DohXifVQ.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*9L53jFilwjDIP4DohXifVQ.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*9L53jFilwjDIP4DohXifVQ.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*9L53jFilwjDIP4DohXifVQ.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1200/1*9L53jFilwjDIP4DohXifVQ.jpeg 1200w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:600/1*9L53jFilwjDIP4DohXifVQ.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A common form of proving a theorem is assuming the theorem is false, and then show that the assumption is false itself, and is therefore a contradiction.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Let’s take a look at a simple example:</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">Theorem: If n² is even, then n is even.</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Given this theorem, let’s assume that <em>n²</em> is even but <em>n</em> is odd. We’re assuming that the theorem is false. As we showed in the previous section, an odd number can be characterized by <em>n = 2k + 1. </em>Using that definition for an odd number we say the following:</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4"><em>n² = (2k + 1)² = 4k²+ 4k + 1 = 2(2k² + 2k) + 1</em></p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Or more concisely, <em>n² = 2(2k² + 2k) + 1</em>. If we let <em>m = 2k² + 2k, </em>we get <em>n² = 2m + 1</em>. Using the definition for odd numbers that we mentioned before, we must say that <em>n² </em>is odd. In our assumption, we declared <em>n² </em>to be even. A contradiction! Since our assumption cannot be, then <em>n²</em> must be even, and we’ve proven the original theorem.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Proof by Induction</h4></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 640w, https://miro.medium.com/v2/resize:fit:720/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 720w, https://miro.medium.com/v2/resize:fit:750/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 750w, https://miro.medium.com/v2/resize:fit:786/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 786w, https://miro.medium.com/v2/resize:fit:828/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 828w, https://miro.medium.com/v2/resize:fit:1100/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 1100w, https://miro.medium.com/v2/resize:fit:1400/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*PvbuksEXe0Z0XmSUpZSR3w.jpeg"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Proof by induction is a more advanced method of proving things, and to be honest, something that took me a while to really grasp. This method is used to show that all elements in an infinite set have a certain property. For example, we may want to prove that <em>1 + 2 + 3 + … + n = n (n + 1)/2.</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In a proof by induction, we generally have 2 parts, a <strong>basis </strong>and the <strong>inductive step.</strong> The basis is the simplest version of the problem, In our case, the basis is,</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">For n=1, our theorem is true</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">since, <em>1 = 1(1 + 1)/2 </em>.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The next part of the proof is the inductive step. The inductive step is the part where to generalize your basis and take it a step further.</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">Suppose our theorem is true for some n = k ≥ 1, that is:1 + 2 + 3 + . . . + k = k(k + 1)/2.Prove that our theorem is true for n = k + 1, meaning:1 + 2 + 3 + . . . + k + (k + 1) = (k + 1)(k + 2) 2 .</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This is the core of the inductive step. We take our theorem, generalize it and take it to the next step. We added in the <em>(k + 1) </em>on the left side of the equals sign and we changed the<em> k </em>on the right side of the equals sign to <em>(k + 1)(k + 2). </em>We finally finish off our proof with</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*k3Uhf-MUdL-K1e_ueVIKwg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*k3Uhf-MUdL-K1e_ueVIKwg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*k3Uhf-MUdL-K1e_ueVIKwg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*k3Uhf-MUdL-K1e_ueVIKwg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*k3Uhf-MUdL-K1e_ueVIKwg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*k3Uhf-MUdL-K1e_ueVIKwg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*k3Uhf-MUdL-K1e_ueVIKwg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*k3Uhf-MUdL-K1e_ueVIKwg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*k3Uhf-MUdL-K1e_ueVIKwg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*k3Uhf-MUdL-K1e_ueVIKwg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*k3Uhf-MUdL-K1e_ueVIKwg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*k3Uhf-MUdL-K1e_ueVIKwg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*k3Uhf-MUdL-K1e_ueVIKwg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*k3Uhf-MUdL-K1e_ueVIKwg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*k3Uhf-MUdL-K1e_ueVIKwg.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Final solution for our proof</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">And with that, we’re done. We’ve followed a logical progression from the basis or the base case, to the inductive step, all the way through to the final part of the proof.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Conclusion</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">We looked at a few different types of proofs and how they really work. We can use these methods to make logical arguments about the validity of some statement in everyday life, or in the code that we right, or in countless of other situations.</p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>