<!DOCTYPE html>
                <html>
                <head>
                    <title>Websites where you can find popular ML/DL research papers</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/mlearning-ai/websites-where-you-can-find-popular-ml-dl-research-papers-dcf075af4cbb"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@sue.sk.guo?source=post_page-----dcf075af4cbb--------------------------------">Author : Sue</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>Websites where you can find popular ML/DL research papers</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Keep you updated with state-of-the-art technology is really important in the Machine learning and deep learning field.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">There are some tips from Andre NG on how to read research papers. <a href="https://www.youtube.com/watch?v=733m6qBH-jI" target="_self">https://www.youtube.com/watch?v=733m6qBH-jI</a></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">So, where can we find the popular papers?</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;">paperswithcode — <a href="https://paperswithcode.com/sota" target="_self">Browse State-of-the-Art</a></li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The papers are well categorized so you can follow what Andre said, choose an area of interest like semantic segmentation, and read 15–20 papers to get a good understanding of this field. More importantly, you can find the paper’s code.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:93%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 684px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*tGqJ4kOcwBtYH8qZf5oowQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*tGqJ4kOcwBtYH8qZf5oowQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*tGqJ4kOcwBtYH8qZf5oowQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*tGqJ4kOcwBtYH8qZf5oowQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*tGqJ4kOcwBtYH8qZf5oowQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*tGqJ4kOcwBtYH8qZf5oowQ.png 1100w, https://miro.medium.com/v2/resize:fit:1368/format:webp/1*tGqJ4kOcwBtYH8qZf5oowQ.png 1368w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 684px" srcset="https://miro.medium.com/v2/resize:fit:640/1*tGqJ4kOcwBtYH8qZf5oowQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*tGqJ4kOcwBtYH8qZf5oowQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*tGqJ4kOcwBtYH8qZf5oowQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*tGqJ4kOcwBtYH8qZf5oowQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*tGqJ4kOcwBtYH8qZf5oowQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*tGqJ4kOcwBtYH8qZf5oowQ.png 1100w, https://miro.medium.com/v2/resize:fit:1368/1*tGqJ4kOcwBtYH8qZf5oowQ.png 1368w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:684/1*tGqJ4kOcwBtYH8qZf5oowQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:70%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 524px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*GFD5JPhEEXzp7vwMmKfpjw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*GFD5JPhEEXzp7vwMmKfpjw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*GFD5JPhEEXzp7vwMmKfpjw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*GFD5JPhEEXzp7vwMmKfpjw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*GFD5JPhEEXzp7vwMmKfpjw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*GFD5JPhEEXzp7vwMmKfpjw.png 1100w, https://miro.medium.com/v2/resize:fit:1048/format:webp/1*GFD5JPhEEXzp7vwMmKfpjw.png 1048w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 524px" srcset="https://miro.medium.com/v2/resize:fit:640/1*GFD5JPhEEXzp7vwMmKfpjw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*GFD5JPhEEXzp7vwMmKfpjw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*GFD5JPhEEXzp7vwMmKfpjw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*GFD5JPhEEXzp7vwMmKfpjw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*GFD5JPhEEXzp7vwMmKfpjw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*GFD5JPhEEXzp7vwMmKfpjw.png 1100w, https://miro.medium.com/v2/resize:fit:1048/1*GFD5JPhEEXzp7vwMmKfpjw.png 1048w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:524/1*GFD5JPhEEXzp7vwMmKfpjw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">2. <a href="https://nn.labml.ai/index.html" target="_self">labml.ai Deep Learning Paper Implementations</a></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">59 Implementations/tutorials of deep learning papers with side-by-side notes 📝; including transformers (original, xl, switch, feedback, vit, …), optimizers (adam, adabelief, …), gans(cyclegan, stylegan2, …), 🎮 reinforcement learning (ppo, dqn), capsnet, distillation, … 🧠</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">This is a collection of simple PyTorch implementations of neural networks and related algorithms. These implementations are documented with explanations. So you are able to read the paper while understanding how to implement it by Pytorch.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*QI_S19lNihupZgpJj7eMfg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*QI_S19lNihupZgpJj7eMfg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*QI_S19lNihupZgpJj7eMfg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*QI_S19lNihupZgpJj7eMfg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*QI_S19lNihupZgpJj7eMfg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*QI_S19lNihupZgpJj7eMfg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*QI_S19lNihupZgpJj7eMfg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*QI_S19lNihupZgpJj7eMfg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*QI_S19lNihupZgpJj7eMfg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*QI_S19lNihupZgpJj7eMfg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*QI_S19lNihupZgpJj7eMfg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*QI_S19lNihupZgpJj7eMfg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*QI_S19lNihupZgpJj7eMfg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*QI_S19lNihupZgpJj7eMfg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*QI_S19lNihupZgpJj7eMfg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">3. labml.ai — <a href="https://papers.labml.ai/" target="_self">Trending Research Papers</a></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The most popular research papers on social media like Twitter. You can easily find links to download papers, paper summaries, explanation videos, and discussions.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*7pr_Bk_Sh38aNgmzOPgb1A.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*7pr_Bk_Sh38aNgmzOPgb1A.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*7pr_Bk_Sh38aNgmzOPgb1A.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*7pr_Bk_Sh38aNgmzOPgb1A.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*7pr_Bk_Sh38aNgmzOPgb1A.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*7pr_Bk_Sh38aNgmzOPgb1A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*7pr_Bk_Sh38aNgmzOPgb1A.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*7pr_Bk_Sh38aNgmzOPgb1A.png 640w, https://miro.medium.com/v2/resize:fit:720/1*7pr_Bk_Sh38aNgmzOPgb1A.png 720w, https://miro.medium.com/v2/resize:fit:750/1*7pr_Bk_Sh38aNgmzOPgb1A.png 750w, https://miro.medium.com/v2/resize:fit:786/1*7pr_Bk_Sh38aNgmzOPgb1A.png 786w, https://miro.medium.com/v2/resize:fit:828/1*7pr_Bk_Sh38aNgmzOPgb1A.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*7pr_Bk_Sh38aNgmzOPgb1A.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*7pr_Bk_Sh38aNgmzOPgb1A.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*7pr_Bk_Sh38aNgmzOPgb1A.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*XJkaJCU4qvndNY1pUV5VZw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*XJkaJCU4qvndNY1pUV5VZw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*XJkaJCU4qvndNY1pUV5VZw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*XJkaJCU4qvndNY1pUV5VZw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*XJkaJCU4qvndNY1pUV5VZw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*XJkaJCU4qvndNY1pUV5VZw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*XJkaJCU4qvndNY1pUV5VZw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*XJkaJCU4qvndNY1pUV5VZw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*XJkaJCU4qvndNY1pUV5VZw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*XJkaJCU4qvndNY1pUV5VZw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*XJkaJCU4qvndNY1pUV5VZw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*XJkaJCU4qvndNY1pUV5VZw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*XJkaJCU4qvndNY1pUV5VZw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*XJkaJCU4qvndNY1pUV5VZw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*XJkaJCU4qvndNY1pUV5VZw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*MxxeMhbirfw3CcN9Vs4eRg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*MxxeMhbirfw3CcN9Vs4eRg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*MxxeMhbirfw3CcN9Vs4eRg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*MxxeMhbirfw3CcN9Vs4eRg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*MxxeMhbirfw3CcN9Vs4eRg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*MxxeMhbirfw3CcN9Vs4eRg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*MxxeMhbirfw3CcN9Vs4eRg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*MxxeMhbirfw3CcN9Vs4eRg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*MxxeMhbirfw3CcN9Vs4eRg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*MxxeMhbirfw3CcN9Vs4eRg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*MxxeMhbirfw3CcN9Vs4eRg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*MxxeMhbirfw3CcN9Vs4eRg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*MxxeMhbirfw3CcN9Vs4eRg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*MxxeMhbirfw3CcN9Vs4eRg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*MxxeMhbirfw3CcN9Vs4eRg.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The chrome extension is really helpful as well.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="iframe"><pre><span>This extension shows you the following details about research papers:<br/>✨ 2-line summary<br/>✨ Availability source code, videos, and discussions<br/>✨ Popularity on Twitter<br/>✨ Conferences</span></pre></div><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:80%;"><iframe  scrolling="auto" width="640.0" height="480.0" frameborder="0" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F5sv57njUQPY%3Fstart%3D7%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D5sv57njUQPY&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F5sv57njUQPY%2Fhqdefault.jpg&key=a19fcc184b9711e1b4764040d3dc5c07&type=text%2Fhtml&schema=youtube" allowfullscreen=""></iframe></div><br><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">4. <a href="https://aman.ai/papers/#noise-contrastive-estimation-a-new-estimation-principle-for-unnormalized-statistical-models" target="_self">Paper lists made by Aman</a></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">A summary of key papers in Computer Vision, NLP, and Speech recognition.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*BdkxFnegXS0g0sHUNW-Akw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*BdkxFnegXS0g0sHUNW-Akw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*BdkxFnegXS0g0sHUNW-Akw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*BdkxFnegXS0g0sHUNW-Akw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*BdkxFnegXS0g0sHUNW-Akw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*BdkxFnegXS0g0sHUNW-Akw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*BdkxFnegXS0g0sHUNW-Akw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*BdkxFnegXS0g0sHUNW-Akw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*BdkxFnegXS0g0sHUNW-Akw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*BdkxFnegXS0g0sHUNW-Akw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*BdkxFnegXS0g0sHUNW-Akw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*BdkxFnegXS0g0sHUNW-Akw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*BdkxFnegXS0g0sHUNW-Akw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*BdkxFnegXS0g0sHUNW-Akw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*BdkxFnegXS0g0sHUNW-Akw.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">5. <a href="https://deeplearn.org" target="_self">Deep Learning Monitor</a></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Another website where you can find the hot papers on social media.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">The great feature is that you can create some monitors with the keywords related to the topic of interest and check new updates every one or two weeks. Once you find a good paper and you log in Mendeley on this website, you can directly send it to your Mendeley account.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*3HtQpm1hSI6ApIAIOl3YvQ.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*3HtQpm1hSI6ApIAIOl3YvQ.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*3HtQpm1hSI6ApIAIOl3YvQ.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*3HtQpm1hSI6ApIAIOl3YvQ.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*3HtQpm1hSI6ApIAIOl3YvQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*3HtQpm1hSI6ApIAIOl3YvQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*3HtQpm1hSI6ApIAIOl3YvQ.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*3HtQpm1hSI6ApIAIOl3YvQ.png 640w, https://miro.medium.com/v2/resize:fit:720/1*3HtQpm1hSI6ApIAIOl3YvQ.png 720w, https://miro.medium.com/v2/resize:fit:750/1*3HtQpm1hSI6ApIAIOl3YvQ.png 750w, https://miro.medium.com/v2/resize:fit:786/1*3HtQpm1hSI6ApIAIOl3YvQ.png 786w, https://miro.medium.com/v2/resize:fit:828/1*3HtQpm1hSI6ApIAIOl3YvQ.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*3HtQpm1hSI6ApIAIOl3YvQ.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*3HtQpm1hSI6ApIAIOl3YvQ.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*3HtQpm1hSI6ApIAIOl3YvQ.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*cz1BAvWn42uztuayw0dm-w.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*cz1BAvWn42uztuayw0dm-w.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*cz1BAvWn42uztuayw0dm-w.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*cz1BAvWn42uztuayw0dm-w.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*cz1BAvWn42uztuayw0dm-w.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*cz1BAvWn42uztuayw0dm-w.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*cz1BAvWn42uztuayw0dm-w.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*cz1BAvWn42uztuayw0dm-w.png 640w, https://miro.medium.com/v2/resize:fit:720/1*cz1BAvWn42uztuayw0dm-w.png 720w, https://miro.medium.com/v2/resize:fit:750/1*cz1BAvWn42uztuayw0dm-w.png 750w, https://miro.medium.com/v2/resize:fit:786/1*cz1BAvWn42uztuayw0dm-w.png 786w, https://miro.medium.com/v2/resize:fit:828/1*cz1BAvWn42uztuayw0dm-w.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*cz1BAvWn42uztuayw0dm-w.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*cz1BAvWn42uztuayw0dm-w.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*cz1BAvWn42uztuayw0dm-w.png"></picture></div><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><div class="sketchy"><a href="https://medium.com/mlearning-ai/mlearning-ai-submission-suggestions-b51e2b130bfb"><h2 style="color:blueviolet; font-family:Arial, Helvetica, sans-serif; font-size:25px;">Mlearning.ai Submission Suggestions</h2><h3 style="color:rgb(45, 34, 54); font-family:Arial, Helvetica, sans-serif; font-size:20px;">How to become a writer on Mlearning.ai</h3><p>medium.com</p></a></div></div></div></div></section><br><?php include_once 'Elemental/footer.php'; ?>