<!DOCTYPE html>
                <html>
                <head>
                    <title>What is good/bad code? An illustrated example for non-programmers</title>
                <?php include_once 'Elemental/header.php'; ?><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><br><br><h5> This article is reformatted from originally published at <a href="https://medium.com/@todbotts.triangles/what-is-good-bad-code-an-illustrated-example-for-non-programmers-1222b600a0f0"><strong>TDS(Towards Data Science)</strong></a></h5></br><h5> <a href="https://medium.com/@todbotts.triangles?source=post_page-----1222b600a0f0--------------------------------">Author : Todd Gillies</a> </h5></div></div></div></section><section data-bs-version="5.1" class="content4 cid-tt5SM2WLsM" id="content4-2" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="title col-md-12 col-lg-9">
                        <h3 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                            <strong>What is good/bad code? An illustrated example for non-programmers</h3></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I once read a quote somewhere that basically had the following content:</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">“The lives of many people in the modern world depend on software, such as that which controls flight systems in large commercial airliners, and yet the field of software development is mostly unregulated. Anybody can become a self-taught software developer, and there are none of the certifications or rigors in place as there are for other high-stakes professions, such as sky-rise architecture or neurosurgery. It is a <strong>dangerously unregulated field</strong>, as a few lines of <strong>bad code</strong> could literally cause a loss of life, depending on the circumstances.</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">I seem to remember that this was in some kind of mainstream publication. The theme of the article, I guess, was “<em>Watch out for bad code, it can kill you, oh, but wait, it’s invisible so never mind!</em>” Certainly a soothing message for readers, don’t you think? Seems in retrospect that the article was simply trying to sensationalize the lurking presence of ‘bad code’ in the airliners, trains, and self-driving cars that increasingly surround us, and thus increase readership.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">So what is ‘Bad Code’, as a layperson?</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">As a person who writes, reviews and <em>refactors</em> code (meaning, <em>to re-write in a more concise and usable fashion</em>) for about 5 hours a day, I know what code is (and what bad code is, believe you me!). I sometimes lose sight of the fact that many people<strong> don’t</strong> have a concept of what code is.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">For those people, I offer the following answer to the question “You’re a coder, what do you do?”:</p></div></div></div></section><section data-bs-version="5.1" class="content7 cid-ttbhFZC4Ql" id="content7-8" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
        <div class="container"><div class="row justify-content-center"><div class="col-12 col-md-9"><blockquote><p class="ff4">“I build<strong> tiny assemblies of small doorways</strong>, that open and close in various ways and in various configurations. When the doorways open, electrons can pass through, and when they close, electrons are blocked. As the doorways are too small to build by hand, I have to have them built by my computer. Depending on the words I type into my computer, it builds various types of these small doorways on my behalf.”</p></blockquote></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Make no mistake, as the above answer states, software developers/coders/programmers <em>are actually building things which have physical presence</em>, but are just too small to see (which can be envisioned, however, as assemblies or sets of small doorways). That’s crazy enough in itself, but if you can at least imagine that, you have achieved a conceptual understanding of what “coding” is, congratulations! But back to the question in the title of this section — What is ’<em>Bad</em> Code?’</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Keeping with our <em>tiny assemblies of small doorways</em> analogy, I will say that <strong>bad code</strong> means that you have <strong>too many doorways</strong>, arranged in an unnecessarily <strong>repetitive</strong> or <strong>complex</strong> manner.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">As that is hard to visualize or explain any further with the doorways analogy, at this point I would like to offer another analogy, as written and illustrated below.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Build me a knob turner!</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Say we want to build a knob-turner. A knob that can be rotated, which will in turn rotate another knob in a remote location. The product requirement is as shown below. Turn one knob, and another knob some distance away will turn as well:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*z59DDguTT_SZ12I26zuurg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*z59DDguTT_SZ12I26zuurg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*z59DDguTT_SZ12I26zuurg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*z59DDguTT_SZ12I26zuurg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*z59DDguTT_SZ12I26zuurg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*z59DDguTT_SZ12I26zuurg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*z59DDguTT_SZ12I26zuurg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*z59DDguTT_SZ12I26zuurg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*z59DDguTT_SZ12I26zuurg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*z59DDguTT_SZ12I26zuurg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*z59DDguTT_SZ12I26zuurg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*z59DDguTT_SZ12I26zuurg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*z59DDguTT_SZ12I26zuurg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*z59DDguTT_SZ12I26zuurg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*z59DDguTT_SZ12I26zuurg.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">This is the system we need — a knob that turns another knob.</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Bad code thinks only of the problem at hand</strong>, and proposes the easiest solution — a knob and a knob-turner, connected by a semi-flexible rod. Bad code wins the Occam’s razor prize, at this early stage. <strong>Good code seems to be an overkill at first</strong>, and makes use of a rubber belt and 2 wheels.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*HNFa6ZnRJaiT0tgaeYPXMg.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*HNFa6ZnRJaiT0tgaeYPXMg.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*HNFa6ZnRJaiT0tgaeYPXMg.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*HNFa6ZnRJaiT0tgaeYPXMg.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*HNFa6ZnRJaiT0tgaeYPXMg.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*HNFa6ZnRJaiT0tgaeYPXMg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*HNFa6ZnRJaiT0tgaeYPXMg.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*HNFa6ZnRJaiT0tgaeYPXMg.png 640w, https://miro.medium.com/v2/resize:fit:720/1*HNFa6ZnRJaiT0tgaeYPXMg.png 720w, https://miro.medium.com/v2/resize:fit:750/1*HNFa6ZnRJaiT0tgaeYPXMg.png 750w, https://miro.medium.com/v2/resize:fit:786/1*HNFa6ZnRJaiT0tgaeYPXMg.png 786w, https://miro.medium.com/v2/resize:fit:828/1*HNFa6ZnRJaiT0tgaeYPXMg.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*HNFa6ZnRJaiT0tgaeYPXMg.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*HNFa6ZnRJaiT0tgaeYPXMg.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*HNFa6ZnRJaiT0tgaeYPXMg.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">One point for Bad Code! Simple, with few moving parts!</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Requirement Change! The knob will be re-located!</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">As always happens in the development cycle, at some point, the customer requirement changes. In our analogy here, the customer now wants a knob turner that can rotate another knob located forward <em>and to the side of </em>the original knob, as shown below:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*VfQkaesbzNsG67HnjH162Q.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*VfQkaesbzNsG67HnjH162Q.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*VfQkaesbzNsG67HnjH162Q.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*VfQkaesbzNsG67HnjH162Q.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*VfQkaesbzNsG67HnjH162Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*VfQkaesbzNsG67HnjH162Q.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*VfQkaesbzNsG67HnjH162Q.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*VfQkaesbzNsG67HnjH162Q.png 640w, https://miro.medium.com/v2/resize:fit:720/1*VfQkaesbzNsG67HnjH162Q.png 720w, https://miro.medium.com/v2/resize:fit:750/1*VfQkaesbzNsG67HnjH162Q.png 750w, https://miro.medium.com/v2/resize:fit:786/1*VfQkaesbzNsG67HnjH162Q.png 786w, https://miro.medium.com/v2/resize:fit:828/1*VfQkaesbzNsG67HnjH162Q.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*VfQkaesbzNsG67HnjH162Q.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*VfQkaesbzNsG67HnjH162Q.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*VfQkaesbzNsG67HnjH162Q.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Oops! Product requirement change!</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><strong>Bad code needs to add a few jerry-rigged components</strong>, making the whole system more rickety and susceptible to failure. <strong>Good code needs only slight adjustment when new requirements come in</strong>, and simply uses a longer rubber belt to solve this problem.</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*InuBj5oL_Q5g--BGHDF9OA.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*InuBj5oL_Q5g--BGHDF9OA.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*InuBj5oL_Q5g--BGHDF9OA.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*InuBj5oL_Q5g--BGHDF9OA.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*InuBj5oL_Q5g--BGHDF9OA.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*InuBj5oL_Q5g--BGHDF9OA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*InuBj5oL_Q5g--BGHDF9OA.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*InuBj5oL_Q5g--BGHDF9OA.png 640w, https://miro.medium.com/v2/resize:fit:720/1*InuBj5oL_Q5g--BGHDF9OA.png 720w, https://miro.medium.com/v2/resize:fit:750/1*InuBj5oL_Q5g--BGHDF9OA.png 750w, https://miro.medium.com/v2/resize:fit:786/1*InuBj5oL_Q5g--BGHDF9OA.png 786w, https://miro.medium.com/v2/resize:fit:828/1*InuBj5oL_Q5g--BGHDF9OA.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*InuBj5oL_Q5g--BGHDF9OA.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*InuBj5oL_Q5g--BGHDF9OA.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*InuBj5oL_Q5g--BGHDF9OA.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Bad code has become an amalgam of rickety components…</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Requirement Change! The knob needs to turn slower!</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Finally, our customer has decided that they want the knobs to turn at different rates. A small turn of the input knob should result in a large turn of the connected knob.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">In light of this new requirement, <strong>bad code needs to add even more components to the system</strong>, making it even more complex. On the other hand, <strong>good code again needs only slight adjustment</strong>, using a larger wheel on the connected knob side:</p></div></div></div></section><section data-bs-version="5.1" class="image3 cid-tt612oXwA9" id="image3-5" style="padding-top:0px; padding-bottom:0px; background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9">
                <div class="image-wrapper"><div class="image_style" style="width:96%;"><picture><source sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/format:webp/1*DfXGxAO0C5S1weGjwqRNjw.png 640w, https://miro.medium.com/v2/resize:fit:720/format:webp/1*DfXGxAO0C5S1weGjwqRNjw.png 720w, https://miro.medium.com/v2/resize:fit:750/format:webp/1*DfXGxAO0C5S1weGjwqRNjw.png 750w, https://miro.medium.com/v2/resize:fit:786/format:webp/1*DfXGxAO0C5S1weGjwqRNjw.png 786w, https://miro.medium.com/v2/resize:fit:828/format:webp/1*DfXGxAO0C5S1weGjwqRNjw.png 828w, https://miro.medium.com/v2/resize:fit:1100/format:webp/1*DfXGxAO0C5S1weGjwqRNjw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/format:webp/1*DfXGxAO0C5S1weGjwqRNjw.png 1400w" type="image/webp"/><source data-testid="og" sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" srcset="https://miro.medium.com/v2/resize:fit:640/1*DfXGxAO0C5S1weGjwqRNjw.png 640w, https://miro.medium.com/v2/resize:fit:720/1*DfXGxAO0C5S1weGjwqRNjw.png 720w, https://miro.medium.com/v2/resize:fit:750/1*DfXGxAO0C5S1weGjwqRNjw.png 750w, https://miro.medium.com/v2/resize:fit:786/1*DfXGxAO0C5S1weGjwqRNjw.png 786w, https://miro.medium.com/v2/resize:fit:828/1*DfXGxAO0C5S1weGjwqRNjw.png 828w, https://miro.medium.com/v2/resize:fit:1100/1*DfXGxAO0C5S1weGjwqRNjw.png 1100w, https://miro.medium.com/v2/resize:fit:1400/1*DfXGxAO0C5S1weGjwqRNjw.png 1400w"/><img alt="" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/1*DfXGxAO0C5S1weGjwqRNjw.png"></picture></div><p class="mbr-description mbr-fonts-style mt-2 align-center display-12 text-muted" style="font-size:12px;">Two inserts and a funny-shaped rod? Who whilst maintain thou, bad code?</p><br></div></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5">Analogy Afterword: So what?</h4></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;"><mark>As shown above, good code often seems like an overkill when requirements are simple, but then really shines when customer requirements change (as they always do).</mark> In other words, it scales and changes well. Bad code, on the other hand, seems simple and great for simple problems, but becomes a nightmare when the system changes or increases in complexity.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">But maybe you’re thinking, <em>“Well, both of the systems outlined above achieve the same result — the knob turner works successfully in either case.”</em></p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">That is true — and fine for solo-coding or hobbyist projects. Lord knows that I’ve written tens of thousands of lines of bad code (vanilla JS, in my case), but it was okay, as I never had to maintain the code or add to it in any way (check out <a href="https://github.com/todbott/python-gui-builder/blob/master/js/canvas_0618.js" target="_self">these 2,422 lines</a> of source code for <a href="http://www.python-gui-builder.com" target="_self">www.python-gui-builder.com</a>, one of my hobby sites from 2020). The code worked, and I deployed it, and have never looked back.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">However, professional coding is at heart a collaborative effort, and whatever code you write will undoubtedly be read and edited continuously by other coders, either in the present or in the future. Those coders will have a much easier and more efficient workday if the code is as easy to understand as possible.</p></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><ol><li class="ff3" style="font-size:22px;"><em>“Here’s our knob turner, it consists of 2 wheels and a belt”</em>, or</li><li class="ff3" style="font-size:22px;"><em>“This is the insert to hold the connecting rod, this is the connecting rod, and you have to put the end of it into a little hole up here in this other insert…”</em></li></ol></div></div></div></section><section data-bs-version="5.1" class="content5 cid-tt5UseJ9wk" id="content5-4" style="padding-top:0px; padding-bottom:0px;background-color: rgb(255, 255, 255);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9"><p class="ff3" style="font-size:22px;">Which would <strong>you</strong> rather hear, as a junior developer taking over the code base from your senior? :)</p></div></div></div></section><?php include_once 'Elemental/footer.php'; ?>